export const Deutch: Record<string, string> = {
    documents: "Dokumente",
    document_hub: "Dokumenten Hub",
    type: "Typ",
    name: "Name",
    created_at: "Erstellt am",
    administration: "Verwaltung",
    create: "Erstellen",
    create_file: "Datei erstellen",
    create_folder: "Ordner erstellen",
    create_a_folder: "Erstellen Sie einen Ordner",
    public: "Öffentlich",
    cancel: "Abbrechen",
    placeholder: "Bitte geben Sie en Ordnernamen ein",
    placeholder_file: "Bitte geben Sie den Dateinamen ein",
    edit: "Bearbeiten",
    edit_folder: "Ordner bearbeiten",
    edit_file: "Datei bearbeiten",
    file: "Datei",
    upload_file: "Datei hochladen",
    update: "Aktualisieren",
    save: "Speichern",
    rename: "Umbenennen",
    are_you_sure_you_want_to_delete: "Sind Sie sicher, dass Sie löschen möchten",
    delete: "Löschen",
    a_file: "Einer Datei",
    a_folder: "Ein Ordner",
    add: "Hinzufügen",
    add_file: "Datei hinzufügen",
    navigation_administration_button_text: "Administration",
    navigation_administration_button_text_exit: "Verlassen",
    navigation_theme_toggle_light: "Hell",
    navigation_theme_toggle_dark: "Dunkel",
    navigation_theme_toggle_system: "System",
    navigation_language_toggle_english: "English",
    navigation_language_toggle_german: "Deutsch",
    navigation_language_toggle_french: "Französisch",
    navigation_language_toggle_spanish: "Spanisch",
    navigation_language_toggle_italian: "Italienisch",
    navigation_language_toggle_portuguese: "Portugiesisch",
    navigation_language_toggle_russian: "Russisch",
    navigation_language_toggle_mandarin: "Mandarin",
    navigation_search_placeholder: "Suchen",
    navigation_footer_text: "Powered by",
    navigation_footer_text_product: "Product",
    search_courseCounter_currentCourses: "Aktuell existierende Kurse",
    news_no_posts_found: "Keine Posts gefunden",
    news_comments_button_label: "Kommentare",
    news_comments_input_placeholder: "Geben Sie Ihren Kommentar ein...",
    news_comments_showmore_label: "Mehr anzeigen +",
    news_comments_reply_button_label: "Antworten",
    live_event_futureAndPast_button_text_future: "Zukünftige Events",
    live_event_futureAndPast_button_text_past: "Vergangene Events",
    live_event_filter_button_text: "Filtern",
    live_event_filter_title: "Live Events Filtern",
    live_event_filter_description: "Sie können Ereignisse filtern, indem Sie das Start- und/oder Enddatum eines Ereignisses angeben.",
    live_event_filter_applyFilter_button_text: "Filter anwenden",
    live_event_filter_clearFilter_button_text: "Filter löschen",
    courses_createCourse_button_text: "Kurs erstellen",
    courses_noCourses_text: "Keine Kurse gefunden",
    adminTable_previous_button_text: "Vorherige",
    adminTable_next_button_text: "Nächste",
    courses_searchCourses_placeholder: "Kurse filtern...",
    actions_unpublish: "Veröffentlichung aufheben",
    actions_publish: "Veröffentlichen",
    courses_titleForm_title: "Kurstitel",
    courses_titleForm_cancel: "Abbrechen",
    courses_titleForm_edit: "Titel bearbeiten",
    courses_titleForm_placeholder: "z.B. 'Fortgeschrittene Webentwicklung'",
    courses_titleForm_save: "Speichern",
    courses_descriptionForm_title: "Kursbeschreibung",
    courses_descriptionForm_cancel: "Abbrechen",
    courses_descriptionForm_edit: "Beschreibung bearbeiten",
    courses_descriptionForm_empty: "Keine Beschreibung",
    courses_descriptionForm_placeholder: "z.B. 'Dieser Kurs behandelt...'",
    courses_descriptionForm_save: "Speichern",
    course_imageForm_title: "Kursbild",
    courses_imageForm_cancel: "Abbrechen",
    courses_imageForm_add: "Ein Bild hinzufügen",
    courses_imageForm_edit: "Bild bearbeiten",
    courses_imageForm_aspectRatioRecoomendation: "Empfohlenes Seitenverhältnis 16:9",
    courses_categoryForm_title: "Kurskategorie",
    courses_categoryForm_cancel: "Abbrechen",
    courses_categoryForm_edit: "Kategorie bearbeiten",
    courses_categoryForm_noCategory: "Keine Kategorie",
    courses_categoryForm_save: "Speichern",
    courses_chaptersForm_title: "Kapitel",
    courses_chaptersForm_cancel: "Abbrechen",
    courses_chaptersForm_addChapter: "Kapitel hinzufügen",
    courses_chaptersForm_placeholder: "z.B. 'Einführung in den Kurs'",
    courses_chaptersForm_save: "Erstellen",
    courses_chaptersForm_noChapters: "Keine Kapitel",
    courses_chaptersForm_reorderInstructions: "Ziehen und ablegen, um die Kapitel neu zu ordnen",
    course_priceForm_title: "Kurspreis",
    courses_priceForm_cancel: "Abbrechen",
    courses_priceForm_edit: "Preis bearbeiten",
    courses_priceForm_noPrice: "Kein Preis",
    courses_priceForm_placeholder: "Legen Sie einen Preis für Ihren Kurs fest",
    courses_priceForm_save: "Speichern",
    course_attachmentForm_title: "Anlagen für dieses Kapitel",
    course_attachmentForm_cancel: "Abbrechen",
    course_attachmentForm_add: "Eine Datei hinzufügen",
    course_attachmentForm_noAttachments: "Noch keine Anlage",
    course_attachmentForm_Recoomendation: "Fügen Sie alles hinzu, was Ihre Studierenden zur Absolvierung des Kurses benötigen könnten.",
    confirmModal_DialogHeader: "Sind Sie sicher?",
    confirmModal_DialogDescription: "Diese Aktion kann nicht rückgängig gemacht werden.",
    confirmModal_DialogConfirm: "Bestätigen",
    confirmModal_DialogCancel: "Abbrechen",
    chapter_TitleForm_title: "Kapiteltitel",
    chapter_TitleForm_cancel: "Abbrechen",
    chapter_TitleForm_edit: "Titel bearbeiten",
    chapter_TitleForm_save: "Speichern",
    chapter_TitleForm_placeholder: "z.B. 'Einführung in den Kurs'",
    chapter_chapterDescriptionForm_title: "Kapitelbeschreibung",
    chapter_chapterDescriptionForm_cancel: "Abbrechen",
    chapter_chapterDescriptionForm_edit: "Beschreibung bearbeiten",
    chapter_chapterDescriptionForm_noDescription: "Keine Beschreibung",
    chapter_chapterDescriptionForm_save: "Speichern",
    chapter_accessForm_title: "Kapitelzugang",
    chapter_accessForm_cancel: "Abbrechen",
    chapter_accessForm_edit: "Zugang bearbeiten",
    chapter_accessForm_isFree: "Dieses Kapitel ist kostenlos.",
    chapter_accessForm_isNotFree: "Dieses Kapitel ist nicht kostenlos.",
    chapter_accessForm_description: "Markieren Sie dieses Kästchen, wenn Sie dieses Kapitel kostenlos machen möchten.",
    chapter_accessForm_save: "Speichern",
    chapter_actions_unpublish: "Veröffentlichung aufheben",
    chapter_actions_publish: "Veröffentlichen",
    chapter_VideoForm_title: "Kapitelvideo",
    chapter_VideoForm_cancel: "Abbrechen",
    chapter_VideoForm_edit: "Video bearbeiten",
    chapter_VideoForm_addVideo: "Ein Video hinzufügen",
    chapter_VideoForm_placeholder: "Vimeo-Teilen-Link",
    chapter_VideoForm_urlWarning: "Seite neu laden, wenn das Video nicht angezeigt wird.",
    post_createPost_button_text: "Beitrag erstellen",
    post_noPosts_text: "Keine Beiträge gefunden.",
    post_search_placeholder_text: "Beiträge filtern...",
    posts_actions_unpublish: "Veröffentlichung aufheben",
    posts_actions_publish: "Veröffentlichen",
    post_TitleForm_title: "Beitragstitel",
    post_TitleForm_cancel: "Abbrechen",
    post_TitleForm_edit: "Titel bearbeiten",
    post_TitleForm_placeholder: "z.B. 'Fortgeschrittene Webentwicklung'",
    post_TitleForm_save: "Speichern",
    post_DescriptionForm_title: "Beitragsbeschreibung",
    post_DescriptionForm_cancel: "Abbrechen",
    post_DescriptionForm_edit: "Beschreibung bearbeiten",
    post_DescriptionForm_noDescription: "Keine Beschreibung",
    post_DescriptionForm_save: "Speichern",
    post_CategoryForm_title: "Beitragskategorie",
    post_CategoryForm_cancel: "Abbrechen",
    post_CategoryForm_edit: "Kategorie bearbeiten",
    post_CategoryForm_noCategory: "Keine Kategorie",
    post_CategoryForm_save: "Speichern",
    post_ImageForm_title: "Beitragsbild",
    post_ImageForm_cancel: "Abbrechen",
    post_ImageForm_add: "Ein Bild hinzufügen",
    post_ImageForm_edit: "Bild bearbeiten",
    post_ImageForm_help: "Empfohlenes Seitenverhältnis 16:9",
    categories_search_placeholder_text: "Kategorien filtern...",
    categories_createCategory_button_text: "Kategorie erstellen",
    categories_noCategories_text: "Keine Ergebnisse.",
    categories_TitleForm_title: "Kategoriename",
    categories_TitleForm_cancel: "Abbrechen",
    categories_TitleForm_edit: "Name bearbeiten",
    categories_TitleForm_placeholder: "z.B. 'Fortgeschrittene Webentwicklung'",
    categories_TitleForm_save: "Speichern",
    category_ColorForm_title: "Kategoriefarbe",
    categories_ColorForm_cancel: "Abbrechen",
    categories_ColorForm_edit: "Bearbeiten",
    categories_ColorForm_save: "Speichern",
    post_CategoryTypeForm_title: "Kategorietyp",
    post_CategoryTypeForm_isCourseCategory: "Kurskategorie",
    post_CategoryTypeForm_isNewsCategory: "Nachrichtenkategorie",
    post_CategoryTypeForm_isLiveEventCategory: "Live-Veranstaltungskategorie",
    post_CategoryTypeForm_save: "Speichern",
    customize_ContainerLinkForm_title: "Container-Link",
    customize_ContainerLinkForm_cancel: "Abbrechen",
    customize_ContainerLinkForm_edit: "Titel bearbeiten",
    customize_ContainerLinkForm_placeholder: "z.B. 'Fortgeschrittene Webentwicklung'",
    customize_ContainerLinkForm_save: "Speichern",
    customize_ImageForm_title: "Container-Bild",
    customize_ImageForm_cancel: "Abbrechen",
    customize_ImageForm_addImage: "Ein Bild hinzufügen",
    customize_ImageForm_edit: "Bild bearbeiten",
    customize_ImageForm_imageHint: "Empfohlenes Seitenverhältnis 16:9",
    customize_PrimaryColorForm_title: "Primärfarbe",
    customize_PrimaryColorForm_cancel: "Abbrechen",
    customize_PrimaryColorForm_edit: "Bearbeiten",
    customize_PrimaryColorForm_save: "Speichern",
    users_search_placeholder_text: "Profile filtern...",
    users_noUsers_text: "Keine Benutzer.",
    user_TitleForm_title: "Benutzername",
    user_MailForm_title: "Benutzer-E-Mail",
    user_RoleForm_title: "Profilrolle",
    user_RoleForm_cancel: "Abbrechen",
    user_RoleForm_edit: "Rolle bearbeiten",
    user_RoleForm_save: "Speichern",
    chat_ChatMessages_loading: "Nachrichten laden...",
    chat_ChatMessages_error: "Etwas ist schiefgelaufen!",
    chat_ChatMessages_loadPreviousMessages: "Vorherige Nachrichten laden",
    chat_ChatItem_viewPDF: "PDF-Datei",
    chat_ChatItem_edited: "(bearbeitet)",
    chat_ChatItem_editMessage: "Nachricht bearbeiten",
    chat_ChatItem_saveChanges: "Speichern",
    chat_ChatItem_editMessageHint: "Drücken Sie Escape zum Abbrechen, Enter zum Speichern",
    chat_ChatInput_placeholder: "Nachricht",
    chat_initialModal_title: "Ihren Server erstellen",
    chat_initialModal_description: "Geben Sie Ihrem Server eine Persönlichkeit mit einem Namen und einem Bild. Sie können dies später immer ändern.",
    chat_initialModal_serverName: "Servername",
    chat_initialModal_serverName_placeholder: "Servernamen eingeben",
    chat_initialModal_createServer: "Erstellen",
    chat_serverSection_createChannel: "Kanal erstellen",
    chat_serverSection_manageMembers: "Mitglieder verwalten",
    chat_server_search_placeholder: "Suche",
    chat_server_search_notFound: "Keine Ergebnisse gefunden",
    chat_server_invite: "Leute einladen",
    chat_server_edit: "Server bearbeiten",
    chat_server_manage_members: "Mitglieder verwalten",
    chat_server_create_channel: "Kanal erstellen",
    chat_server_delete: "Server löschen",
    chat_server_addServer: "Einen Server hinzufügen",
    chat_channel_edit: "Bearbeiten",
    chat_channel_delete: "Löschen",
    chat_chatItem_edit: "Bearbeiten",
    chat_chatItem_delete: "Löschen",
    chat_socket_reconnecting: "Fallback: Polling alle 1s",
    chat_socket_connected: "Live",
    chat_modal_create_server_title: "Ihren Server anpassen",
    chat_modal_create_server_description: "Geben Sie Ihrem Server eine Persönlichkeit mit einem Namen und einem Bild. Sie können dies später immer ändern.",
    chat_modal_create_server_name: "Servername",
    chat_modal_create_server_name_placeholder: "Servernamen eingeben",
    chat_modal_create_server_create: "Erstellen",
    chat_modal_create_channel_title: "Kanal erstellen",
    chat_modal_create_channel_name: "Kanalname",
    chat_modal_create_channel_name_placeholder: "Kanalnamen eingeben",
    chat_modal_create_channelType_name: "Kanaltyp",
    chat_modal_create_channelType_placeholder: "Einen Kanaltyp auswählen",
    chat_modal_create_channel_create: "Erstellen",
    chat_modal_invite_title: "Freunde einladen",
    chat_modal_invite_link_label: "Servereinladungslink",
    chat_modal_invite_new: "Einen neuen Link generieren",
    chat_modal_manageMembers_title: "Mitglieder verwalten",
    chat_modal_manageMembers_description: "Mitglieder",
    chat_modal_manageMembers_role_label: "Rolle",
    chat_modal_manageMembers_role_guest: "Gast",
    chat_modal_manageMembers_role_moderator: "Moderator",
    chat_modal_manageMembers_kick: "Rauswerfen",
    chat_modal_delete_server_title: "Server löschen",
    chat_modal_delete_server_description_1: "Sind Sie sicher, dass Sie dies tun möchten?",
    chat_modal_delete_server_description_2: "wird dauerhaft gelöscht.",
    chat_modal_delete_server_cancel_button: "Abbrechen",
    chat_modal_delete_server_delete_button: "Bestätigen",
    chat_modal_edit_channel_title: "Kanal bearbeiten",
    chat_modal_edit_channel_name: "Kanalname",
    chat_modal_edit_channel_name_placeholder: "Kanalnamen eingeben",
    chat_modal_edit_channel_type: "Kanaltyp",
    chat_modal_edit_channel_save: "Speichern",
    chat_modal_edit_channel_type_placeholder: "Einen Kanaltyp auswählen",
    chat_modal_deleteChannel_title: "Kanal löschen",
    chat_modal_deleteChannel_description_1: "Sind Sie sicher, dass Sie dies tun möchten?",
    chat_modal_deleteChannel_description_2: "wird dauerhaft gelöscht.",
    chat_modal_deleteChannel_cancel_button: "Abbrechen",
    chat_modal_deleteChannel_delete_button: "Bestätigen",
    chat_modal_leaveServer_title: "Server verlassen",
    chat_modal_leaveServer_description_1: "Sind Sie sicher, dass Sie verlassen möchten",
    chat_modal_leaveServer_cancel: "Abbrechen",
    chat_modal_leaveServer_leave: "Bestätigen",
    chat_modal_messageFile_title: "Eine Anlage hinzufügen",
    chat_modal_messageFile_description: "Eine Datei als Nachricht senden",
    chat_modal_messageFile_submit: "Senden",
    createCourse_title: "Benennen Sie Ihren Kurs",
    createCourse_description: "Wie möchten Sie Ihren Kurs benennen? Keine Sorge, Sie können dies später ändern.",
    createCourse_form_label: "Kurstitel",
    createCourse_form_description: "Was werden Sie in diesem Kurs lehren?",
    createCourse_form_placeholder: "z.B. 'Fortgeschrittene Webentwicklung'",
    createCourse_cancel: "Abbrechen",
    createCourse_submit: "Fortfahren",
    createPost_title: "Benennen Sie Ihren Beitrag",
    createPost_description: "Wie möchten Sie Ihren Beitrag benennen? Keine Sorge, Sie können dies später ändern.",
    createPost_form_label: "Beitragstitel",
    createPost_form_placeholder: "z.B. 'Fortgeschrittene Webentwicklung'",
    createPost_form_description: "Was möchten Sie Ihrer Gemeinschaft mitteilen?",
    createPost_cancel: "Abbrechen",
    createPost_submit: "Fortfahren",
    createLiveEvent_title: "Benennen Sie Ihre Live-Veranstaltung",
    createLiveEvent_description: "Wie möchten Sie Ihre Live-Veranstaltung benennen? Keine Sorge, Sie können dies später ändern.",
    createLiveEvent_form_label: "Veranstaltungstitel",
    createLiveEvent_form_placeholder: "z.B. 'Fortgeschrittene Webentwicklung'",
    createLiveEvent_form_description: "Was werden Sie in Ihrer Veranstaltung zeigen?",
    createLiveEvent_cancel: "Abbrechen",
    createLiveEvent_submit: "Weiter",
    createCategory_title: "Benennen Sie Ihre Kategorie",
    createCategory_description: "Wie möchten Sie Ihre Kategorie benennen? Keine Sorge, Sie können dies später ändern.",
    createCategory_form_label: "Kategoriename",
    createCategory_form_placeholder: "z.B. 'Fortgeschrittene Webentwicklung'",
    createCategory_form_description: "Was werden Sie auf Ihrer Plattform kategorisieren?",
    createCategory_cancel: "Abbrechen",
    createCategory_submit: "Speichern",
    liveEvent_createEvent_button_text: "Event erstellen",
    liveEvent_noEvent_text: "Keine Events gefunden.",
    liveEvent_filterEvents_placeholder: "Events filtern...",
    infocard_courses: "Kurse",
    infocard_course: "Kurs",
    infocard_inprogress: "In Bearbeitung",
    infocard_completed: "Abgeschlossen",
    no_courses: "Keine Kurse gefunden",
    customize_customizeCcontainer_title: "Passen Sie Ihren Container an",
    customize_customizeCcontainer_requiredFields: "Füllen Sie alle erforderlichen Felder aus",
    customize_customizeYourContainer: "Passen Sie Ihren Container an",
    requiredFields: "*erforderlich",
    customize_AddImageTitle: "Fügen Sie ein Bild als Logo hinzu",
    chat_welcome_title: "Willkommen bei #",
    chat_welcome_description: "Das ist der Anfang des #",
    chat_welcome_description2: "Kanals",
    chat_welcome_title_directMessage: "Das ist der Anfang Ihres Gesprächs mit",
    serverSidebar_textChannel: "Textkanäle",
    serverSidebar_videoChannel: "Videokanäle",
    serverSidebar_audioChannel: "Audiokanäle",
    serverSidebar_member: "Mitglieder",
    chat_serversection_label_text: "Textkanäle",
    chat_serversection_label_audio: "Audiokanäle",
    chat_serversection_label_video: "Videokanäle",
    chat_serversection_label_member: "Mitglieder",
    chat_server_search_command_placeholder: "Alle Kanäle und Mitglieder durchsuchen",
    course_setup_title: "Kurseinrichtung",
    course_setup_undertitle: "Füllen Sie alle erforderlichen Felder aus",
    course_setup_course_information_title: "Passen Sie Ihren Kurs an",
    course_setup_price_title: "Verkaufen Sie Ihren Kurs",
    course_setup_chapters_title: "Kurskapitel",
    course_setup_attachments_title: "Ressourcen & Anhänge",
    courses_chapter_backToCourse_button_text: "Zurück zur Kurseinrichtung",
    courses_chapter_title: "Kapitelerstellung",
    courses_chapter_undertitle: "Füllen Sie alle Felder aus",
    course_chapter_customize_title: "Passen Sie Ihr Kapitel an",
    course_chapter_access: "Zugangseinstellungen",
    course_chapter_video: "Ein Video hinzufügen",
    courses_setup_free_badge: "Kostenlos",
    courses_setup_published_text: "Veröffentlicht",
    courses_setup_draft_text: "Entwurf",
    post_setup_title: "Beitragseinrichtung",
    post_setup_undertitle: "Füllen Sie alle erforderlichen Felder aus",
    post_setup_customize_title: "Passen Sie Ihren Beitrag an",
    post_setup_category_title: "Passen Sie Ihre Kategorie an",
    post_setup_image_title: "Fügen Sie Ihrem Beitrag ein Bild hinzu",
    liveEvent_PremiumFeature_description: "Um Live-Veranstaltungen zu nutzen und Ihre digitalen und hybriden Veranstaltungen mit unserer Software einzurichten, müssen Sie das Community-Paket nutzen.",
    liveEvent_PremiumFeature_button_text: "Community-Paket kaufen",
    liveEvent_setup_title: "Veranstaltungseinrichtung",
    liveEvent_setup_undertitle: "Füllen Sie alle erforderlichen Felder aus",
    liveEvent_setup_customize_title: "Passen Sie Ihre Live-Veranstaltung an",
    liveEvent_setup_video_title: "Fügen Sie die Ressourcen zu Ihrer Veranstaltung hinzu",
    category_setup_title: "Kategorieeinrichtung",
    category_setup_undertitle: "Füllen Sie alle erforderlichen Felder aus",
    category_setup_customize_title: "Benennen Sie Ihre Kategorie",
    user_setup_title: "Benutzereinrichtung",
    user_setup_undertitle: "Füllen Sie alle erforderlichen Felder aus",
    user_setup_customize_title: "Passen Sie den Benutzer an",
    course_unpublish_banner: "Dieser Kurs ist nicht veröffentlicht. Er wird für die Benutzer nicht sichtbar sein.",
    post_unpublish_banner: "Dieser Beitrag ist nicht veröffentlicht. Er wird für die Benutzer nicht sichtbar sein.",
    liveEvent_unpublish_banner: "Diese Veranstaltung ist nicht veröffentlicht. Sie wird für die Benutzer nicht sichtbar sein.",
    category_unpublish_banner: "Diese Kategorie ist nicht veröffentlicht. Sie wird für die Benutzer nicht sichtbar sein.",
    chapter_unpublish_banner: "Dieses Kapitel ist nicht veröffentlicht. Es wird für die Benutzer nicht sichtbar sein.",
    analytics_total_revenue_label: "Gesamteinnahmen",
    analytics_total_sales_label: "Gesamtverkäufe",
    customize_NavColors_title: "Passen Sie Ihre Navigationsfarben an",
    customize_navBackgroundColorForm_title: "Navigationshintergrundfarbe",
    customize_navDarkBackgroundColorForm_title: "Navigationshintergrundfarbe Dunkelmodus",
    customize_navPrimaryColorForm_title: "Primärfarbe der Navigation",
    customize_navDarkPrimaryColorForm_title: "Primärfarbe der Navigation Dunkelmodus",
    customize_customizeNavigation_title: "Passen Sie Ihre Navigationsfarben an",
    customize_NavColorsDark_title: "Passen Sie Ihre Navigationsfarben für den Dunkelmodus an",
    settings_menu_containersettings_title: "Container-Einstellungen",
    settings_menu_navigationdesign_title: "Navigationsdesign",
    settings_backToMenu_button_text: "Zurück zum Menü",
    nav_item_browse: "Kurse",
    nav_item_dashboard: "Dashboard",
    nav_item_news: "Nachrichten",
    nav_item_liveEvent: "Live-Events",
    nav_item_chat: "Chat",
    nav_item_documents: "Dokumente",
    nav_admin_item_course: "Kurse",
    nav_admin_item_posts: "Beiträge",
    nav_admin_item_liveEvents: "Live-Events",
    nav_admin_item_categories: "Kategorien",
    nav_admin_item_users: "Benutzer",
    nav_admin_item_analytics: "Analytik",
    nav_admin_item_settings: "Einstellungen",
    customize_ImageFormDark_title: "Containerbild Dunkelmodus",
    settings_Container_IconForm_title: "Container-Symbol",
    privacy_policy_title: "Datenschutzrichtlinie & Nutzungsbedingungen",
    privacy_policy_description: "Um unsere Plattform weiterhin zu nutzen, überprüfen und akzeptieren Sie bitte unsere Datenschutzrichtlinie und Nutzungsbedingungen. Ihre Akzeptanz stellt sicher, dass Sie gelesen und verstanden haben, wie Ihre Daten behandelt werden, und dass Sie den Regeln unserer Plattform zustimmen. Wir schätzen Ihre Privatsphäre und bemühen uns, allen Nutzern eine sichere Umgebung zu bieten.",
    privacy_policy_button: "Ich akzeptiere es",
    user_isBannedForm_title: "Sperrstatus",
    user_isBannedForm_cancel: "Abbrechen",
    user_isBannedForm_edit: "Bearbeiten",
    user_isBannedForm_save: "Speichern",
    user_setup_settings_title: "Gefahrenzone",
    courses_authorForm_cancel: "Abbrechen",
    courses_authorForm_edit: "Autor bearbeiten",
    courses_authorForm_save: "Speichern",
    courses_authorForm_placeholder: "z.B. 'Max Mustermann'",
    courses_authorForm_title: "Authorenname",
    courses_authorForm_empty: "leer",
    infocard_completedChapters: "Abgeschlossene Kapitel",
    infocard_currentOnlineUsers: "Aktuelle Online-Benutzer",
    profile_manageAccount: "Konto verwalten",
    profile_signOut: "Abmelden",
    profile_change_customize_username: "Mein Profil",
    profile_TitleForm_title: "Benutzername",
    profile_TitleForm_cancel: "Abbrechen",
    profile_TitleForm_edit: "Bearbeiten",
    profile_TitleForm_placeholder: "Benutzername123",
    profile_TitleForm_save: "Speichern",
    courses_list_backToDashboard_button_text: "Zurück zum Dashboard",
    dashboard_courseTable_CourseStatus_Title: "Meine Kurse",
    dashboard_courseTable_courseName: "Kursname",
    dashboard_courseTable_paid: "Bezahlt",
    dashboard_courseTable_progress: "Fortschritt",
    dashboard_courseTable_chapter: "Kapitel",
    dashboard_courseTable_action: "Aktion",
    dashboard_courseTable_viewAllCourses_button_text: "Alle anzeigen",
    dashboard_courseTable_viewCourse_button_text: "ANSCHAUEN",
    chapter_aboutcourse_title: "Über Kapitel",
    chapter_ChapterDocuments_Title: "Dokumente",
    courses_setup_backToCourseAdminList_button_text: "Zurück zur Kursübersicht",
    post_setup_backToPostAdminList_button_text: "Zurück zur Beitragsübersicht",
    liveEvent_setup_backToEventAdminList_button_text: "Zurück zur Live-Event-Übersicht",
    category_setup_backToCategoryAdminList_button_text: "Zurück zur Kategorienübersicht",
    user_setup_backToUserAdminList_button_text: "Zurück zur Benutzerübersicht",
    settings_backToAdminSettings_button_text: "Zurück zur Einstellungenübersicht",
    navigation_language_tooltip: "Sprachen",
    navigation_mode_tooltip: "Modus",
    navigation_administration_tooltip: "Administration",
    navigation_profile_tooltip: "Profil",
    privacy_policy_link: "Datenschutzerklärung",
    privacy_termsOfService_link: "Nutzungsbedingungen",
    chapter_attachments_NoDocuments: "Keine Dokumente",
    nav_item_career: "Karriere",
    nav_item_calendar: "Kalender",
    nav_item_knowledgeHub: "Wissensbibliothek",
    profile_OnlineStatus_Online: "Online",
    profile_OnlineStatus_Away: "Nicht verfügbar",
    profile_OnlineStatus_DoNotDisturb: "Bitte nicht stören",
    profile_OnlineStatus_Invisible: "Unsichtbar",
    profile_OnlineStatus_Offline: "Offline",
    profile_status_text: "Status",
    profile_help: "Hilfe",
    course_chapter_author_text: "Autor -",
    live_event_filter_start_date_text: "Start Datum",
    live_event_filter_end_date_text: "End Datum",
    chapter_aboutevent_title: "Über die Veranstaltung",
    chat_server_leave: "Server verlassen",
    settings_menu_design_title: "Button Design",
    customize_customizeContainer_title: "Passen Sie Ihren Container an",
    customize_PrimaryButtonColors_title: "Passen Sie Ihre Primärfarben der Knöpfe an",
    customize_PrimaryButtonColorsDark_title: "Passen Sie Ihre Primärfarben für den Darkmode an",
    customize_PrimaryButtonColorForm_title: "Passen Sie die Primärfarbe der Buttons an",
    customize_PrimaryButtonColorForm_cancel: "Abbrechen",
    customize_PrimaryButtonColorForm_edit: "Bearbeiten",
    customize_PrimaryButtonColorForm_save: "Speichern",
    customize_DarkPrimaryButtonColorForm_title: "Passen Sie die Primärfarbe der Buttons für den Darkmode an",
    dashboard_popularChapter_chapterName_text: "Kapitelname",
    dashboard_popularChapter_courseName_text: "Kursname",
    dashboard_popularChapter_likes_text: "Likes",
    dashboard_popularChapter_comments_text: "Kommentare",
    dashboard_popularChapter_action_text: "Aktion",
    categories_ColorForm_title: "Kategoriefarbe",
    profile_MemberIdForm_title: "Mitglieds-ID",
    profile_MemberIdForm_cancel: "Abbrechen",
    profile_MemberIdForm_edit: "Bearbeiten",
    profile_MemberIdForm_placeholder: "111",
    profile_MemberIdForm_save: "Speichern",
    post_scheduleDateForm_title: "Datum & Uhrzeit planen",
    post_scheduleDateForm_cancel: "Abbrechen",
    post_scheduleDateForm_edit: "Datum bearbeiten",
    post_scheduleDateForm_save: "Speichern",
    liveEvent_TitleForm_title: "Veranstaltungstitel",
    liveEvent_TitleForm_cancel: "Abbrechen",
    liveEvent_TitleForm_edit: "Titel bearbeiten",
    liveEvent_TitleForm_save: "Speichern",
    liveEvent_DescriptionForm_title: "Veranstaltungsbeschreibung",
    liveEvent_DescriptionForm_cancel: "Abbrechen",
    liveEvent_DescriptionForm_edit: "Beschreibung bearbeiten",
    liveEvent_DescriptionForm_save: "Speichern",
    liveEvent_CategoryForm_title: "Veranstaltungskategorie",
    liveEvent_CategoryForm_cancel: "Abbrechen",
    liveEvent_CategoryForm_edit: "Kategorie bearbeiten",
    liveEvent_CategoryForm_save: "Speichern",
    liveEvent_startDateTimeForm_title: "Startdatum & -uhrzeit",
    liveEvent_startDateTimeForm_cancel: "Abbrechen",
    liveEvent_startDateTimeForm_edit: "Datum bearbeiten",
    liveEvent_startDateTimeForm_save: "Speichern",
    liveEvent_endDateTimeForm_title: "Enddatum & -uhrzeit",
    liveEvent_endDateTimeForm_cancel: "Abbrechen",
    liveEvent_endDateTimeForm_edit: "Datum bearbeiten",
    liveEvent_endDateTimeForm_save: "Speichern",
    liveEvent_ImageForm_title: "Veranstaltungsvorschaubild",
    liveEvent_ImageForm_add: "Bild hinzufügen",
    liveEvent_ImageForm_edit: "Bild bearbeiten",
    liveEvent_ImageForm_description: "16:9 Seitenverhältnis empfohlen",
    liveEvent_videoForm_title: "Live-Veranstaltung",
    liveEvent_videoForm_cancel: "Abbrechen",
    liveEvent_videoForm_edit: "Video bearbeiten",
    liveEvent_videoForm_add: "Video hinzufügen",
    liveEvent_videoForm_save: "Speichern",
    liveEvent_videoForm_preview: "Seite aktualisieren, wenn das Video nicht angezeigt wird.",
    dashboard_popularChapter_title: "Beliebteste Kapiteln",
    sidebar_help: "Hilfe",
    sidebar_privacy_policy: "Datenschutzerklärung",
    profile_backToDashboard_button_text: "Zurück zum Dashboard",
    profile_EmailForm_title: "E-Mail",
    profile_EmailForm_cancel: "Abbrechen",
    profile_EmailForm_edit: "Bearbeiten",
    profile_EmailForm_placeholder: "z.B. 'max.mustermann@test.com'",
    profile_EmailForm_save: "Speichern",
    profile_ImageForm_title: "Profilbild",
    profile_ImageForm_cancel: "Abbrechen",
    profile_ImageForm_add: "Bild hinzufügen",
    profile_ImageForm_edit: "Bild bearbeiten",
    profile_ImageForm_help: "1:1 Seitenverhältnis empfohlen",
    course_durationForm_title: "Kursdauer",
    courses_durationForm_cancel: "Abbrechen",
    courses_durationForm_edit: "Bearbeiten",
    course_durationForm_hours: "Stunden",
    courses_durationForm_placeholder: "z.B. '2'",
    courses_durationForm_save: "Speichern",
    courses_levelForm_title: "Kursniveau",
    courses_levelForm_cancel: "Abbrechen",
    courses_levelForm_edit: "Bearbeiten",
    courses_levelForm_noLevel: "Kein Niveau",
    courses_levelForm_save: "Speichern",
    course_SpecialTypeForm_title: "Besonderer Status",
    course_SpecialTypeForm_isNew: "Neu",
    course_SpecialTypeForm_isFeatured: "Hervorgehoben",
    course_SpecialTypeForm_isBestseller: "Bestseller",
    course_SpecialTypeForm_save: "Speichern",
    course_card_chapter: "Kapitel",
    course_card_chapters: "Kapitel",
    course_card_hour: "Stunde",
    course_card_hours: "Stunden",
    course_card_no_level: "Kein Level",
    course_card_bestseller: "Bestseller",
    course_card_new: "Neu",
    course_card_featured: "Hervorgehoben",
    course_card_edit: "Bearbeiten",
    course_card_delete: "Löschen",
    descriptionModal_DialogHeader: "Beschreibung",
    descriptionModal_DialogCancel: "Schließen",
    courses_sidebar_infoDescription: "Kursbeschreibung",
    news_myFavorites_title: "Meine Favoriten",
    news_Posts_title: "Beiträge",
    news_LiveEvents_title: "Live-Veranstaltungen",
    news_Courses_title: "Kurse",
    news_Chapters_title: "Kapitel",
    chapter_purchaseBanner_text: "Sie müssen diesen Kurs kaufen, um dieses Kapitel anzusehen.",
    chat_modal_deleteMessage_title: "Nachricht löschen",
    chat_modal_deleteMessage_description1: "Sind Sie sicher, dass Sie das tun möchten?",
    chat_modal_deleteMessage_description2: "Die Nachricht wird dauerhaft gelöscht.",
    chat_modal_deleteMessage_cancel: "Abbrechen",
    chat_modal_deleteMessage_confirm: "Bestätigen",
    liveEvent_chat_title: "Stream-Chat",
    liveEvent_chat_inputField: "Geben Sie Ihren Kommentar ein",
    liveEvent_start: "Beginnt",
    liveEvent_end: "Endet",
    course_enrollButton_free: "Kostenlos anmelden",
    course_enrollButton: "Anmelden für",
    course_progressButton_NotComplete: "Nicht abgeschlossen",
    course_progressButton_MarkComplete: "Kapitel abschliessen",
    createContainer_title: "Benenne deinen Container",
    createCotainer_description: "Wie heißt der Container oder Kunde, den du verwenden wirst?",
    createContainer_form_label: "Container-Name",
    createContainer_form_placeholder: "z.B. 'Kunde XYZ'",
    createContainer_form_description: "Was wirst du in diesem Container lehren?",
    createContainer_cancel: "Abbrechen",
    createContainer_submit: "Erstellen",
    dashboard_doughnutChart_title: "Kursstatistiken",
    liveEvent_eventMdal_title: "Möchten Sie dieses Event beenden?",
    liveEvent_eventMdal_no: "Nein",
    liveEvent_eventMdal_yes: "Ja",
    dashboard_doughnut_completed: "Abgeschlossen",
    dashboard_doughnut_inprogress: "In Bearbeitung",
    dashboard_doughnut_notStarted: "Nicht begonnen",
    dashboard_courseTable_viewFavoriteChapters_button_text: "Meine Favoriten",
    courses_list_backToCourses_button_text:"Zurück zu den Kursen",
    dashboard_courseTable_viewMyFavourties_button_text: "Meine Favoriten",
    dashboard_eventTable_viewFavoriteEvents_button_text: "Meine Event Favoriten",
    live_event_futureAndPast_button_text_all: "Alle",
    no_events_found: "Keine Events gefunden",
    courses_list_backToLiveEvents_button_text: "Zurück zu Live-Events",
    goBack_button_text: "Zurück",
    profile_oldPassword_placeholder: "aktuelles Passwort",
    profile_newPasswordForm_title: "Passwort",
    profile_newPasswordForm_cancel: "Abbrechen",
    profile_newPasswordForm_edit: "Bearbeiten",
    profile_newPasswordForm_placeholder: "neues Passwort",
    profile_confirmPasswordForm_placeholder: "neues Passwort bestätigen",
    profile_newPasswordForm_save: "Speichern",
    modal_share_link_title: "Teilen",
    modal_share_link_label: "Link teilen",
    profile_manageBilling: "Abrechnung",
    settings_menu_themedesign_title: "Theme Design",
    customize_customizeTheme_title: "Passe deine Themenfarbe an",
    customize_ThemeColors_title: "Passe deine Themenfarbe an",
    customize_ThemeColorForm_title: "Themenfarbe",
    customize_ThemeColorForm_cancel: "Abbrechen",
    customize_ThemeColorForm_edit: "Bearbeiten",
    customize_THemeColorForm_save: "Speichern",
    customize_ThemeColorsDark_title: "Passe deine Themenfarbe für den Dunkelmodus an",
    customize_DarkThemeColorForm_title: "Themenfarbe für Dunkelmodus",
    customize_ThemeColorForm_save: "Speichern",
    settings_menu_authenticationdesign_title: "Authentifizierungs Design",
    customize_authDesignSettings_title: "Passen Sie Ihre Authentifizierungsseiten an",
    customize_authDesignSettings_signUp_title: "Bild für Ihre Registrierungsseite hinzufügen",
    customize_authDesignSettings_signIn_title: "Bild für Ihre Anmeldeseite hinzufügen",
    customize_authDesignSettings_forgetPassword_title: "Bild für Ihre Passwort-vergessen-Seite hinzufügen",
    customize_SignUpImageForm_title: "Registrierungsbild",
    customize_SignUpImageForm_cancel: "Abbrechen",
    customize_SignUpImageForm_addImage: "Bild hinzufügen",
    customize_SignUpImageForm_edit: "Bearbeiten",
    customize_SignUpImageForm_imageHint: "16:9 Seitenverhältnis empfohlen",
    customize_darkSignUpImageForm_title: "Registrierungsbild für Dunkelmodus",
    customize_darkSignUpImageForm_cancel: "Abbrechen",
    customize_darkSignUpImageForm_addImage: "Bild hinzufügen",
    customize_darkSignUpImageForm_edit: "Bearbeiten",
    customize_darkSignUpImageForm_imageHint: "16:9 Seitenverhältnis empfohlen",
    customize_SignInImageForm_title: "Anmeldebild",
    customize_SignInImageForm_cancel: "Abbrechen",
    customize_SignInImageForm_addImage: "Bild hinzufügen",
    customize_SignInImageForm_edit: "Bearbeiten",
    customize_SignInImageForm_imageHint: "16:9 Seitenverhältnis empfohlen",
    customize_darkSignInImageForm_title: "Anmeldebild für Dunkelmodus",
    customize_darkSignInImageForm_cancel: "Abbrechen",
    customize_darkSignInImageForm_addImage: "Bild hinzufügen",
    customize_darkSignInImageForm_edit: "Bearbeiten",
    customize_darkSignInImageForm_imageHint: "16:9 Seitenverhältnis empfohlen",
    customize_ForgePasswordImageForm_title: "Passwort-vergessen-Bild",
    customize_ForgePasswordImageForm_cancel: "Abbrechen",
    customize_ForgePasswordImageForm_addImage: "Bild hinzufügen",
    customize_ForgePasswordImageForm_edit: "Bearbeiten",
    customize_ForgePasswordImageForm_imageHint: "16:9 Seitenverhältnis empfohlen",
    customize_darkForgePasswordImageForm_title: "Passwort-vergessen-Bild für Dunkelmodus",
    customize_darkForgePasswordImageForm_cancel: "Abbrechen",
    customize_darkForgePasswordImageForm_addImage: "Bild hinzufügen",
    customize_darkForgePasswordImageForm_edit: "Bearbeiten",
    customize_darkForgePasswordImageForm_imageHint: "16:9 Seitenverhältnis empfohlen",
    categories_TextColorForm_title: "Kategorietextfarbe",
    categories_TextColorForm_save: "Speichern",
    categories_DarkTextColorForm_title: "Kategorietextfarbe für Dunkelmodus",
    categories_DarkTextColorForm_save: "Speichern",
    liveEvent_isStreamChatForm_title: "Stream-Chat",
    liveEvent_isStreamChatForm_isStreamChat: "Stream-Chat aktivieren",
    liveEvent_isStreamChatForm_save: "Speichern",
    usergroups_search_placeholder_text: "Suchen",
    usergroups_createUsergroup_button_text: "Benutzergruppe erstellen",
    usergroups_noUsergroups_text: "Keine Benutzergruppen",
    usergroup_unpublish_banner: "Diese Benutzergruppe ist nicht veröffentlicht. Sie wird nicht wie vorgesehen funktionieren.",
    usergroup_setup_title: "Benutzergruppe einrichten",
    usergroup_setup_undertitle: "Alle erforderlichen Felder ausfüllen",
    usergroup_TitleForm_title: "Benutzergruppenname",
    usergroup_TitleForm_cancel: "Abbrechen",
    usergroup_TitleForm_edit: "Bearbeiten",
    usergroup_TitleForm_placeholder: "Expertengruppe",
    usergroup_TitleForm_save: "Speichern",
    nav_admin_item_usergroups: "Benutzergruppen",
    createUsergroup_title: "Benennen Sie Ihre Benutzergruppe",
    createUsergroup_description: "Wie möchten Sie Ihre Benutzergruppe benennen? Keine Sorge, Sie können dies später ändern.",
    createUsergroup_form_label: "Benutzergruppenname",
    createUsergroup_form_placeholder: "Test-Benutzergruppe",
    createUsergroup_form_description: "Wofür wird eine spezifische Benutzergruppe eingerichtet?",
    createUsergroup_cancel: "Abbrechen",
    createUsergroup_submit: "Speichern",
    profile_UsergroupForm_title: "Benutzergruppe",
    profile_UsergroupForm_cancel: "Abbrechen",
    profile_UsergroupForm_edit: "Benutzergruppe bearbeiten",
    profile_UsergroupForm_allUsers: "Alle Benutzer",
    profile_UsergroupForm_save: "Speichern",
    post_UsergroupForm_title: "Benutzergruppe",
    post_UsergroupForm_cancel: "Abbrechen",
    post_UsergroupForm_edit: "Benutzergruppe bearbeiten",
    post_UsergroupForm_allUsers: "Alle Benutzer",
    post_UsergroupForm_noUsergroup: "Keine Benutzergruppe",
    post_UsergroupForm_save: "Speichern",
    liveEvent_UsergroupForm_title: "Benutzergruppe",
    liveEvent_UsergroupForm_cancel: "Abbrechen",
    liveEvent_UsergroupForm_edit: "Benutzergruppe bearbeiten",
    liveEvent_UsergroupForm_allUsers: "Alle Benutzer",
    liveEvent_UsergroupForm_save: "Speichern",
    courses_UsergroupForm_title: "Benutzergruppe",
    courses_UsergroupForm_cancel: "Abbrechen",
    courses_UsergroupForm_edit: "Benutzergruppe bearbeiten",
    courses_UsergroupForm_allUsers: "Alle Benutzer",
    courses_UsergroupForm_save: "Speichern",
    course_counter_courses: "Kurse",
    course_counter_outOf: "von",
    usergroup_setup_customize_title: "Benenne deine Benutzergruppe",
    usergroup_setup_members_title: "Mitglieder hinzufügen",
    userList_table_header_name: "Name",
    userList_table_header_email: "E-Mail",
    userList_table_header_membership: "Mitgliedschaft",
    userlist_table_body_isMember: "Mitglied",
    userlist_table_body_notMember: "Kein Mitglied",
    userList_pagination_showing: "Zeigt",
    userList_pagination_to: "bis",
    userList_pagination_of: "von",
    userList_pagination_users: "Benutzer",
    userList_pagination_previous: "Zurück",
    userList_pagination_next: "Weiter",
    userList_search_placeholder: "Benutzer suchen...",
    chapters_durationForm_title: "Kapitel Dauer",
    chapters_durationForm_cancel: "Abbrechen",
    chapters_durationForm_edit: "Bearbeiten",
    chapters_durationForm_placeholder: "z. B. '2'",
    chapters_durationForm_save: "Speichern",
    chapters_levelForm_title: "Kapitel Niveau",
    chapters_levelForm_cancel: "Abbrechen",
    chapters_levelForm_edit: "Bearbeiten",
    chapters_levelForm_noLevel: "Kein Niveau",
    chapters_levelForm_save: "Speichern",
    user_DeleteProfileForm_title: "Profil Löschen",
    settings_widgetButton_configure: "Konfigurieren",
    categories_ColorForm_ColorLabel: "Farbe",
    categories_ColorForm_ColorFormDescription: "Wählen Sie eine Farbe oder geben Sie einen Hex-Code ein",
    categories_TextColorForm_ColorLabel: "Textfarbe",
    categories_TextColorForm_ColorFormDescription: "Wählen Sie eine Farbe oder geben Sie einen Hex-Code ein",
    categories_DarkTextColorForm_ColorLabel: "Textfarbe für den Dunkelmodus",
    categories_DarkTextColorForm_ColorFormDescription: "Wählen Sie eine Farbe oder geben Sie einen Hex-Code ein",
    post_CategoryTypeForm_isCourseCategory_Description: "Stellen Sie diese Kategorie ein, um sie für Kurse zu verwenden",
    post_CategoryTypeForm_isNewsCategory_Description: "Stellen Sie diese Kategorie ein, um sie für Nachrichten zu verwenden",
    post_CategoryTypeForm_isLiveEventCategory_Description: "Stellen Sie diese Kategorie ein, um sie für Live-Events zu verwenden",
    commonButton_cancel: "Abbrechen",
    commonButton_save: "Speichern",
    user_RoleForm_Label: "Rolle",
    user_UsergroupForm_Label: "Benutzergruppe",
    user_RoleForm_noRole: "Keine Rolle zugewiesen",
    user_isBannedForm_Label: "Sperrstatus des Benutzers",
    customize_PrimaryButtonColorForm_ColorLabel: "Primärknopffarbe",
    customize_DarkPrimaryButtonColorForm_ColorLabel: "Primärknopffarbe für den Dunkelmodus",
    customize_navPrimaryColorForm_ColorLabel: "Primärfarbe der Navigation",
    customize_navBackgroundColorForm_ColorLabel: "Hintergrundfarbe der Navigation",
    customize_navDarkPrimaryColorForm_ColorLabel: "Primärfarbe der Navigation für den Dunkelmodus",
    customize_navDarkBackgroundColorForm_ColorLabel: "Hintergrundfarbe der Navigation für den Dunkelmodus",
    customize_ThemeColorForm_ColorLabel: "Designfarbe",
    customize_DarkThemeColorForm_ColorLabel: "Dunkle Designfarbe",
    user_DeleteProfileForm_AlerTitle: "Warnung",
    user_DeleteProfileForm_AlerDescription: "Das Löschen Ihres Profils ist endgültig und kann nicht rückgängig gemacht werden. Alle Ihre Daten werden gelöscht.",
    user_DeleteProfileForm_ConfirmModalTitle: "Bist du sicher?",
    user_DeleteProfileForm_ConfirmModalDescription: "Diese Aktion kann nicht rückgängig gemacht werden. Ihr Konto wird dauerhaft gelöscht und Ihre Daten werden von unseren Servern entfernt.",
    user_DeleteProfileForm_ConfirmModalDeleteProfile: "Profil löschen",
    chapters_levelForm_noAuthor: "Kein Autor",
    biliing_page_header: "Abrechnung & Abonnement",
    billing_page_enterPaymentDetails: "Zahlungsdetails eingeben",
    billing_page_payment_endswith: "endet mit",
    billing_page_payment_expires: "Läuft ab",
    biliing_page_addCard: "Klicken Sie hier, um mit dieser Karte zu bezahlen",
    biliing_page_backToPlans: "Zurück zu den Plänen",
    billing_page_Tabs_Overview: "Übersicht",
    billing_page_Tabs_Plans: "Pläne",
    billing_page_Tabs_Payment: "Zahlung",
    billing_page_Tabs_BillingHistory: "Abrechnungshistorie",
    billing_page_overview_currentPlan: "Aktueller Plan:",
    billing_page_overview_startTrialText: "Kein Plan ausgewählt – Klicken, um Ihre 14-tägige Testversion zu starten",
    billing_page_overview_changePlan: "Plan ändern",
    billing_page_overview_cancelSubscription: "Abonnement kündigen",
    billing_page_plans_monthly: "Monatlich",
    billing_page_plans_yearly: "Jährlich",
    billing_page_payment_title: "Zahlungsmethoden",
    billing_page_payment_description: "Verwalten Sie Ihre Zahlungsdetails",
    billing_page_payment_endsWith: "endet mit",
    billing_page_payment_removeCard: "Entfernen",
    billing_page_payment_noSavedPayment: "Keine gespeicherten Zahlungsmethoden.",
    billing_page_payment_AddPaymentMethod: "Zahlungsmethode hinzufügen",
    billing_page_payment_connectStripe_title: "Stripe-Konto verbinden",
    billing_page_payment_connectStripe_description: "Verbinden Sie Ihr Stripe-Konto, um Zahlungen zu erhalten",
    billing_page_payment_connectStripe_button: "Stripe-Konto verbinden",
    billing_page_billingHistory_Title: "Abrechnungshistorie",
    billing_page_billingHistory_Description: "Ihre letzten Abrechnungsaktivitäten",
    billing_page_billingHistory_TableHead_InvoiceId: "Rechnungs-ID",
    billing_page_billingHistory_TableHead_PaidAmount: "Bezahlter Betrag",
    billing_page_billingHistory_TableHead_Status: "Status",
    billing_page_billingHistory_TableHead_Date: "Datum",
    cancelSubscription_title: "Abonnement kündigen",
    cancelSubscription_description: "Durch das Absenden des Formulars wird Ihr Abonnement gekündigt. Bitte teilen Sie uns mit, warum Sie das Abonnement kündigen möchten.",
    cancelSubscription_options_tooExpensive: "Zu teuer",
    cancelSubscription_options_noLongerNeeded: "Nicht mehr benötigt",
    cancelSubscription_options_switchingCompetitor: "Wechsel zu einem Mitbewerber",
    cancelSubscription_options_otherReason: "Anderer Grund",
    cancelSubscription_label_pleaseSpecifiy: "Bitte geben Sie an:",
    cancelSubscription_cancel: "Schließen",
    cancelSubscription_submitting: "Abonnement wird gekündigt",
    cancelSubscription_submit: "Abonnement kündigen",
    dashboard_notificationBanner_verifyEmail_1: "Bitte bestätigen Sie Ihre E-Mail-Adresse",
    dashboard_notificationBanner_verifyEmail_2: "Eine E-Mail wurde an ",
    dashboard_notificationBanner_verifyEmail_3: "gesendet. Bitte prüfen Sie Ihre E-Mail Inbox und Spam-Ordner.",
    dashboard_notificationBanner_subscriptionInfo_1: "Tage in Ihrer Abonnementperiode, bitte besuchen Sie",
    dashboard_notificationBanner_subscriptionInfo_2: "Die Abrechnungsseite",
    dashboard_notificationBanner_subscriptionInfo_3: ", um Ihr Abonnement anzupassen.",
    analytics_chart_title: "Detailierte Kurs-Einnahmen",
    course_durationForm_minutes: "Minuten",
    chapters_durationForm_hoursLabel: "Stunden",
    chapters_durationForm_minutesLabel: "Minuten",
    course_attachmentForm_name: "Anhang Name",
    course_attachmentForm_file: "Anhang Datei",
    course_attachmentForm_submit: "Erstellen",
    course_attachmentForm_namePlaceholder: "Anhang Name eingeben",
    course_attachmentForm_update: "Aktualisieren",
    course_attachmentForm_changeFile: "Anhang ändern",
    level_beginner: "Beginner",
    level_intermediate: "Mittel",
    level_advanced: "Fortgeschritten",
    level_expert: "Experte",
    level_master: "Meister",
    banned: "Gesperrt",
    not_banned: "nicht gesperrt",
    courses_setup_edit_chapter: "Kapitel bearbeiten",
    data_table_title: "Titel",
    data_table_price: "Preis",
    data_table_published: "Veröffentlicht",
    data_table_createdAt: "Erstellt am",
    data_table_name: "Name",
    data_table_color: "Farbe",
    data_table_Username: "Benutzername",
    data_table_email: "Email",
    data_table_role: "Rolle",
    data_table_userIsBanned: "Benutzer gesperrt",
    data_table_edit: "Bearbeiten",
    data_table_draft: "Entwurf",
    data_table_locale: "de-DE",
    };    