export const English: Record<string, string> = {
    documents: "Documents",
    document_hub: "Document Hub",
    type: "Type",
    name: "Name",
    created_at: "Created At",
    administration: "Administration",
    create: "Create",
    create_file: "Create File",
    create_folder: "Create Folder",
    create_a_folder: "Create a Folder",
    edit_folder: "Edit Folder",
    edit_file: "Edit File",
    public: "Public",
    cancel: "Cancel",
    placeholder: "Please enter folder name",
    placeholder_file: "Please enter file name",
    edit: "Edit",
    file: "File",
    upload_file: "Upload File",
    update: "Update",
    save: "Save",
    rename: "Rename",
    are_you_sure_you_want_to_delete: "Are you sure you want to delete",
    delete: "Delete",
    add: "Add",
    a_file: "a File",
    a_folder: "a Folder",
    navigation_administration_button_text: "Administration",
    navigation_administration_button_text_exit: "Exit",
    navigation_theme_toggle_light: "Light",
    navigation_theme_toggle_dark: "Dark",
    navigation_theme_toggle_system: "System",
    navigation_language_toggle_english: "English",
    navigation_language_toggle_german: "German",
    navigation_language_toggle_french: "French",
    navigation_language_toggle_spanish: "Spanish",
    navigation_language_toggle_italian: "Italian",
    navigation_language_toggle_portuguese: "Portuguese",
    navigation_language_toggle_russian: "Russian",
    navigation_language_toggle_mandarin: "Mandarin",
    navigation_search_placeholder: "Search",
    navigation_footer_text: "Powered by",
    navigation_footer_text_product: "Product",
    search_courseCounter_currentCourses: "Current existing Courses",
    news_no_posts_found: "No Posts found",
    news_comments_button_label: "Comments",
    news_comments_input_placeholder: "Type your comment...",
    news_comments_showmore_label: "Show More +",
    news_comments_reply_button_label: "Reply",
    live_event_futureAndPast_button_text_future: "Upcoming",
    live_event_futureAndPast_button_text_past: "Past",
    live_event_filter_button_text: "Filter",
    live_event_filter_title: "Live Event Filter",
    live_event_filter_description: "You can Filter Events by giving  the Start and/or the Enddate of an Event.",
    live_event_filter_applyFilter_button_text: "Apply Filter",
    live_event_filter_clearFilter_button_text: "Clear Filter",
    courses_createCourse_button_text: "Create Course",
    courses_noCourses_text: "No courses found",
    adminTable_previous_button_text: "Previous",
    adminTable_next_button_text: "Next",
    courses_searchCourses_placeholder: "Filter Courses...",
    actions_unpublish: "Unpublish",
    actions_publish: "Publish",
    courses_titleForm_title: "Course Title",
    courses_titleForm_cancel: "Cancel",
    courses_titleForm_edit: "Edit Title",
    courses_titleForm_placeholder: "e.g. 'Advanced web development'",
    courses_titleForm_save: "Save",
    courses_descriptionForm_title: "Course Description",
    courses_descriptionForm_cancel: "Cancel",
    courses_descriptionForm_edit: "Edit Description",
    courses_descriptionForm_empty: "No Description",
    courses_descriptionForm_placeholder: "e.g. 'This course is about...'",
    courses_descriptionForm_save: "Save",
    course_imageForm_title: "Course Image",
    courses_imageForm_cancel: "Cancel",
    courses_imageForm_add: "Add an Image",
    courses_imageForm_edit: "Edit Iamge",
    courses_imageForm_aspectRatioRecoomendation: "16:9 aspect ratio recommended",
    courses_categoryForm_title: "Course Category",
    courses_categoryForm_cancel: "Cancel",
    courses_categoryForm_edit: "Edit Category",
    courses_categoryForm_noCategory: "No Category",
    courses_categoryForm_save: "Save",
    courses_chaptersForm_title: "Chapter Chapters",
    courses_chaptersForm_cancel: "Cancel",
    courses_chaptersForm_addChapter: "Add a Chapter",
    courses_chaptersForm_placeholder: "e.g. 'Introduction to the course'",
    courses_chaptersForm_save: "Create",
    courses_chaptersForm_noChapters: "No Chapters",
    courses_chaptersForm_reorderInstructions: "Drag and drop to reorder the chapters",
    course_priceForm_title: "Course Price",
    courses_priceForm_cancel: "Cancel",
    courses_priceForm_edit: "Edit Price",
    courses_priceForm_noPrice: "No Price",
    courses_priceForm_placeholder: "Set a price for your course",
    courses_priceForm_save: "Save",
    course_attachmentForm_title: "Chapter Attachments",
    course_attachmentForm_cancel: "Cancel",
    course_attachmentForm_add: "Add a File",
    course_attachmentForm_noAttachments: "No Attachment yet",
    course_attachmentForm_Recoomendation: "Add anything your students might need to complete the course.",
    confirmModal_DialogHeader: "Are you sure ?",
    confirmModal_DialogDescription: "This action cannot be undone.",
    confirmModal_DialogConfirm: "Confirm",
    confirmModal_DialogCancel: "Cancel",
    chapter_TitleForm_title: "Chapter Title",
    chapter_TitleForm_cancel: "Cancel",
    chapter_TitleForm_edit: "Edit Title",
    chapter_TitleForm_save: "Save",
    chapter_TitleForm_placeholder: "e.g. 'Introduction to the course'",
    chapter_chapterDescriptionForm_title: "Chapter Description",
    chapter_chapterDescriptionForm_cancel: "Cancel",
    chapter_chapterDescriptionForm_edit: "Edit Description",
    chapter_chapterDescriptionForm_noDescription: "No Description",
    chapter_chapterDescriptionForm_save: "Save",
    chapter_accessForm_title: "Chapter Access",
    chapter_accessForm_cancel: "Cancel",
    chapter_accessForm_edit: "Edit Access",
    chapter_accessForm_isFree: "This chapter is free.",
    chapter_accessForm_isNotFree: "This chapter is not free.",
    chapter_accessForm_description: "Check this box if you want to make this chapter free.",
    chapter_accessForm_save: "Save",
    chapter_actions_unpublish: "Unpublish",
    chapter_actions_publish: "Publish",
    chapter_VideoForm_title: "Chapter Video",
    chapter_VideoForm_cancel: "Cancel",
    chapter_VideoForm_edit: "Edit Video",
    chapter_VideoForm_addVideo: "Add a Video",
    chapter_VideoForm_placeholder: "Vimeo share Link",
    chapter_VideoForm_urlWarning: "Refresh the page if video does not appear.",
    post_createPost_button_text: "Create Post",
    post_noPosts_text: "No Posts found.",
    post_search_placeholder_text: "Filter Posts...",
    posts_actions_unpublish: "Unpublish",
    posts_actions_publish: "Publish",
    post_TitleForm_title: "Post Title",
    post_TitleForm_cancel: "Cancel",
    post_TitleForm_edit: "Edit Title",
    post_TitleForm_placeholder: "e.g. 'Advanced web development'",
    post_TitleForm_save: "Save",
    post_DescriptionForm_title: "Post Description",
    post_DescriptionForm_cancel: "Cancel",
    post_DescriptionForm_edit: "Edit Description",
    post_DescriptionForm_noDescription: "No Description",
    post_DescriptionForm_save: "Save",
    post_CategoryForm_title: "Post category",
    post_CategoryForm_cancel: "Cancel",
    post_CategoryForm_edit: "Edit category",
    post_CategoryForm_noCategory: "No Category",
    post_CategoryForm_save: "Save",
    post_ImageForm_title: "Post image",
    post_ImageForm_cancel: "Cancel",
    post_ImageForm_add: "Add Image",
    post_ImageForm_edit: "Edit Image",
    post_ImageForm_help: "16:9 aspect ratio recommended",
    categories_search_placeholder_text: "Filter categories...",
    categories_createCategory_button_text: "Create Category",
    categories_noCategories_text: "No Results.",
    categories_TitleForm_title: "Category Name",
    categories_TitleForm_cancel: "Cancel",
    categories_TitleForm_edit: "Edit Name",
    categories_TitleForm_placeholder: "e.g. 'Advanced web development'",
    categories_TitleForm_save: "Save",
    category_ColorForm_title: "Category Color",
    categories_ColorForm_cancel: "Cancel",
    categories_ColorForm_edit: "Edit",
    categories_ColorForm_save: "Save",
    post_CategoryTypeForm_title: "Category Type",
    post_CategoryTypeForm_isCourseCategory: "Course Category",
    post_CategoryTypeForm_isNewsCategory: "News Category",
    post_CategoryTypeForm_isLiveEventCategory: "Live Event Category",
    post_CategoryTypeForm_save: "Save",
    customize_ContainerLinkForm_title: "Container Link",
    customize_ContainerLinkForm_cancel: "Cancel",
    customize_ContainerLinkForm_edit: "Edit Title",
    customize_ContainerLinkForm_placeholder: "e.g. 'Advanced web development'",
    customize_ContainerLinkForm_save: "Save",
    customize_ImageForm_title: "Container Image",
    customize_ImageForm_cancel: "Cancel",
    customize_ImageForm_addImage: "Add an Image",
    customize_ImageForm_edit: "Edit Image",
    customize_ImageForm_imageHint: "16:9 aspect ratio recommended",
    customize_PrimaryColorForm_cancel: "Cancel",
    customize_PrimaryColorForm_edit: "Edit",
    customize_PrimaryColorForm_save: "Save",
    users_search_placeholder_text: "Filter profiles...",
    users_noUsers_text: "No Users.",
    user_TitleForm_title: "Username",
    user_MailForm_title: "User E-Mail",
    user_RoleForm_title: "Profile Role",
    user_RoleForm_cancel: "Cancel",
    user_RoleForm_edit: "Edit Role",
    user_RoleForm_save: "Save",
    chat_ChatMessages_loading: "Loading messages...",
    chat_ChatMessages_error: "currentLanguage.toast_error!",
    chat_ChatMessages_loadPreviousMessages: "Load previous messages",
    chat_ChatItem_viewPDF: "PDF File",
    chat_ChatItem_edited: "(edited)",
    chat_ChatItem_editMessage: "edited Message",
    chat_ChatItem_saveChanges: "Save",
    chat_ChatItem_editMessageHint: "Press escape to cancel, enter to save",
    chat_ChatInput_placeholder: "Message",
    chat_initialModal_title: "Create your Server",
    chat_initialModal_description: "Give your server a personality with a name and an image. You can always change it later.",
    chat_initialModal_serverName: "Server Name",
    chat_initialModal_serverName_placeholder: "Enter Server Name",
    chat_initialModal_createServer: "Create",
    chat_serverSection_createChannel: "Create Channel",
    chat_serverSection_manageMembers: "Manage Members",
    chat_server_search_placeholder: "Search",
    chat_server_search_notFound: "No Results Found",
    chat_server_invite: "Invite People",
    chat_server_edit: "Edit Server",
    chat_server_manage_members: "Manage Members",
    chat_server_create_channel: "Create Channel",
    chat_server_delete: "Delete Server",
    chat_server_addServer: "Add a Server",
    chat_channel_edit: "Edit",
    chat_channel_delete: "Delete",
    chat_chatItem_edit: "Edit",
    chat_chatItem_delete: "Delete",
    chat_socket_reconnecting: "Fallback: Polling every 1s",
    chat_socket_connected: "Live",
    chat_modal_create_server_title: "Customize your Server",
    chat_modal_create_server_description: "Give your server a personality with a name and an image. You can always change it later.",
    chat_modal_create_server_name: "Server name",
    chat_modal_create_server_name_placeholder: "Enter server name",
    chat_modal_create_server_create: "Create",
    chat_modal_create_channel_title: "Create Channel",
    chat_modal_create_channel_name: "Channel name",
    chat_modal_create_channel_name_placeholder: "Enter channel name",
    chat_modal_create_channelType_name: "Channel Type",
    chat_modal_create_channelType_placeholder: "Select a channel type",
    chat_modal_create_channel_create: "Create",
    chat_modal_invite_title: "Invite Friends",
    chat_modal_invite_link_label: "Server invite link",
    chat_modal_invite_new: "Generate a new link",
    chat_modal_manageMembers_title: "Manage Members",
    chat_modal_manageMembers_description: "Members",
    chat_modal_manageMembers_role_label: "Role",
    chat_modal_manageMembers_role_guest: "Guest",
    chat_modal_manageMembers_role_moderator: "Moderator",
    chat_modal_manageMembers_kick: "Kick",
    chat_modal_delete_server_title: "Delete Server",
    chat_modal_delete_server_description_1: "Are you sure you want to do this?",
    chat_modal_delete_server_description_2: "will be permanently deleted.",
    chat_modal_delete_server_cancel_button: "Cancel",
    chat_modal_delete_server_delete_button: "Confirm",
    chat_modal_edit_channel_title: "Edit Channel",
    chat_modal_edit_channel_name: "Channel Name",
    chat_modal_edit_channel_name_placeholder: "Enter channel name",
    chat_modal_edit_channel_type: "Channel Type",
    chat_modal_edit_channel_save: "Save",
    chat_modal_edit_channel_type_placeholder: "Select a channel type",
    chat_modal_deleteChannel_title: "Delete Channel",
    chat_modal_deleteChannel_description_1: "Are you sure you want to do this?",
    chat_modal_deleteChannel_description_2: "will be permanently deleted.",
    chat_modal_deleteChannel_cancel_button: "Cancel",
    chat_modal_deleteChannel_delete_button: "Confirm",
    chat_modal_leaveServer_title: "Leave Server",
    chat_modal_leaveServer_description_1: "Are you sure you want to leave",
    chat_modal_leaveServer_cancel: "Cancel",
    chat_modal_leaveServer_leave: "Confirm",
    chat_modal_messageFile_title: "Add an attachment",
    chat_modal_messageFile_description: "Send a file as a message",
    chat_modal_messageFile_submit: "Send",
    createCourse_title: "Name your Course",
    createCourse_description: "What would you like to name your course? Don't worry, you can change this later.",
    createCourse_form_label: "Course title",
    createCourse_form_description: "What will you teach in this course?",
    createCourse_form_placeholder: "e.g. 'Advanced web development'",
    createCourse_cancel: "Cancel",
    createCourse_submit: "Continue",
    createPost_title: "Name your Post",
    createPost_description: "What would you like to name your Post? Don't worry, you can change this later.",
    createPost_form_label: "Post title",
    createPost_form_placeholder: "e.g. 'Advanced web development'",
    createPost_form_description: "What will you want to let you know your Community?",
    createPost_cancel: "Cancel",
    createPost_submit: "Continue",
    createLiveEvent_title: "Name your Live Event",
    createLiveEvent_description: "What would you like to name your Live Event? Don't worry, you can change this later.",
    createLiveEvent_form_label: "Event title",
    createLiveEvent_form_placeholder: "e.g. 'Advanced web development'",
    createLiveEvent_form_description: "What will you show on your Event?",
    createLiveEvent_cancel: "Cancel",
    createLiveEvent_submit: "Continue",
    createCategory_title: "Name your Category",
    createCategory_description: "What would you like to name your Category? Don’t worry, you can change this later.",
    createCategory_form_label: "Category Name",
    createCategory_form_placeholder: "e.g. 'Advanced web development'",
    createCategory_form_description: "What will you categorize on your platform?",
    createCategory_cancel: "Cancel",
    createCategory_submit: "Save",
    liveEvent_createEvent_button_text: "Create Live Event",
    liveEvent_noEvent_text: "No Events found.",
    liveEvent_filterEvents_placeholder: "Filter Events...",
    infocard_courses: "Courses",
    infocard_course: "Course",
    infocard_inprogress: "In Progress",
    infocard_completed: "Completed",
    no_courses: "No Courses found",
    customize_customizeCcontainer_title: "Customize your Container",
    customize_customizeCcontainer_requiredFields: "Complete all required fields",
    customize_customizeYourContainer: "Customize your Container",
    requiredFields: "*required",
    customize_AddImageTitle: "Add an Image as an Logo",
    chat_welcome_title: "Welcome to #",
    chat_welcome_description: "This is the start of the #",
    chat_welcome_description2: "channel",
    chat_welcome_title_directMessage: "This is the start of your conversation with",
    serverSidebar_textChannel: "Text Channels",
    serverSidebar_videoChannel: "Video Channels",
    serverSidebar_audioChannel: "Audio Channels",
    serverSidebar_member: "Members",
    chat_serversection_label_text: "Text Channels",
    chat_serversection_label_audio: "Audio Channels",
    chat_serversection_label_video: "Video Channels",
    chat_serversection_label_member: "Members",
    chat_server_search_command_placeholder: "Search all channels and members",
    course_setup_title: "Course Setup",
    course_setup_undertitle: "Complete all required fields",
    course_setup_course_information_title: "Customize your course",
    course_setup_price_title: "Sell your Course",
    course_setup_chapters_title: "Course Chapters",
    course_setup_attachments_title: "Resources & Attachments",
    courses_chapter_backToCourse_button_text: "Back to Course Setup",
    courses_chapter_title: "Chapter Creation",
    courses_chapter_undertitle: "Complete all fields",
    course_chapter_customize_title: "Customize your Chapter",
    course_chapter_access: "Access Settings",
    course_chapter_video: "Add a Video",
    courses_setup_free_badge: "Free",
    courses_setup_published_text: "Published",
    courses_setup_draft_text: "Draft",
    post_setup_title: "Post Setup",
    post_setup_undertitle: "Complete all required fields",
    post_setup_customize_title: "Customize your Post",
    post_setup_image_title: "Add an Image to your Post",
    liveEvent_PremiumFeature_description: "To use Live-Events and set up your digital and hybrid Events with our software, you need to use the community package.",
    liveEvent_PremiumFeature_button_text: "Buy Community Package",
    liveEvent_setup_title: "Event Setup",
    liveEvent_setup_undertitle: "Complete all required fields",
    liveEvent_setup_customize_title: "Customize your Live Event",
    liveEvent_setup_video_title: "Add the Resources to your Event",
    category_setup_title: "Category Setup",
    category_setup_undertitle: "Complete all required fields",
    category_setup_customize_title: "Name your Category",
    user_setup_title: "User Setup",
    user_setup_undertitle: "Complete all required fields",
    user_setup_customize_title: "Customize the User",
    course_unpublish_banner: "This course is unpublished. It will not be visible to the Users.",
    post_unpublish_banner: "This post is unpublished. It will not be visible to the Users.",
    liveEvent_unpublish_banner: "This event is unpublished. It will not be visible to the Users.",
    category_unpublish_banner: "This category is unpublished. It will not be visible to the Users.",
    chapter_unpublish_banner: "This chapter is unpublished. It will not be visible to the Users.",
    analytics_total_revenue_label: "Total Revenue",
    analytics_total_sales_label: "Total Sales",
    customize_NavColors_title: "Customize your Navigation Colors",
    customize_navBackgroundColorForm_title: "Navigation Background Color",
    customize_navDarkBackgroundColorForm_title: "Navigation Background Color Darkmode",
    customize_navPrimaryColorForm_title: "Navigation Primary Color",
    customize_navDarkPrimaryColorForm_title: "Navigation Primary Color Darkmode",
    customize_customizeNavigation_title: "Customize your Navigation Colors",
    customize_NavColorsDark_title: "Customize your Navigation Colors Darkmode",
    settings_menu_containersettings_title: "Container Settings",
    settings_menu_navigationdesign_title: "Navigation Design",
    settings_backToMenu_button_text: "Back to Menu",
    nav_item_browse: "Courses",
    nav_item_dashboard: "Dashboard",
    nav_item_news: "News",
    nav_item_liveEvent: "Live Event",
    nav_item_chat: "Chat",
    nav_item_documents: "Documents",
    nav_admin_item_course: "Courses",
    nav_admin_item_posts: "Posts",
    nav_admin_item_liveEvents: "Live Events",
    nav_admin_item_categories: "Categories",
    nav_admin_item_users: "Users",
    nav_admin_item_analytics: "Analytics",
    nav_admin_item_settings: "Settings",
    customize_ImageFormDark_title: "Container Image Darkmode",
    settings_Container_IconForm_title: "Container Icon",
    privacy_policy_title: "Privacy Policy & Terms and Conditions",
    privacy_policy_description: "To continue using our platform, please review and accept our Privacy Policy and Terms and Conditions. Your acceptance ensures that you read & understand how your data will be handled and agree to the rules governing our platform. We value your privacy and strive to provide a secure environment for all users.",
    privacy_policy_button: "I've read it and accept it",
    user_isBannedForm_title: "Ban Status",
    user_isBannedForm_cancel: "Cancel",
    user_isBannedForm_edit: "Edit",
    user_isBannedForm_save: "Save",
    user_setup_settings_title: "Danger Zone",
    post_setup_category_title: "Customize your Post Category",
    courses_authorForm_cancel: "Cancel",
    courses_authorForm_edit: "Edit Author",
    courses_authorForm_save: "Save",
    courses_authorForm_placeholder: "e.g. 'Max Mustermann'",
    courses_authorForm_title: "Author Name",
    courses_authorForm_empty: "empty",
    infocard_completedChapters: "Completed Chapters",
    infocard_currentOnlineUsers: "Current Online Users",
    profile_manageAccount: "Manage Account",
    profile_signOut: "Sign Out",
    profile_change_customize_username: "My Profile",
    profile_TitleForm_title: "Username",
    profile_TitleForm_cancel: "Cancel",
    profile_TitleForm_edit: "Edit",
    profile_TitleForm_placeholder: "Username123",
    profile_TitleForm_save: "Save",
    courses_list_backToDashboard_button_text: "Back to Dashboard",
    dashboard_courseTable_CourseStatus_Title: "My Courses",
    dashboard_courseTable_courseName: "Course Name",
    dashboard_courseTable_paid: "Paid",
    dashboard_courseTable_progress: "Progress",
    dashboard_courseTable_chapter: "Chapter",
    dashboard_courseTable_action: "Action",
    dashboard_courseTable_viewAllCourses_button_text: "View all",
    dashboard_courseTable_viewCourse_button_text: "VIEW",
    chapter_aboutcourse_title: "About Chapter",
    chapter_ChapterDocuments_Title: "Documents",
    courses_setup_backToCourseAdminList_button_text: "Back to Course Overview",
    post_setup_backToPostAdminList_button_text: "Back to Post Overview",
    liveEvent_setup_backToEventAdminList_button_text: "Back to Live-Event Overview",
    category_setup_backToCategoryAdminList_button_text: "Back to Category Overview",
    user_setup_backToUserAdminList_button_text: "Back to User Overview",
    settings_backToAdminSettings_button_text: "Back to Settings Overview",
    navigation_language_tooltip: "Languages",
    navigation_mode_tooltip: "Mode",
    navigation_administration_tooltip: "Administration",
    navigation_profile_tooltip: "Profile",
    privacy_policy_link: "Privacy Policy",
    privacy_termsOfService_link: "Terms of Service",
    chapter_attachments_NoDocuments: "No Documents",
    nav_item_career: "Career",
    nav_item_calendar: "Calendar",
    nav_item_knowledgeHub: "Knowledge-Hub",
    profile_OnlineStatus_Online: "Online",
    profile_OnlineStatus_Away: "Not Available",
    profile_OnlineStatus_DoNotDisturb: "Do Not Disturb",
    profile_OnlineStatus_Invisible: "Invisible",
    profile_OnlineStatus_Offline: "Offline",
    profile_status_text: "Status",
    profile_help: "Help",
    course_chapter_author_text: "Author -",
    live_event_filter_start_date_text: "Start Date",
    live_event_filter_end_date_text: "End Date",
    chapter_aboutevent_title: "About the Event",
    chat_server_leave: "Leave Server",
    settings_menu_design_title: "Button Design",
    customize_customizeContainer_title: "Customize your Container Colors",
    customize_PrimaryButtonColors_title: "Customize your Primary Button Color",
    customize_PrimaryButtonColorsDark_title: "Customize your Primary Button Color Darkmode",
    customize_PrimaryButtonColorForm_title: "Primary Button Color",
    customize_PrimaryButtonColorForm_cancel: "Cancel",
    customize_PrimaryButtonColorForm_edit: "Edit",
    customize_PrimaryButtonColorForm_save: "Save",
    customize_DarkPrimaryButtonColorForm_title: "Primary Button Color Darkmode",
    settings_menu_themedesign_title: "Theme Design",
    customize_customizeTheme_title: "Customize your Theme Color",
    customize_ThemeColors_title: "Customize your Theme Color",
    customize_ThemeColorForm_title: "Theme Color",
    customize_ThemeColorForm_cancel: "Cancel",
    customize_ThemeColorForm_edit: "Edit",
    customize_THemeColorForm_save: "Save",
    customize_ThemeColorsDark_title: "Customize your Theme Color for Darkmode",
    customize_DarkThemeColorForm_title: "Theme Color for Darkmode",
    customize_ThemeColorForm_save: "Save",
    dashboard_popularChapter_chapterName_text: "Chapter Name",
    dashboard_popularChapter_courseName_text: "Course Name",
    dashboard_popularChapter_likes_text: "Likes",
    dashboard_popularChapter_comments_text: "Comments",
    dashboard_popularChapter_action_text: "Action",
    categories_ColorForm_title: "Category Color",
    profile_MemberIdForm_title: "Member ID",
    profile_MemberIdForm_cancel: "Cancel",
    profile_MemberIdForm_edit: "Edit",
    profile_MemberIdForm_placeholder: "111",
    profile_MemberIdForm_save: "Save",
    post_scheduleDateForm_title: "Schedule Date & Time",
    post_scheduleDateForm_cancel: "Cancel",
    post_scheduleDateForm_edit: "Edit Date",
    post_scheduleDateForm_save: "Save",
    liveEvent_TitleForm_title: "Event Title",
    liveEvent_TitleForm_cancel: "Cancel",
    liveEvent_TitleForm_edit: "Edit Title",
    liveEvent_TitleForm_save: "Save",
    liveEvent_DescriptionForm_title: "Event Description",
    liveEvent_DescriptionForm_cancel: "Cancel",
    liveEvent_DescriptionForm_edit: "Edit Description",
    liveEvent_DescriptionForm_save: "Save",
    liveEvent_CategoryForm_title: "Event Category",
    liveEvent_CategoryForm_cancel: "Cancel",
    liveEvent_CategoryForm_edit: "Edit Category",
    liveEvent_CategoryForm_save: "Save",
    liveEvent_startDateTimeForm_title: "Start Date & Time",
    liveEvent_startDateTimeForm_cancel: "Cancel",
    liveEvent_startDateTimeForm_edit: "Edit Date",
    liveEvent_startDateTimeForm_save: "Save",
    liveEvent_endDateTimeForm_title: "End Date & Time",
    liveEvent_endDateTimeForm_cancel: "Cancel",
    liveEvent_endDateTimeForm_edit: "Edit Date",
    liveEvent_endDateTimeForm_save: "Save",
    liveEvent_ImageForm_title: "Event Thumbnail",
    liveEvent_ImageForm_add: "Add an Image",
    liveEvent_ImageForm_edit: "Edit Image",
    liveEvent_ImageForm_description: "16:9 aspect ratio recommended",
    liveEvent_videoForm_title: "Live Event",
    liveEvent_videoForm_cancel: "Cancel",
    liveEvent_videoForm_edit: "Edit Video",
    liveEvent_videoForm_add: "Add a Video",
    liveEvent_videoForm_save: "Save",
    liveEvent_videoForm_preview: "Refresh the page if video does not appear.",
    dashboard_popularChapter_title: "Most Popular Chapters",
    sidebar_help: "Help",
    sidebar_privacy_policy: "Privacy Policy",
    profile_backToDashboard_button_text: "Back to Dashboard",
    profile_EmailForm_title: "E-mail",
    profile_EmailForm_cancel: "Cancel",
    profile_EmailForm_edit: "Edit",
    profile_EmailForm_placeholder: "e.g. 'max.mustermann@test.com'",
    profile_EmailForm_save: "Save",
    profile_ImageForm_title: "Profile Image",
    profile_ImageForm_cancel: "Cancel",
    profile_ImageForm_add: "Add Image",
    profile_ImageForm_edit: "Edit Iamge",
    profile_ImageForm_help: "1:1 aspect ratio recommended",
    course_durationForm_title: "Course Duration",
    courses_durationForm_cancel: "Cancel",
    courses_durationForm_edit: "Edit",
    course_durationForm_hours: "Hours",
    courses_durationForm_placeholder: "e.g. '2'",
    courses_durationForm_save: "Save",
    courses_levelForm_title: "Course Level",
    courses_levelForm_cancel: "Cancel",
    courses_levelForm_edit:"Edit",
    courses_levelForm_noLevel: "No Level",
    courses_levelForm_save: "Save",
    course_SpecialTypeForm_title: "Special Status",
    course_SpecialTypeForm_isNew: "New",
    course_SpecialTypeForm_isFeatured: "Featured",
    course_SpecialTypeForm_isBestseller: "Bestseller",
    course_SpecialTypeForm_save: "Save",
    course_card_chapter: "Chapter",
    course_card_chapters: "Chapters",
    course_card_hour: "Hour",
    course_card_hours: "Hours",
    course_card_no_level: "No Level",
    course_card_bestseller: "Best Seller",
    course_card_new: "New",
    course_card_featured: "Featured",
    course_card_edit: "Edit",
    course_card_delete: "Delete",
    descriptionModal_DialogHeader: "Description",
    descriptionModal_DialogCancel: "Close",
    courses_sidebar_infoDescription: "Course Description",
    news_myFavorites_title: "My Favorites",
    news_Posts_title: "Posts",
    news_LiveEvents_title: "Live Events",
    news_Courses_title: "Courses",
    news_Chapters_title: "Chapters",
    chapter_purchaseBanner_text: "You need to purchase this course to watch this chapter.",
    chat_modal_deleteMessage_title: "Delete Message",
    chat_modal_deleteMessage_description1: "Are you sure you want to do this?",
    chat_modal_deleteMessage_description2: "The message will be permanently deleted.",
    chat_modal_deleteMessage_cancel: "Cancel",
    chat_modal_deleteMessage_confirm: "Confirm",
    liveEvent_chat_title: "Stream Chat",
    liveEvent_chat_inputField: "Type your comment",
    liveEvent_start: "Starts at",
    liveEvent_end: "Ends at",
    course_enrollButton_free: "Enroll for Free",
    course_enrollButton: "Enroll for",
    course_progressButton_NotComplete: "Not completed",
    course_progressButton_MarkComplete: "Mark as complete",
    createContainer_title: "Name your Container",
    createCotainer_description: "What is the name of the Container or Client you will be using?",
    createContainer_form_label: "Container Name",
    createContainer_form_placeholder: "e.g. 'Customer XYZ'",
    createContainer_form_description: "What will you teach in this container?",
    createContainer_cancel: "Cancel",
    createContainer_submit: "Create",
    dashboard_doughnutChart_title: "Course Statistics",
    liveEvent_eventMdal_title: "Do you want to end this session?",
    liveEvent_eventMdal_no: "No",
    liveEvent_eventMdal_yes: "Yes",
    dashboard_doughnut_completed: "Copmleted",
    dashboard_doughnut_inprogress: "Inprogress",
    dashboard_doughnut_notStarted: "Not Started",
    dashboard_courseTable_viewFavoriteChapters_button_text: "My Favourite Chapters",
    courses_list_backToCourses_button_text:"Back to Courses",
    dashboard_courseTable_viewMyFavourties_button_text: "My Favourite Courses",
    dashboard_eventTable_viewFavoriteEvents_button_text: "My Favourite Events",
    live_event_futureAndPast_button_text_all: "All",
    no_events_found:"No Events Found",
    courses_list_backToLiveEvents_button_text: "Back to Live-Events",
    goBack_button_text: "Go Back",
    profile_oldPassword_placeholder: "current Password",
    profile_newPasswordForm_title: "Password",
    profile_newPasswordForm_cancel: "Cancel",
    profile_newPasswordForm_edit: "Edit",
    profile_newPasswordForm_placeholder: "new Password",
    profile_confirmPasswordForm_placeholder: "confirm new Password",
    profile_newPasswordForm_save: "Save",
    modal_share_link_title: "Share",
    modal_share_link_label: "Share Link",
    profile_manageBilling: "Billing",
    settings_menu_authenticationdesign_title: "Authentication Design",
    customize_authDesignSettings_title: "Customize your Authentication Pages",
    customize_authDesignSettings_signUp_title: "Add an Image for your Sign Up Page",
    customize_authDesignSettings_signIn_title: "Add an Image for your Sign In Page",
    customize_authDesignSettings_forgetPassword_title: "Add an Image for your Forget Password Page",
    customize_SignUpImageForm_title: "Sign Up Image",
    customize_SignUpImageForm_cancel: "Cancel",
    customize_SignUpImageForm_addImage: "Add Iamge",
    customize_SignUpImageForm_edit: "Edit",
    customize_SignUpImageForm_imageHint: "16:9 aspect Ratio recommended",
    customize_darkSignUpImageForm_title: "Sign Up Image for Darkmode",
    customize_darkSignUpImageForm_cancel: "Cancel",
    customize_darkSignUpImageForm_addImage: "Add Iamge",
    customize_darkSignUpImageForm_edit: "Edit",
    customize_darkSignUpImageForm_imageHint: "16:9 aspect Ratio recommended",
    customize_SignInImageForm_title: "Sign In Image",
    customize_SignInImageForm_cancel: "Cancel",
    customize_SignInImageForm_addImage: "Add Iamge",
    customize_SignInImageForm_edit: "Edit",
    customize_SignInImageForm_imageHint: "16:9 aspect Ratio recommended",
    customize_darkSignInImageForm_title: "Sign In Image for Darkmode",
    customize_darkSignInImageForm_cancel: "Cancel",
    customize_darkSignInImageForm_addImage: "Add Iamge",
    customize_darkSignInImageForm_edit: "Edit",
    customize_darkSignInImageForm_imageHint: "16:9 aspect Ratio recommended",
    customize_ForgePasswordImageForm_title: "Forget Password Image",
    customize_ForgePasswordImageForm_cancel: "Cancel",
    customize_ForgePasswordImageForm_addImage: "Add Iamge",
    customize_ForgePasswordImageForm_edit: "Edit",
    customize_ForgePasswordImageForm_imageHint: "16:9 aspect Ratio recommended",
    customize_darkForgePasswordImageForm_title: "Forget Password Image for Darkmode",
    customize_darkForgePasswordImageForm_cancel: "Cancel",
    customize_darkForgePasswordImageForm_addImage: "Add Iamge",
    customize_darkForgePasswordImageForm_edit: "Edit",
    customize_darkForgePasswordImageForm_imageHint: "16:9 aspect Ratio recommended",
    categories_TextColorForm_title: "Category Text Color",
    categories_TextColorForm_save: "Save",
    categories_DarkTextColorForm_title: "Category Text Color for Darkmode",
    categories_DarkTextColorForm_save: "Save",
    liveEvent_isStreamChatForm_title: "Stream Chat",
    liveEvent_isStreamChatForm_isStreamChat: "Activate Stream Chat",
    liveEvent_isStreamChatForm_save: "Save",
    usergroups_search_placeholder_text: "Search",
    usergroups_createUsergroup_button_text: "Create Usergroup",
    usergroups_noUsergroups_text: "No Usergroups",
    usergroup_unpublish_banner: "This usergroup is unpublished. It will not working as it should.",
    usergroup_setup_title: "Usergroup Setup",
    usergroup_setup_undertitle: "Complete all requured fields",
    usergroup_TitleForm_title: "Usergroup Name",
    usergroup_TitleForm_cancel: "Cancel",
    usergroup_TitleForm_edit: "Edit",
    usergroup_TitleForm_placeholder: "Expertgroup",
    usergroup_TitleForm_save: "Save",
    nav_admin_item_usergroups: "Usergroups",
    createUsergroup_title: "Name your Usergroup",
    createUsergroup_description: "What would you like to name your Usergroup? Don’t worry, you can change this later.",
    createUsergroup_form_label: "Usergroup Name",
    createUsergroup_form_placeholder: "Test Usergroup",
    createUsergroup_form_description: "What will you set a specific Usergroup for",
    createUsergroup_cancel: "Cancel",
    createUsergroup_submit: "Save",
    profile_UsergroupForm_title: "Usergroup",
    profile_UsergroupForm_cancel: "Cancel",
    profile_UsergroupForm_edit: "Edit Usergroup",
    profile_UsergroupForm_allUsers: "All Users",
    profile_UsergroupForm_save: "Save",
    post_UsergroupForm_title: "Usergroup",
    post_UsergroupForm_cancel: "Cancel",
    post_UsergroupForm_edit: "Edit Usergroup",
    post_UsergroupForm_noUsergroup: "No Usergroup",
    post_UsergroupForm_allUsers: "All Users",
    post_UsergroupForm_save: "Save",
    liveEvent_UsergroupForm_title: "Usergroup",
    liveEvent_UsergroupForm_cancel: "Cancel",
    liveEvent_UsergroupForm_edit: "Edit Usergroup",
    liveEvent_UsergroupForm_allUsers: "All Users",
    liveEvent_UsergroupForm_save: "Save",
    courses_UsergroupForm_title: "Usergroup",
    courses_UsergroupForm_cancel: "Cancel",
    courses_UsergroupForm_edit: "Edit Usergroup",
    courses_UsergroupForm_allUsers: "All Users",
    courses_UsergroupForm_save: "Save",
    course_counter_courses: "courses",
    course_counter_outOf: "out of",
    usergroup_setup_customize_title: "Name your Usergroup",
    usergroup_setup_members_title: "Add Memebers",
    userList_table_header_name: "Name",
    userList_table_header_email: "Email",
    userList_table_header_membership: "Membership",
    userlist_table_body_isMember: "Member",
    userlist_table_body_notMember: "Not a member",
    userList_pagination_showing: "Showing",
    userList_pagination_to: "to",
    userList_pagination_of: "of",
    userList_pagination_users: "users",
    userList_pagination_previous: "Previous",
    userList_pagination_next: "Next",
    userList_search_placeholder: "Search Users...",
    chapters_durationForm_title: "Chapter Duration",
    chapters_durationForm_cancel: "Cancel",
    chapters_durationForm_edit: "Edit",
    chapters_durationForm_placeholder: "e.g.'2'",
    chapters_durationForm_save: "Save",
    chapters_levelForm_title: "Chapter Level",
    chapters_levelForm_cancel: "Cancel",
    chapters_levelForm_edit: "Edit",
    chapters_levelForm_noLevel: "No Level",
    chapters_levelForm_save: "Save",
    user_DeleteProfileForm_title: "Delete Profile",
    settings_widgetButton_configure: "Configure",
    categories_ColorForm_ColorLabel: "Color",
    categories_ColorForm_ColorFormDescription: "Select a color or enter a hex code",
    categories_TextColorForm_ColorLabel: "Text Color",
    categories_TextColorForm_ColorFormDescription: "Select a color or enter a hex code",
    categories_DarkTextColorForm_ColorLabel: "Text Color for Darkmode",
    categories_DarkTextColorForm_ColorFormDescription: "Select a color or enter a hex code",
    post_CategoryTypeForm_isCourseCategory_Description: "Set this Category, to be used for Courses",
    post_CategoryTypeForm_isNewsCategory_Description: "Set this Category, to be used for News",
    post_CategoryTypeForm_isLiveEventCategory_Description: "Set this Category, to be used for Live Events",
    commonButton_cancel: "Cancel",
    commonButton_save: "Save",
    user_RoleForm_Label: "Role",
    user_UsergroupForm_Label: "Usergroup",
    user_RoleForm_noRole: "No Role assigned",
    user_isBannedForm_Label: "User Ban status",
    customize_PrimaryButtonColorForm_ColorLabel: "Primary Button Color",
    customize_DarkPrimaryButtonColorForm_ColorLabel: "Primary Button Color for Darkmode",
    customize_navPrimaryColorForm_ColorLabel: "Navigation Primary Color",
    customize_navBackgroundColorForm_ColorLabel: "Navigation Background Color",
    customize_navDarkPrimaryColorForm_ColorLabel: "Navigation Primary Color for Darkmode",
    customize_navDarkBackgroundColorForm_ColorLabel: "Navigation Background Color for Darkmode",
    customize_ThemeColorForm_ColorLabel: "Theme Color",
    customize_DarkThemeColorForm_ColorLabel: "Dark Theme Color",
    user_DeleteProfileForm_AlerTitle: "Warning",
    user_DeleteProfileForm_AlerDescription: "Deleting your profile is permanent and cannot be undone. All your data will be lost.",
    user_DeleteProfileForm_ConfirmModalTitle: "Are you sure?",
    user_DeleteProfileForm_ConfirmModalDescription: "This action cannot be undone. This will permanently delete your account and remove your data from our servers.",
    user_DeleteProfileForm_ConfirmModalDeleteProfile: "Delete Profile",
    chapters_levelForm_noAuthor: "No Author",
    biliing_page_header: "Billing & Subscription",
    billing_page_enterPaymentDetails: "Enter Payment Details",
    billing_page_payment_endswith: "ends with",
    billing_page_payment_expires: "Expires",
    biliing_page_addCard: "Click to pay with this card",
    biliing_page_backToPlans: "Back to Plans",
    billing_page_Tabs_Overview: "Overview",
    billing_page_Tabs_Plans: "Plans",
    billing_page_Tabs_Payment: "Payment",
    billing_page_Tabs_BillingHistory: "Billing History",
    billing_page_overview_currentPlan: "Current Plan:",
    billing_page_overview_startTrialText: "No Plan Selected - Click to start your 14 days trial",
    billing_page_overview_changePlan: "Change Plan",
    billing_page_overview_cancelSubscription: "Cancel Subscription",
    billing_page_plans_monthly: "Monthly",
    billing_page_plans_yearly: "Yearly",
    billing_page_payment_title: "Payment Methods",
    billing_page_payment_description: "Manage your payment details",
    billing_page_payment_endsWith: "ends with",
    billing_page_payment_removeCard: "Remove",
    billing_page_payment_noSavedPayment: "No saved payment methods.",
    billing_page_payment_AddPaymentMethod: "Add Payment Method",
    billing_page_payment_connectStripe_title: "Connect Stripe Account",
    billing_page_payment_connectStripe_description: "Link your Stripe account to receive payments",
    billing_page_payment_connectStripe_button: "Connect Stripe Account",
    billing_page_billingHistory_Title: "Billing History",
    billing_page_billingHistory_Description: "Your recent billing activity",
    billing_page_billingHistory_TableHead_InvoiceId: "Invoice ID",
    billing_page_billingHistory_TableHead_PaidAmount: "Amount Paid",
    billing_page_billingHistory_TableHead_Status: "Status",
    billing_page_billingHistory_TableHead_Date: "Date",
    cancelSubscription_title: "Cancel Subscription",
    cancelSubscription_description: "By submitting the form your subscription will be cancelled, please tell us why you want to cancel the Subscription",
    cancelSubscription_options_tooExpensive: "Too Expensive",
    cancelSubscription_options_noLongerNeeded: "No longer needed",
    cancelSubscription_options_switchingCompetitor: "Switching to a competitor",
    cancelSubscription_options_otherReason: "Other Reason",
    cancelSubscription_label_pleaseSpecifiy: "Please specify:",
    cancelSubscription_cancel: "Close",
    cancelSubscription_submitting: "Cancelling Subscription",
    cancelSubscription_submit: "Cancel Subscription",
    dashboard_notificationBanner_verifyEmail_1: "Please verify Your Email",
    dashboard_notificationBanner_verifyEmail_2: "An email is sent to ",
    dashboard_notificationBanner_verifyEmail_3: "Please check your inbox and spam folder.",
    dashboard_notificationBanner_subscriptionInfo_1: "days left in your subscription period, please visit",
    dashboard_notificationBanner_subscriptionInfo_2: "billings page",
    dashboard_notificationBanner_subscriptionInfo_3: "to renew your subscription.",
    analytics_chart_title: "Detailed Cours Revenue",
    course_durationForm_minutes: "Minutes",
    chapters_durationForm_hoursLabel: "Hours",
    chapters_durationForm_minutesLabel: "Minutes",
    course_attachmentForm_name: "Attachment Name",
    course_attachmentForm_file: "Attachment FIle",
    course_attachmentForm_submit: "Save",
    course_attachmentForm_namePlaceholder: "Enter attachment name",
    course_attachmentForm_changeFile: "Change Attachment",
    level_beginner: "Beginner",
    level_intermediate: "Intermediate",
    level_advanced: "Advanced",
    level_expert: "Expert",
    level_master: "Master",
    banned: "Banned",
    not_banned: "not Banned",
    courses_setup_edit_chapter: "Edit Chapter",
    data_table_title: "Title",
    data_table_price: "Price",
    data_table_published: "Published",
    data_table_createdAt: "Created At",
    data_table_name: "Name",
    data_table_color: "Color",
    data_table_Username: "Username",
    data_table_email: "Email",
    data_table_role: "Role",
    data_table_userIsBanned: "User Is Banned",
    data_table_edit: "Edit",
    data_table_draft: "Draft",
    data_table_locale: "en-US",
    dashboard_popularCHapter_noFavorites: "No favorite chapters yet",
    settings_defaultLanguage_title: "Default Language",
    post_setup_advertise_title: "Advertise your Post",
    post_LiveEventForm_noLiveEvent: "No live event selected",
    post_LiveEventForm_title: "Live Event",
    post_CourseForm_noCourse: "No course selected",
    post_CourseForm_title: "Course",
    linkedCourse_button_viewCourse: "View Course",
    linkedEvent_button_viewEvent: "Join Event",
    analytics_overviewContainer_title: "Analytics and Statistics",
    analytics_overviewFinance_title: "Finance Analytics",
    analytics_overviewCourse_title: "Course Analytics",
    analytics_overviewLiveEventAnalytics_title: "Event Analytics",
    analytics_overviewPostAnalytics_title: "Posts Analytics",
    analytics_widgetButton_view: "View",
    post_card_linked_items_title: "Linked Items",
    linkedEvent_button_starts: "Starts at",
    linkedEvent_button_ends: "Ends at",
    analytic_courses_totalCourses_label: "Total Courses",
    analytic_courses_totalChapters_label: "Total Chapters",
    analytic_courses_totalPurchasedCourses_label: "Total Purchases",
    analytic_courses_NotStartedCourses_label: "Not Started Courses",
    analytic_courses_inProgress_label: "In Progress",
    analytic_courses_completedCourses_label: "Completed Courses",
    analytic_courses_coursePurchasDistribution_label: "Course Purchase Distribution",
    analytic_courses_totalCourseLikes_label: "Total Course Likes",
    analytic_events_totalEvents_label: "Total Events",
    analytic_events_upcomingEvents_label: "Upcoming Events",
    analytic_events_pastEvents_label: "Past Events",
    analytic_events_totalEventsLikes_label: "Total Event Likes",
    analytic_posts_totalPosts_label: "Total Posts",
    analytic_posts_totalPostsLikes_label: "Posts with Comments",
    analytic_posts_avgCommentsPosts_label: "Avg. Comments per Post",
    analytic_posts_postEngagement_label: "Post Engagement",
    analytic_posts_postLikeEngagement_label: "Post Like Engagement",
};