export const Francaise: Record<string, string> = {
  documents: "documents",
  document_hub: "centre de documents",
  type: "type",
  name: "prénom",
  created_at: "créé à",
  administration: "administration",
  create: "créer",
  create_file: "créer un fichier",
  create_folder: "créer un dossier",
  create_a_folder: "créer un dossier",
  edit_folder: "Modifier le Dossier",
  edit_file: "Modifier le Fichier",
  public: "public",
  cancel: "annuler",
  placeholder: "Veuillez entrer le nom du dossier",
  placeholder_file: "Veuillez entrer le nom du fichier",
  edit: "modifier",
  file: "fichier",
  upload_file: "télécharger un fichier",
  update: "mettre à jour",
  save: "sauvegarder",
  rename: "renommer",
  are_you_sure_you_want_to_delete: "Êtes-vous sûr de vouloir supprimer",
  delete: "effacer",
  a_file: "un fichier",
  a_folder: "un dossier",
  add: "ajouter",
  navigation_administration_button_text: "Administration",
  navigation_administration_button_text_exit: "Quitter",
  navigation_theme_toggle_light: "Lumière",
  navigation_theme_toggle_dark: "Sombre",
  navigation_theme_toggle_system: "Système",
  navigation_language_toggle_english: "Anglais",
  navigation_language_toggle_german: "Allemand",
  navigation_language_toggle_french: "Français",
  navigation_language_toggle_spanish: "Espagnol",
  navigation_language_toggle_italian: "Italien",
  navigation_language_toggle_portuguese: "Portugais",
  navigation_language_toggle_russian: "Russe",
  navigation_language_toggle_mandarin: "Mandarin",
  navigation_search_placeholder: "Rechercher",
  navigation_footer_text: "Propulsé par",
  navigation_footer_text_product: "Produit",
  search_courseCounter_currentCourses: "Cours existants actuels",
  news_no_posts_found: "Aucun message trouvé",
  news_comments_button_label: "Commentaires",
  news_comments_input_placeholder: "Tapez votre commentaire...",
  news_comments_showmore_label: "Afficher plus +",
  news_comments_reply_button_label: "Répondre",
  live_event_futureAndPast_button_text_future: "Événements futurs",
  live_event_futureAndPast_button_text_past: "Événements passés",
  live_event_filter_button_text: "Filtrer",
  live_event_filter_title: "Filtre d'événements en direct",
  live_event_filter_description:
    "Vous pouvez filtrer les événements en donnant la date de début et/ou de fin d'un événement.",
  live_event_filter_applyFilter_button_text: "Appliquer le filtre",
  live_event_filter_clearFilter_button_text: "Effacer le filtre",
  courses_createCourse_button_text: "Créer un Cours",
  courses_noCourses_text: "Aucun cours trouvé",
  adminTable_previous_button_text: "Précédent",
  adminTable_next_button_text: "Suivant",
  courses_searchCourses_placeholder: "Filtrer les cours...",
  actions_unpublish: "Retirer la publication",
  actions_publish: "Publier",
  courses_titleForm_title: "Titre du Cours",
  courses_titleForm_cancel: "Annuler",
  courses_titleForm_edit: "Modifier le Titre",
  courses_titleForm_placeholder: "ex. : 'Développement web avancé'",
  courses_titleForm_save: "Sauvegarder",
  courses_descriptionForm_title: "Description du Cours",
  courses_descriptionForm_cancel: "Annuler",
  courses_descriptionForm_edit: "Modifier la Description",
  courses_descriptionForm_empty: "Aucune Description",
  courses_descriptionForm_placeholder: "ex. : 'Ce cours est sur...'",
  courses_descriptionForm_save: "Sauvegarder",
  course_imageForm_title: "Image du Cours",
  courses_imageForm_cancel: "Annuler",
  courses_imageForm_add: "Ajouter une Image",
  courses_imageForm_edit: "Modifier l'Image",
  courses_imageForm_aspectRatioRecoomendation:
    "Rapport d'aspect recommandé de 16:9",
  courses_categoryForm_title: "Catégorie du Cours",
  courses_categoryForm_cancel: "Annuler",
  courses_categoryForm_edit: "Modifier la Catégorie",
  courses_categoryForm_noCategory: "Aucune Catégorie",
  courses_categoryForm_save: "Sauvegarder",
  courses_chaptersForm_title: "Chapitres du Cours",
  courses_chaptersForm_cancel: "Annuler",
  courses_chaptersForm_addChapter: "Ajouter un Chapitre",
  courses_chaptersForm_placeholder: "ex. : 'Introduction au cours'",
  courses_chaptersForm_save: "Créer",
  courses_chaptersForm_noChapters: "Aucun Chapitre",
  courses_chaptersForm_reorderInstructions:
    "Glisser et déposer pour réordonner les chapitres",
  course_priceForm_title: "Prix du Cours",
  courses_priceForm_cancel: "Annuler",
  courses_priceForm_edit: "Modifier le Prix",
  courses_priceForm_noPrice: "Aucun Prix",
  courses_priceForm_placeholder: "Définir un prix pour votre cours",
  courses_priceForm_save: "Sauvegarder",
  course_attachmentForm_title: "Pièces jointes du Capitre",
  course_attachmentForm_cancel: "Annuler",
  course_attachmentForm_add: "Ajouter un Fichier",
  course_attachmentForm_noAttachments: "Aucune Pièce jointe pour le moment",
  course_attachmentForm_Recoomendation:
    "Ajoutez tout ce dont vos étudiants pourraient avoir besoin pour compléter le cours.",
  confirmModal_DialogHeader: "Êtes-vous sûr ?",
  confirmModal_DialogDescription: "Cette action ne peut pas être annulée.",
  confirmModal_DialogConfirm: "Confirmer",
  confirmModal_DialogCancel: "Annuler",
  chapter_TitleForm_title: "Titre du Chapitre",
  chapter_TitleForm_cancel: "Annuler",
  chapter_TitleForm_edit: "Modifier le Titre",
  chapter_TitleForm_save: "Sauvegarder",
  chapter_TitleForm_placeholder: "ex. : 'Introduction au cours'",
  chapter_chapterDescriptionForm_title: "Description du Chapitre",
  chapter_chapterDescriptionForm_cancel: "Annuler",
  chapter_chapterDescriptionForm_edit: "Modifier la Description",
  chapter_chapterDescriptionForm_noDescription: "Aucune Description",
  chapter_chapterDescriptionForm_save: "Sauvegarder",
  chapter_accessForm_title: "Accès au Chapitre",
  chapter_accessForm_cancel: "Annuler",
  chapter_accessForm_edit: "Modifier l'Accès",
  chapter_accessForm_isFree: "Ce chapitre est gratuit.",
  chapter_accessForm_isNotFree: "Ce chapitre n'est pas gratuit.",
  chapter_accessForm_description:
    "Cochez cette case si vous souhaitez rendre ce chapitre gratuit.",
  chapter_accessForm_save: "Sauvegarder",
  chapter_actions_unpublish: "Retirer la publication",
  chapter_actions_publish: "Publier",
  chapter_VideoForm_title: "Vidéo du Chapitre",
  chapter_VideoForm_cancel: "Annuler",
  chapter_VideoForm_edit: "Modifier la Vidéo",
  chapter_VideoForm_addVideo: "Ajouter une Vidéo",
  chapter_VideoForm_placeholder: "Lien de partage Vimeo",
  chapter_VideoForm_urlWarning:
    "Rafraîchissez la page si la vidéo n'apparaît pas.",
  post_createPost_button_text: "Créer un Post",
  post_noPosts_text: "Aucun post trouvé.",
  post_search_placeholder_text: "Filtrer les posts...",
  posts_actions_unpublish: "Retirer la publication",
  posts_actions_publish: "Publier",
  post_TitleForm_title: "Titre de la publication",
  post_TitleForm_cancel: "Annuler",
  post_TitleForm_edit: "Modifier le Titre",
  post_TitleForm_placeholder: "ex. : 'Développement web avancé'",
  post_TitleForm_save: "Sauvegarder",
  post_DescriptionForm_title: "Description de la Publication",
  post_DescriptionForm_cancel: "Annuler",
  post_DescriptionForm_edit: "Modifier la Description",
  post_DescriptionForm_noDescription: "Aucune Description",
  post_DescriptionForm_save: "Sauvegarder",
  post_CategoryForm_title: "Catégorie de la publication",
  post_CategoryForm_cancel: "Annuler",
  post_CategoryForm_edit: "Modifier la catégorie",
  post_CategoryForm_noCategory: "Aucune Catégorie",
  post_CategoryForm_save: "Sauvegarder",
  post_ImageForm_title: "Image de la publication",
  post_ImageForm_cancel: "Annuler",
  post_ImageForm_add: "Ajouter une Image",
  post_ImageForm_edit: "Modifier l'Image",
  post_ImageForm_help: "Rapport d'aspect recommandé de 16:9",
  categories_search_placeholder_text: "Filtrer les catégories...",
  categories_createCategory_button_text: "Créer Catégorie",
  categories_noCategories_text: "Aucun résultat.",
  categories_TitleForm_title: "Nom de la Catégorie",
  categories_TitleForm_cancel: "Annuler",
  categories_TitleForm_edit: "Modifier le Nom",
  categories_TitleForm_placeholder: "ex. : 'Développement web avancé'",
  categories_TitleForm_save: "Sauvegarder",
  category_ColorForm_title: "Couleur de la Catégorie",
  categories_ColorForm_cancel: "Annuler",
  categories_ColorForm_edit: "Modifier",
  categories_ColorForm_save: "Sauvegarder",
  post_CategoryTypeForm_title: "Type de Catégorie",
  post_CategoryTypeForm_isCourseCategory: "Catégorie de Cours",
  post_CategoryTypeForm_isNewsCategory: "Catégorie de Nouvelles",
  post_CategoryTypeForm_isLiveEventCategory: "Catégorie d'Événement en Direct",
  post_CategoryTypeForm_save: "Sauvegarder",
  customize_ContainerLinkForm_title: "Lien du Conteneur",
  customize_ContainerLinkForm_cancel: "Annuler",
  customize_ContainerLinkForm_edit: "Modifier le Titre",
  customize_ContainerLinkForm_placeholder: "ex. : 'Développement web avancé'",
  customize_ContainerLinkForm_save: "Sauvegarder",
  customize_ImageForm_title: "Image du Conteneur",
  customize_ImageForm_cancel: "Annuler",
  customize_ImageForm_addImage: "Ajouter une Image",
  customize_ImageForm_edit: "Modifier l'Image",
  customize_ImageForm_imageHint: "Rapport d'aspect recommandé de 16:9",
  customize_PrimaryColorForm_title: "Couleur Principale",
  customize_PrimaryColorForm_cancel: "Annuler",
  customize_PrimaryColorForm_edit: "Modifier",
  customize_PrimaryColorForm_save: "Sauvegarder",
  users_search_placeholder_text: "Filtrer les profils...",
  users_noUsers_text: "Aucun utilisateur.",
  user_TitleForm_title: "Nom d'Utilisateur",
  user_MailForm_title: "E-Mail de l'Utilisateur",
  user_RoleForm_title: "Rôle du Profil",
  user_RoleForm_cancel: "Annuler",
  user_RoleForm_edit: "Modifier le Rôle",
  user_RoleForm_save: "Sauvegarder",
  chat_ChatMessages_loading: "Chargement des messages...",
  chat_ChatMessages_error: "Quelque chose s'est mal passé !",
  chat_ChatMessages_loadPreviousMessages: "Charger les messages précédents",
  chat_ChatItem_viewPDF: "Fichier PDF",
  chat_ChatItem_edited: "(modifié)",
  chat_ChatItem_editMessage: "Message modifié",
  chat_ChatItem_saveChanges: "Sauvegarder",
  chat_ChatItem_editMessageHint:
    "Appuyez sur échapper pour annuler, entrer pour sauvegarder",
  chat_ChatInput_placeholder: "Message",
  chat_initialModal_title: "Créer votre Serveur",
  chat_initialModal_description:
    "Donnez à votre serveur une personnalité avec un nom et une image. Vous pouvez toujours le modifier plus tard.",
  chat_initialModal_serverName: "Nom du Serveur",
  chat_initialModal_serverName_placeholder: "Entrez le nom du serveur",
  chat_initialModal_createServer: "Créer",
  chat_serverSection_createChannel: "Créer un Canal",
  chat_serverSection_manageMembers: "Gérer les Membres",
  chat_server_search_placeholder: "Rechercher",
  chat_server_search_notFound: "Aucun Résultat Trouvé",
  chat_server_invite: "Inviter des Gens",
  chat_server_edit: "Éditer le Serveur",
  chat_server_manage_members: "Gérer les Membres",
  chat_server_create_channel: "Créer un Canal",
  chat_server_delete: "Supprimer le Serveur",
  chat_server_addServer: "Ajouter un Serveur",
  chat_channel_edit: "Éditer",
  chat_channel_delete: "Supprimer",
  chat_chatItem_edit: "Éditer",
  chat_chatItem_delete: "Supprimer",
  chat_socket_reconnecting: "Reconnexion : Sondage toutes les 1s",
  chat_socket_connected: "En Direct",
  chat_modal_create_server_title: "Personnaliser votre Serveur",
  chat_modal_create_server_description:
    "Donnez à votre serveur une personnalité avec un nom et une image. Vous pouvez toujours le modifier plus tard.",
  chat_modal_create_server_name: "Nom du serveur",
  chat_modal_create_server_name_placeholder: "Entrez le nom du serveur",
  chat_modal_create_server_create: "Créer",
  chat_modal_create_channel_title: "Créer un Canal",
  chat_modal_create_channel_name: "Nom du canal",
  chat_modal_create_channel_name_placeholder: "Entrez le nom du canal",
  chat_modal_create_channelType_name: "Type de Canal",
  chat_modal_create_channelType_placeholder: "Sélectionnez un type de canal",
  chat_modal_create_channel_create: "Créer",
  chat_modal_invite_title: "Inviter des Amis",
  chat_modal_invite_link_label: "Lien d'invitation au serveur",
  chat_modal_invite_new: "Générer un nouveau lien",
  chat_modal_manageMembers_title: "Gérer les Membres",
  chat_modal_manageMembers_description: "Membres",
  chat_modal_manageMembers_role_label: "Rôle",
  chat_modal_manageMembers_role_guest: "Invité",
  chat_modal_manageMembers_role_moderator: "Modérateur",
  chat_modal_manageMembers_kick: "Expulser",
  chat_modal_delete_server_title: "Supprimer le Serveur",
  chat_modal_delete_server_description_1:
    "Êtes-vous sûr de vouloir faire cela ?",
  chat_modal_delete_server_description_2: "sera définitivement supprimé.",
  chat_modal_delete_server_cancel_button: "Annuler",
  chat_modal_delete_server_delete_button: "Confirmer",
  chat_modal_edit_channel_title: "Éditer le Canal",
  chat_modal_edit_channel_name: "Nom du Canal",
  chat_modal_edit_channel_name_placeholder: "Entrez le nom du canal",
  chat_modal_edit_channel_type: "Type de Canal",
  chat_modal_edit_channel_save: "Sauvegarder",
  chat_modal_edit_channel_type_placeholder: "Sélectionnez un type de canal",
  chat_modal_deleteChannel_title: "Supprimer le Canal",
  chat_modal_deleteChannel_description_1:
    "Êtes-vous sûr de vouloir faire cela ?",
  chat_modal_deleteChannel_description_2: "sera définitivement supprimé.",
  chat_modal_deleteChannel_cancel_button: "Annuler",
  chat_modal_deleteChannel_delete_button: "Confirmer",
  chat_modal_leaveServer_title: "Quitter le Serveur",
  chat_modal_leaveServer_description_1: "Êtes-vous sûr de vouloir quitter",
  chat_modal_leaveServer_cancel: "Annuler",
  chat_modal_leaveServer_leave: "Confirmer",
  chat_modal_messageFile_title: "Ajouter une pièce jointe",
  chat_modal_messageFile_description: "Envoyer un fichier comme message",
  chat_modal_messageFile_submit: "Envoyer",
  createCourse_title: "Nommer votre Cours",
  createCourse_description:
    "Comment souhaitez-vous nommer votre cours ? Ne vous inquiétez pas, vous pouvez le changer plus tard.",
  createCourse_form_label: "Titre du cours",
  createCourse_form_description: "Que allez-vous enseigner dans ce cours ?",
  createCourse_form_placeholder: "ex. : 'Développement web avancé'",
  createCourse_cancel: "Annuler",
  createCourse_submit: "Continuer",
  createPost_title: "Nommer votre Publication",
  createPost_description:
    "Comment souhaitez-vous nommer votre publication ? Ne vous inquiétez pas, vous pouvez le changer plus tard.",
  createPost_form_label: "Titre de la publication",
  createPost_form_placeholder: "ex. : 'Développement web avancé'",
  createPost_form_description:
    "Que souhaitez-vous faire savoir à votre communauté ?",
  createPost_cancel: "Annuler",
  createPost_submit: "Continuer",
  createLiveEvent_title: "Nommer votre Événement en Direct",
  createLiveEvent_description:
    "Comment souhaitez-vous nommer votre événement en direct ? Ne vous inquiétez pas, vous pouvez le changer plus tard.",
  createLiveEvent_form_label: "Titre de l'événement",
  createLiveEvent_form_placeholder: "ex. : 'Développement web avancé'",
  createLiveEvent_form_description:
    "Que montrerez-vous lors de votre événement ?",
  createLiveEvent_cancel: "Annuler",
  createLiveEvent_submit: "Continuer",
  createCategory_title: "Nommer votre Catégorie",
  createCategory_description:
    "Comment souhaitez-vous nommer votre catégorie ? Ne vous inquiétez pas, vous pouvez le changer plus tard.",
  createCategory_form_label: "Nom de la catégorie",
  createCategory_form_placeholder: "ex. : 'Développement web avancé'",
  createCategory_form_description:
    "Que catégoriserez-vous sur votre plateforme ?",
  createCategory_cancel: "Annuler",
  createCategory_submit: "Sauvegarder",
  liveEvent_createEvent_button_text: "Créer un Événement",
  liveEvent_noEvent_text: "Aucun événement trouvé.",
  liveEvent_filterEvents_placeholder: "Filtrer les événements...",
  infocard_courses: "Cours",
  infocard_course: "Cours",
  infocard_inprogress: "En cours",
  infocard_completed: "Terminé",
  no_courses: "Aucun cours trouvé",
  customize_customizeCcontainer_title: "Personnalisez votre conteneur",
  customize_customizeCcontainer_requiredFields:
    "Remplissez tous les champs requis",
  customize_customizeYourContainer: "Personnalisez votre conteneur",
  requiredFields: "*requis",
  customize_AddImageTitle: "Ajouter une image en tant que logo",
  chat_welcome_title: "Bienvenue dans #",
  chat_welcome_description: "Ceci est le début du #",
  chat_welcome_description2: "canal",
  chat_welcome_title_directMessage:
    "Ceci est le début de votre conversation avec",
  serverSidebar_textChannel: "Canaux texte",
  serverSidebar_videoChannel: "Canaux vidéo",
  serverSidebar_audioChannel: "Canaux audio",
  serverSidebar_member: "Membres",
  chat_serversection_label_text: "Canaux texte",
  chat_serversection_label_audio: "Canaux audio",
  chat_serversection_label_video: "Canaux vidéo",
  chat_serversection_label_member: "Membres",
  chat_server_search_command_placeholder:
    "Rechercher tous les canaux et membres",
  course_setup_title: "Configuration du cours",
  course_setup_undertitle: "Remplissez tous les champs requis",
  course_setup_course_information_title: "Personnalisez votre cours",
  course_setup_price_title: "Vendez votre cours",
  course_setup_chapters_title: "Chapitres du cours",
  course_setup_attachments_title: "Ressources et pièces jointes",
  courses_chapter_backToCourse_button_text:
    "Retour à la configuration du cours",
  courses_chapter_title: "Création de chapitre",
  courses_chapter_undertitle: "Remplissez tous les champs",
  course_chapter_customize_title: "Personnalisez votre chapitre",
  course_chapter_access: "Paramètres d'accès",
  course_chapter_video: "Ajouter une vidéo",
  courses_setup_free_badge: "Gratuit",
  courses_setup_published_text: "Publié",
  courses_setup_draft_text: "Brouillon",
  post_setup_title: "Configuration de la publication",
  post_setup_undertitle: "Remplissez tous les champs requis",
  post_setup_customize_title: "Personnalisez votre publication",
  post_setup_image_title: "Ajouter une image à votre publication",
  liveEvent_PremiumFeature_description:
    "Pour utiliser les Événements en direct et configurer vos événements numériques et hybrides avec notre logiciel, vous devez utiliser le package de communauté.",
  liveEvent_PremiumFeature_button_text: "Acheter le package de communauté",
  liveEvent_setup_title: "Configuration de l'événement",
  liveEvent_setup_undertitle: "Remplissez tous les champs requis",
  liveEvent_setup_customize_title: "Personnalisez votre événement en direct",
  liveEvent_setup_video_title: "Ajoutez les ressources à votre événement",
  category_setup_title: "Configuration de la catégorie",
  category_setup_undertitle: "Remplissez tous les champs requis",
  category_setup_customize_title: "Nommez votre catégorie",
  user_setup_title: "Configuration de l'utilisateur",
  user_setup_undertitle: "Remplissez tous les champs requis",
  user_setup_customize_title: "Personnalisez l'utilisateur",
  course_unpublish_banner:
    "Ce cours n'est pas publié. Il ne sera pas visible pour les utilisateurs.",
  post_unpublish_banner:
    "Cette publication n'est pas publiée. Elle ne sera pas visible pour les utilisateurs.",
  liveEvent_unpublish_banner:
    "Cet événement n'est pas publié. Il ne sera pas visible pour les utilisateurs.",
  category_unpublish_banner:
    "Cette catégorie n'est pas publiée. Elle ne sera pas visible pour les utilisateurs.",
  chapter_unpublish_banner:
    "Ce chapitre n'est pas publié. Il ne sera pas visible pour les utilisateurs.",
  analytics_total_revenue_label: "Revenu total",
  analytics_total_sales_label: "Ventes totales",
  customize_NavColors_title: "Personnalisez les couleurs de votre navigation",
  customize_navBackgroundColorForm_title: "Couleur de fond de la navigation",
  customize_navDarkBackgroundColorForm_title:
    "Couleur de fond de la navigation en mode sombre",
  customize_navPrimaryColorForm_title: "Couleur principale de la navigation",
  customize_navDarkPrimaryColorForm_title:
    "Couleur principale de la navigation en mode sombre",
  customize_customizeNavigation_title:
    "Personnalisez les couleurs de votre navigation",
  customize_NavColorsDark_title:
    "Personnalisez les couleurs de votre navigation en mode sombre",
  settings_menu_containersettings_title: "Paramètres du conteneur",
  settings_menu_navigationdesign_title: "Design de la navigation",
  settings_backToMenu_button_text: "Retour au menu",
  nav_item_browse: "Parcourir",
  nav_item_dashboard: "Tableau de bord",
  nav_item_news: "Nouvelles",
  nav_item_liveEvent: "Événement en direct",
  nav_item_chat: "Chat",
  nav_item_documents: "Documents",
  nav_admin_item_course: "Cours",
  nav_admin_item_posts: "Publications",
  nav_admin_item_liveEvents: "Événements en direct",
  nav_admin_item_categories: "Catégorie",
  nav_admin_item_users: "Utilisateurs",
  nav_admin_item_analytics: "Analytique",
  nav_admin_item_settings: "Paramètres",
  customize_ImageFormDark_title: "Image du conteneur en mode sombre",
  settings_Container_IconForm_title: "Icône du conteneur",
  privacy_policy_title: "Politique de Confidentialité & Conditions Générales",
  privacy_policy_description:
    "Pour continuer à utiliser notre plateforme, veuillez examiner et accepter notre Politique de Confidentialité et nos Conditions Générales. Votre acceptation garantit que vous avez lu et compris comment vos données seront traitées et que vous acceptez les règles qui régissent notre plateforme. Nous accordons de l'importance à votre vie privée et nous efforçons de fournir un environnement sûr à tous les utilisateurs.",
  privacy_policy_button: "J'ai lu et j'accepte",
  user_isBannedForm_title: "Statut de Bannissement",
  user_isBannedForm_cancel: "Annuler",
  user_isBannedForm_edit: "Éditer",
  user_isBannedForm_save: "Enregistrer",
  user_setup_settings_title: "Zone de Danger",
  courses_authorForm_cancel: "Annuler",
  courses_authorForm_edit: "Modifier l'Auteur",
  courses_authorForm_save: "Sauvegarder",
  courses_authorForm_placeholder: "p.ex. 'Max Mustermann'",
  courses_authorForm_title: "Nom de l'Auteur",
  courses_authorForm_empty: "vide",
  infocard_completedChapters: "Chapitres Complétés",
  infocard_currentOnlineUsers: "Utilisateurs en Ligne Actuels",
  profile_manageAccount: "Gérer le compte",
  profile_signOut: "Se déconnecter",
  profile_change_customize_username: "Changer votre nom d'utilisateur",
  profile_TitleForm_title: "Nom d'utilisateur",
  profile_TitleForm_cancel: "Annuler",
  profile_TitleForm_edit: "Modifier",
  profile_TitleForm_placeholder: "NomUtilisateur123",
  profile_TitleForm_save: "Enregistrer",
  courses_list_backToDashboard_button_text: "Retour au tableau de bord",
  dashboard_courseTable_CourseStatus_Title: "Mes Cours",
  dashboard_courseTable_courseName: "Nom du cours",
  dashboard_courseTable_paid: "Payé",
  dashboard_courseTable_progress: "Progression",
  dashboard_courseTable_chapter: "Chapitre",
  dashboard_courseTable_action: "Action",
  dashboard_courseTable_viewAllCourses_button_text: "Voir tout",
  dashboard_courseTable_viewCourse_button_text: "CHERCHER",
  chapter_aboutcourse_title: "À propos du chapitre",
  chapter_ChapterDocuments_Title: "Documents",
  courses_setup_backToCourseAdminList_button_text:
    "Retour à la Vue d'ensemble des Cours",
  post_setup_backToPostAdminList_button_text:
    "Retour à la Vue d'ensemble des Publications",
  liveEvent_setup_backToEventAdminList_button_text:
    "Retour à la Vue d'ensemble des Événements en Direct",
  category_setup_backToCategoryAdminList_button_text:
    "Retour à la Vue d'ensemble des Catégories",
  user_setup_backToUserAdminList_button_text:
    "Retour à la Vue d'ensemble des Utilisateurs",
  settings_backToAdminSettings_button_text:
    "Retour à la Vue d'ensemble des Paramètres",
  navigation_language_tooltip: "Langues",
  navigation_mode_tooltip: "Mode",
  navigation_administration_tooltip: "Administration",
  navigation_profile_tooltip: "Profil",
  privacy_policy_link: "Politique de Confidentialité",
  privacy_termsOfService_link: "Conditions d'Utilisation",
  chapter_attachments_NoDocuments: "Pas de documents",
  nav_item_career: "Carrière",
  nav_item_calendar: "Calendrier",
  nav_item_knowledgeHub: "Centre de Connaissances",
  profile_OnlineStatus_Online: "En ligne",
  profile_OnlineStatus_Away: "Indisponible",
  profile_OnlineStatus_DoNotDisturb: "Ne pas déranger",
  profile_OnlineStatus_Invisible: "Invisible",
  profile_OnlineStatus_Offline: "Hors ligne",
  profile_status_text: "Statut",
  profile_help: "Aide",
  course_chapter_author_text: "Auteur -",
  live_event_filter_start_date_text: "Date de début",
  live_event_filter_end_date_text: "Date de fin",
  chapter_aboutevent_title: "À propos de l'événement",
  chat_server_leave: "Quitter Serveur",
  settings_menu_design_title: "Bouton Design",
  customize_customizeContainer_title: "Personnalisez votre conteneur",
  customize_PrimaryButtonColors_title:
    "Personnalisez votre couleur de bouton principal",
  customize_PrimaryButtonColorsDark_title:
    "Personnalisez votre couleur de bouton principal en mode sombre",
  customize_PrimaryButtonColorForm_title: "Color de bouton principal",
  customize_PrimaryButtonColorForm_cancel: "Annuler",
  customize_PrimaryButtonColorForm_edit: "Modifier",
  customize_PrimaryButtonColorForm_save: "Enregistrer",
  customize_DarkPrimaryButtonColorForm_title:
    "Color de bouton principal en mode sombre",
  dashboard_popularChapter_chapterName_text: "Nom du chapitre",
  dashboard_popularChapter_courseName_text: "Nom du cours",
  dashboard_popularChapter_likes_text: "J'aime",
  dashboard_popularChapter_comments_text: "Commentaires",
  dashboard_popularChapter_action_text: "Action",
  categories_ColorForm_title: "Couleur de Catégorie",
  profile_MemberIdForm_title: "ID de membre",
  profile_MemberIdForm_cancel: "Annuler",
  profile_MemberIdForm_edit: "Modifier",
  profile_MemberIdForm_placeholder: "111",
  profile_MemberIdForm_save: "Enregistrer",
  settings_menu_themedesign_title: "Theme Design",
  post_scheduleDateForm_title: "Planifier la Date & l'Heure",
  post_scheduleDateForm_cancel: "Annuler",
  post_scheduleDateForm_edit: "Modifier la Date",
  post_scheduleDateForm_save: "Enregistrer",
  liveEvent_TitleForm_title: "Titre de l'Événement",
  liveEvent_TitleForm_cancel: "Annuler",
  liveEvent_TitleForm_edit: "Modifier le Titre",
  liveEvent_TitleForm_save: "Enregistrer",
  liveEvent_DescriptionForm_title: "Description de l'Événement",
  liveEvent_DescriptionForm_cancel: "Annuler",
  liveEvent_DescriptionForm_edit: "Modifier la Description",
  liveEvent_DescriptionForm_save: "Enregistrer",
  liveEvent_CategoryForm_title: "Catégorie de l'Événement",
  liveEvent_CategoryForm_cancel: "Annuler",
  liveEvent_CategoryForm_edit: "Modifier la Catégorie",
  liveEvent_CategoryForm_save: "Enregistrer",
  liveEvent_startDateTimeForm_title: "Date & Heure de Début",
  liveEvent_startDateTimeForm_cancel: "Annuler",
  liveEvent_startDateTimeForm_edit: "Modifier la Date",
  liveEvent_startDateTimeForm_save: "Enregistrer",
  liveEvent_endDateTimeForm_title: "Date & Heure de Fin",
  liveEvent_endDateTimeForm_cancel: "Annuler",
  liveEvent_endDateTimeForm_edit: "Modifier la Date",
  liveEvent_endDateTimeForm_save: "Enregistrer",
  liveEvent_ImageForm_title: "Miniature de l'Événement",
  liveEvent_ImageForm_add: "Ajouter une Image",
  liveEvent_ImageForm_edit: "Modifier l'Image",
  liveEvent_ImageForm_description: "Ratio 16:9 recommandé",
  liveEvent_videoForm_title: "Événement en Direct",
  liveEvent_videoForm_cancel: "Annuler",
  liveEvent_videoForm_edit: "Modifier la Vidéo",
  liveEvent_videoForm_add: "Ajouter une Vidéo",
  liveEvent_videoForm_save: "Enregistrer",
  liveEvent_videoForm_preview: "Actualisez la page si la vidéo n'apparaît pas.",
  dashboard_popularChapter_title: "Chapitres les Plus Populaires",
  sidebar_help: "Aide",
  sidebar_privacy_policy: "Politique de Confidentialité",
  profile_backToDashboard_button_text: "Retour au tableau de bord",
  profile_EmailForm_title: "E-mail",
  profile_EmailForm_cancel: "Annuler",
  profile_EmailForm_edit: "Modifier",
  profile_EmailForm_placeholder: "ex. 'max.mustermann@test.com'",
  profile_EmailForm_save: "Enregistrer",
  profile_ImageForm_title: "Image de profil",
  profile_ImageForm_cancel: "Annuler",
  profile_ImageForm_add: "Ajouter une image",
  profile_ImageForm_edit: "Modifier l'image",
  profile_ImageForm_help: "Ratio 1:1 recommandé",
  course_durationForm_title: "Durée du Cours",
  courses_durationForm_cancel: "Annuler",
  courses_durationForm_edit: "Éditer",
  course_durationForm_hours: "Heures",
  courses_durationForm_placeholder: "par ex. '2'",
  courses_durationForm_save: "Enregistrer",
  courses_levelForm_title: "Niveau du Cours",
  courses_levelForm_cancel: "Annuler",
  courses_levelForm_edit: "Éditer",
  courses_levelForm_noLevel: "Aucun Niveau",
  courses_levelForm_save: "Enregistrer",
  course_SpecialTypeForm_title: "Statut Spécial",
  course_SpecialTypeForm_isNew: "Nouveau",
  course_SpecialTypeForm_isFeatured: "Mis en Avant",
  course_SpecialTypeForm_isBestseller: "Meilleure Vente",
  course_SpecialTypeForm_save: "Enregistrer",
  course_card_chapter: "Chapitre",
  course_card_chapters: "Chapitres",
  course_card_hour: "Heure",
  course_card_hours: "Heures",
  course_card_no_level: "Aucun niveau",
  course_card_bestseller: "Meilleure vente",
  course_card_new: "Nouveau",
  course_card_featured: "En vedette",
  course_card_edit: "Modifier",
  course_card_delete: "Supprimer",
  descriptionModal_DialogHeader: "Description",
  descriptionModal_DialogCancel: "Fermer",
  courses_sidebar_infoDescription: "Description du cours",
  news_myFavorites_title: "Mes Favoris",
  news_Posts_title: "Publications",
  news_LiveEvents_title: "Événements en Direct",
  news_Courses_title: "Cours",
  news_Chapters_title: "Chapitres",
  chapter_purchaseBanner_text:
    "Vous devez acheter ce cours pour regarder ce chapitre.",
  chat_modal_deleteMessage_title: "Supprimer le message",
  chat_modal_deleteMessage_description1: "Êtes-vous sûr de vouloir faire cela?",
  chat_modal_deleteMessage_description2:
    "Le message sera supprimé définitivement.",
  chat_modal_deleteMessage_cancel: "Annuler",
  chat_modal_deleteMessage_confirm: "Confirmer",
  liveEvent_chat_title: "Chat du stream",
  liveEvent_chat_inputField: "Tapez votre commentaire",
  liveEvent_start: "Commence",
  liveEvent_end: "Se termine",
  course_enrollButton_free: "S'inscrire gratuitement",
  course_enrollButton: "S'inscrire pour",
  course_progressButton_NotComplete: "Non terminé",
  course_progressButton_MarkComplete: "Marquer comme terminé",
  createContainer_title: "Nommez votre Conteneur",
  createCotainer_description: "Quel est le nom du Conteneur ou du Client que vous utiliserez?",
  createContainer_form_label: "Nom du Conteneur",
  createContainer_form_placeholder: "ex. 'Client XYZ'",
  createContainer_form_description: "Que allez-vous enseigner dans ce conteneur?",
  createContainer_cancel: "Annuler",
  createContainer_submit: "Créer",
  dashboard_doughnutChart_title: "Statistiques du cours",
  liveEvent_eventMdal_title: "Voulez-vous terminer cette session?",
  liveEvent_eventMdal_no: "Non",
  liveEvent_eventMdal_yes: "Oui",
  dashboard_doughnut_completed: "Terminé",
  dashboard_doughnut_inprogress: "En cours",
  dashboard_doughnut_notStarted: "Non commencé",
  dashboard_courseTable_viewFavoriteChapters_button_text: "Mes Chapitres Favoris",
  courses_list_backToCourses_button_text:"Retour aux Cours",
  dashboard_courseTable_viewMyFavourties_button_text: "Mes Cours Favoris",
  dashboard_eventTable_viewFavoriteEvents_button_text: "Mes Événements Préférés",
  live_event_futureAndPast_button_text_all: "Tous",
  no_events_found: "Aucun événement trouvé",
  courses_list_backToLiveEvents_button_text: "Retour aux événements en direct",
  goBack_button_text: "Retour",
  profile_oldPassword_placeholder: "mot de passe actuel",
  profile_newPasswordForm_title: "Mot de passe",
  profile_newPasswordForm_cancel: "Annuler",
  profile_newPasswordForm_edit: "Modifier",
  profile_newPasswordForm_placeholder: "nouveau mot de passe",
  profile_confirmPasswordForm_placeholder: "confirmer le nouveau mot de passe",
  profile_newPasswordForm_save: "Enregistrer",
  modal_share_link_title: "Partager",
  modal_share_link_label: "Partager le lien",
  profile_manageBilling: "Facturation",
  customize_customizeTheme_title: "Personnalisez la couleur de votre thème",
  customize_ThemeColors_title: "Personnalisez la couleur de votre thème",
  customize_ThemeColorForm_title: "Couleur du thème",
  customize_ThemeColorForm_cancel: "Annuler",
  customize_ThemeColorForm_edit: "Modifier",
  customize_THemeColorForm_save: "Enregistrer",
  customize_ThemeColorsDark_title: "Personnalisez la couleur de votre thème pour le mode sombre",
  customize_DarkThemeColorForm_title: "Couleur du thème pour le mode sombre",
  customize_ThemeColorForm_save: "Enregistrer",
  settings_menu_authenticationdesign_title: "Conception de l'authentification",
  customize_authDesignSettings_title: "Personnalisez vos pages d'authentification",
  customize_authDesignSettings_signUp_title: "Ajouter une image pour votre page d'inscription",
  customize_authDesignSettings_signIn_title: "Ajouter une image pour votre page de connexion",
  customize_authDesignSettings_forgetPassword_title: "Ajouter une image pour votre page de mot de passe oublié",
  customize_SignUpImageForm_title: "Image d'inscription",
  customize_SignUpImageForm_cancel: "Annuler",
  customize_SignUpImageForm_addImage: "Ajouter une image",
  customize_SignUpImageForm_edit: "Éditer",
  customize_SignUpImageForm_imageHint: "Format d'image 16:9 recommandé",
  customize_darkSignUpImageForm_title: "Image d'inscription pour le mode sombre",
  customize_darkSignUpImageForm_cancel: "Annuler",
  customize_darkSignUpImageForm_addImage: "Ajouter une image",
  customize_darkSignUpImageForm_edit: "Éditer",
  customize_darkSignUpImageForm_imageHint: "Format d'image 16:9 recommandé",
  customize_SignInImageForm_title: "Image de connexion",
  customize_SignInImageForm_cancel: "Annuler",
  customize_SignInImageForm_addImage: "Ajouter une image",
  customize_SignInImageForm_edit: "Éditer",
  customize_SignInImageForm_imageHint: "Format d'image 16:9 recommandé",
  customize_darkSignInImageForm_title: "Image de connexion pour le mode sombre",
  customize_darkSignInImageForm_cancel: "Annuler",
  customize_darkSignInImageForm_addImage: "Ajouter une image",
  customize_darkSignInImageForm_edit: "Éditer",
  customize_darkSignInImageForm_imageHint: "Format d'image 16:9 recommandé",
  customize_ForgePasswordImageForm_title: "Image de mot de passe oublié",
  customize_ForgePasswordImageForm_cancel: "Annuler",
  customize_ForgePasswordImageForm_addImage: "Ajouter une image",
  customize_ForgePasswordImageForm_edit: "Éditer",
  customize_ForgePasswordImageForm_imageHint: "Format d'image 16:9 recommandé",
  customize_darkForgePasswordImageForm_title: "Image de mot de passe oublié pour le mode sombre",
  customize_darkForgePasswordImageForm_cancel: "Annuler",
  customize_darkForgePasswordImageForm_addImage: "Ajouter une image",
  customize_darkForgePasswordImageForm_edit: "Éditer",
  customize_darkForgePasswordImageForm_imageHint: "Format d'image 16:9 recommandé",
  categories_TextColorForm_title: "Couleur du texte de la catégorie",
  categories_TextColorForm_save: "Enregistrer",
  categories_DarkTextColorForm_title: "Couleur du texte de la catégorie en mode sombre",
  categories_DarkTextColorForm_save: "Enregistrer",
  liveEvent_isStreamChatForm_title: "Chat en direct",
  liveEvent_isStreamChatForm_isStreamChat: "Activer le chat en direct",
  liveEvent_isStreamChatForm_save: "Enregistrer",
  usergroups_search_placeholder_text: "Rechercher",
  usergroups_createUsergroup_button_text: "Créer un Groupe d'Utilisateurs",
  usergroups_noUsergroups_text: "Aucun Groupe d'Utilisateurs",
  usergroup_unpublish_banner: "Ce groupe d'utilisateurs n'est pas publié. Il ne fonctionnera pas comme prévu.",
  usergroup_setup_title: "Configuration du Groupe d'Utilisateurs",
  usergroup_setup_undertitle: "Remplissez tous les champs requis",
  usergroup_TitleForm_title: "Nom du Groupe d'Utilisateurs",
  usergroup_TitleForm_cancel: "Annuler",
  usergroup_TitleForm_edit: "Modifier",
  usergroup_TitleForm_placeholder: "Groupe d'Experts",
  usergroup_TitleForm_save: "Enregistrer",
  nav_admin_item_usergroups: "Groupes d'Utilisateurs",
  createUsergroup_title: "Nommer votre Groupe d'Utilisateurs",
  createUsergroup_description: "Comment souhaitez-vous nommer votre Groupe d'Utilisateurs? Ne vous inquiétez pas, vous pourrez le changer plus tard.",
  createUsergroup_form_label: "Nom du Groupe d'Utilisateurs",
  createUsergroup_form_placeholder: "Groupe de Test",
  createUsergroup_form_description: "À quoi servira ce Groupe d'Utilisateurs spécifique?",
  createUsergroup_cancel: "Annuler",
  createUsergroup_submit: "Enregistrer",
  profile_UsergroupForm_title: "Groupe d'Utilisateurs",
  profile_UsergroupForm_cancel: "Annuler",
  profile_UsergroupForm_edit: "Modifier le Groupe d'Utilisateurs",
  profile_UsergroupForm_allUsers: "Tous les Utilisateurs",
  profile_UsergroupForm_save: "Enregistrer",
  post_UsergroupForm_title: "Groupe d'Utilisateurs",
  post_UsergroupForm_cancel: "Annuler",
  post_UsergroupForm_edit: "Modifier le Groupe d'Utilisateurs",
  post_UsergroupForm_allUsers: "Tous les Utilisateurs",
  post_UsergroupForm_noUsergroup: "Aucun Groupe d'Utilisateurs",
  post_UsergroupForm_save: "Enregistrer",
  liveEvent_UsergroupForm_title: "Groupe d'Utilisateurs",
  liveEvent_UsergroupForm_cancel: "Annuler",
  liveEvent_UsergroupForm_edit: "Modifier le Groupe d'Utilisateurs",
  liveEvent_UsergroupForm_allUsers: "Tous les Utilisateurs",
  liveEvent_UsergroupForm_save: "Enregistrer",
  courses_UsergroupForm_title: "Groupe d'Utilisateurs",
  courses_UsergroupForm_cancel: "Annuler",
  courses_UsergroupForm_edit: "Modifier le Groupe d'Utilisateurs",
  courses_UsergroupForm_allUsers: "Tous les Utilisateurs",
  courses_UsergroupForm_save: "Enregistrer",
  course_counter_courses: "cours",
  course_counter_outOf: "sur",
  usergroup_setup_customize_title: "Nommez votre groupe d'utilisateurs",
  usergroup_setup_members_title: "Ajouter des membres",
  userList_table_header_name: "Nom",
  userList_table_header_email: "E-mail",
  userList_table_header_membership: "Adhésion",
  userlist_table_body_isMember: "Membre",
  userlist_table_body_notMember: "Non membre",
  userList_pagination_showing: "Affichage",
  userList_pagination_to: "à",
  userList_pagination_of: "de",
  userList_pagination_users: "utilisateurs",
  userList_pagination_previous: "Précédent",
  userList_pagination_next: "Suivant",
  userList_search_placeholder: "Rechercher des utilisateurs...",
  chapters_durationForm_title: "Durée du Chapitre",
  chapters_durationForm_cancel: "Annuler",
  chapters_durationForm_edit: "Modifier",
  chapters_durationForm_placeholder: "ex. '2'",
  chapters_durationForm_save: "Enregistrer",
  chapters_levelForm_title: "Niveau du Chapitre",
  chapters_levelForm_cancel: "Annuler",
  chapters_levelForm_edit: "Modifier",
  chapters_levelForm_noLevel: "Pas de Niveau",
  chapters_levelForm_save: "Enregistrer",
  user_DeleteProfileForm_title: "Supprimer le profil",
  settings_widgetButton_configure: "Configurer",
  categories_ColorForm_ColorLabel: "Couleur",
  categories_ColorForm_ColorFormDescription: "Sélectionnez une couleur ou entrez un code hexadécimal",
  categories_TextColorForm_ColorLabel: "Couleur du texte",
  categories_TextColorForm_ColorFormDescription: "Sélectionnez une couleur ou entrez un code hexadécimal",
  categories_DarkTextColorForm_ColorLabel: "Couleur du texte pour le mode sombre",
  categories_DarkTextColorForm_ColorFormDescription: "Sélectionnez une couleur ou entrez un code hexadécimal",
  post_CategoryTypeForm_isCourseCategory_Description: "Définissez cette catégorie pour être utilisée pour les cours",
  post_CategoryTypeForm_isNewsCategory_Description: "Définissez cette catégorie pour être utilisée pour les actualités",
  post_CategoryTypeForm_isLiveEventCategory_Description: "Définissez cette catégorie pour être utilisée pour les événements en direct",
  commonButton_cancel: "Annuler",
  commonButton_save: "Enregistrer",
  user_RoleForm_Label: "Rôle",
  user_UsergroupForm_Label: "Groupe d'utilisateurs",
  user_RoleForm_noRole: "Aucun rôle attribué",
  user_isBannedForm_Label: "Statut de bannissement de l'utilisateur",
  customize_PrimaryButtonColorForm_ColorLabel: "Couleur du bouton principal",
  customize_DarkPrimaryButtonColorForm_ColorLabel: "Couleur du bouton principal pour le mode sombre",
  customize_navPrimaryColorForm_ColorLabel: "Couleur principale de la navigation",
  customize_navBackgroundColorForm_ColorLabel: "Couleur de fond de la navigation",
  customize_navDarkPrimaryColorForm_ColorLabel: "Couleur principale de la navigation pour le mode sombre",
  customize_navDarkBackgroundColorForm_ColorLabel: "Couleur de fond de la navigation pour le mode sombre",
  customize_ThemeColorForm_ColorLabel: "Couleur du thème",
  customize_DarkThemeColorForm_ColorLabel: "Couleur du thème sombre",
  user_DeleteProfileForm_AlerTitle: "Avertissement",
  user_DeleteProfileForm_AlerDescription: "Supprimer votre profil est permanent et ne peut pas être annulé. Toutes vos données seront perdues.",
  user_DeleteProfileForm_ConfirmModalTitle: "Êtes-vous sûr ?",
  user_DeleteProfileForm_ConfirmModalDescription: "Cette action est irréversible. Cela supprimera définitivement votre compte et supprimera vos données de nos serveurs.",
  user_DeleteProfileForm_ConfirmModalDeleteProfile: "Supprimer le profil",
  chapters_levelForm_noAuthor: "Pas d'auteur",
  biliing_page_header: "Facturation et Abonnement",
  billing_page_enterPaymentDetails: "Saisir les détails de paiement",
  billing_page_payment_endswith: "se termine par",
  billing_page_payment_expires: "Expire",
  biliing_page_addCard: "Cliquez pour payer avec cette carte",
  biliing_page_backToPlans: "Retour aux plans",
  billing_page_Tabs_Overview: "Vue d'ensemble",
  billing_page_Tabs_Plans: "Plans",
  billing_page_Tabs_Payment: "Paiement",
  billing_page_Tabs_BillingHistory: "Historique de facturation",
  billing_page_overview_currentPlan: "Plan actuel :",
  billing_page_overview_startTrialText: "Aucun plan sélectionné - Cliquez pour démarrer votre essai de 14 jours",
  billing_page_overview_changePlan: "Changer de plan",
  billing_page_overview_cancelSubscription: "Annuler l'abonnement",
  billing_page_plans_monthly: "Mensuel",
  billing_page_plans_yearly: "Annuel",
  billing_page_payment_title: "Méthodes de paiement",
  billing_page_payment_description: "Gérez vos détails de paiement",
  billing_page_payment_endsWith: "se termine par",
  billing_page_payment_removeCard: "Supprimer",
  billing_page_payment_noSavedPayment: "Aucune méthode de paiement enregistrée.",
  billing_page_payment_AddPaymentMethod: "Ajouter une méthode de paiement",
  billing_page_payment_connectStripe_title: "Connecter un compte Stripe",
  billing_page_payment_connectStripe_description: "Connectez votre compte Stripe pour recevoir des paiements",
  billing_page_payment_connectStripe_button: "Connecter un compte Stripe",
  billing_page_billingHistory_Title: "Historique de facturation",
  billing_page_billingHistory_Description: "Votre activité de facturation récente",
  billing_page_billingHistory_TableHead_InvoiceId: "ID de facture",
  billing_page_billingHistory_TableHead_PaidAmount: "Montant payé",
  billing_page_billingHistory_TableHead_Status: "Statut",
  billing_page_billingHistory_TableHead_Date: "Date",
  cancelSubscription_title: "Annuler l'abonnement",
  cancelSubscription_description: "En soumettant le formulaire, votre abonnement sera annulé. Veuillez nous indiquer pourquoi vous souhaitez annuler l'abonnement.",
  cancelSubscription_options_tooExpensive: "Trop cher",
  cancelSubscription_options_noLongerNeeded: "Plus nécessaire",
  cancelSubscription_options_switchingCompetitor: "Passage à un concurrent",
  cancelSubscription_options_otherReason: "Autre raison",
  cancelSubscription_label_pleaseSpecifiy: "Veuillez spécifier :",
  cancelSubscription_cancel: "Fermer",
  cancelSubscription_submitting: "Annulation de l'abonnement",
  cancelSubscription_submit: "Annuler l'abonnement",
  dashboard_notificationBanner_verifyEmail_1: "Veuillez vérifier votre adresse électronique",
  dashboard_notificationBanner_verifyEmail_2: "Un email est envoyé à ",
  dashboard_notificationBanner_verifyEmail_3: "Veuillez vérifier votre boîte de réception et votre dossier de spam.",
  dashboard_notificationBanner_subscriptionInfo_1: "jours restants dans votre periode de souscription, veuillez visiter",
  dashboard_notificationBanner_subscriptionInfo_2: "page de facturation",
  dashboard_notificationBanner_subscriptionInfo_3: "pour renouveler votre souscription.",
  analytics_chart_title: "Détail des revenus des cours",
  course_durationForm_minutes: "Minutes",
  chapters_durationForm_hoursLabel: "Heures",
  chapters_durationForm_minutesLabel: "Minutes",
  course_attachmentForm_name: "Nom de l'attachment",
  course_attachmentForm_file: "Fichier d'attachment",
  course_attachmentForm_submit: "Sauvegarder",
  course_attachmentForm_namePlaceholder: "Entrez le nom de l'attachment",
  course_attachmentForm_changeFile: "Changer de fichier",
  level_beginner: "Débutant",
  level_intermediate: "Intermédiaire",
  level_advanced: "Avancé",
  level_expert: "Expert",
  level_master: "Maître",
  banned: "Banni",
  not_banned: "pas banni",
  courses_setup_edit_chapter: "Éditer le Chapitre",
  data_table_title: "Titre",
  data_table_price: "Prix",
  data_table_published: "Publié",
  data_table_createdAt: "Créé",
  data_table_name: "Nom",
  data_table_color: "Couleur",
  data_table_Username: "Nom d'utilisateur",
  data_table_email: "Email",
  data_table_role: "Rôle",
  data_table_userIsBanned: "Utilisateur banni",
  data_table_edit: "Éditer",
  data_table_draft: "Brouillon",
  data_table_locale: "fr-FR",
  dashboard_popularCHapter_noFavorites: "Aucun chapitre favori pour le moment",
  settings_defaultLanguage_title: "Langue par défaut",
  post_setup_advertise_title: "Annoncez votre Publication", 
  post_LiveEventForm_noLiveEvent: "Aucun événement en direct sélectionné",
  post_LiveEventForm_title: "Événement en Direct",
  post_CourseForm_noCourse: "Aucun cours sélectionné",
  post_CourseForm_title: "Cours",
  linkedCourse_button_viewCourse: "View Course",
  linkedEvent_button_viewEvent: "Join Event",
};