export const Italiano: Record<string, string> = {
  documents: "documenti",
  document_hub: "hub dei documenti",
  type: "tipo",
  name: "nome",
  created_at: "creato a",
  administration: "amministrazione",
  create: "creare",
  create_file: "creare file",
  create_folder: "creare cartella",
  create_a_folder: "creare una cartella",
  edit_folder: "Modifica Cartella",
  edit_file: "Modifica File",
  public: "pubblico",
  cancel: "cancellare",
  placeholder: "Si prega di inserire il nome della cartella",
  placeholder_file: "Si prega di inserire il nome del file",
  edit: "modificare",
  file: "file",
  upload_file: "caricare file",
  update: "aggiornare",
  save: "salvare",
  rename: "rinominare",
  are_you_sure_you_want_to_delete: "Sei sicuro di voler eliminare",
  delete: "eliminare",
  a_file: "un file",
  a_folder: "una cartella",
  add: "aggiungere",
  navigation_administration_button_text: "Amministrazione",
  navigation_administration_button_text_exit: "Esci",
  navigation_theme_toggle_light: "Luce",
  navigation_theme_toggle_dark: "Scuro",
  navigation_theme_toggle_system: "Sistema",
  navigation_language_toggle_english: "Inglese",
  navigation_language_toggle_german: "Tedesco",
  navigation_language_toggle_french: "francese",
  navigation_language_toggle_spanish: "Spagnolo",
  navigation_language_toggle_italian: "Italiano",
  navigation_language_toggle_portuguese: "Portoghese",
  navigation_language_toggle_russian: "Russo",
  navigation_language_toggle_mandarin: "Mandarino",
  navigation_search_placeholder: "Cerca",
  navigation_footer_text: "Fornito da",
  navigation_footer_text_product: "Prodotto",
  search_courseCounter_currentCourses: "Corsi esistenti attuali",
  news_no_posts_found: "Nessun post trovato",
  news_comments_button_label: "Commenti",
  news_comments_input_placeholder: "Digita il tuo commento...",
  news_comments_showmore_label: "Mostra altro +",
  news_comments_reply_button_label: "Rispondi",
  live_event_futureAndPast_button_text_future: "Eventi futuri",
  live_event_futureAndPast_button_text_past: "Eventi passati",
  live_event_filter_button_text: "Filtrare",
  live_event_filter_title: "Filtro eventi dal vivo",
  live_event_filter_description:
    "Puoi filtrare gli eventi fornendo la data di inizio e/o di fine di un evento.",
  live_event_filter_applyFilter_button_text: "Applica filtro",
  live_event_filter_clearFilter_button_text: "Cancella filtro",
  courses_createCourse_button_text: "Crea Corso",
  courses_noCourses_text: "Nessun corso trovato",
  adminTable_previous_button_text: "Precedente",
  adminTable_next_button_text: "Successivo",
  courses_searchCourses_placeholder: "Filtra Corsi...",
  actions_unpublish: "Rimuovi pubblicazione",
  actions_publish: "Pubblica",
  courses_titleForm_title: "Titolo del Corso",
  courses_titleForm_cancel: "Annulla",
  courses_titleForm_edit: "Modifica Titolo",
  courses_titleForm_placeholder: "es. 'Sviluppo web avanzato'",
  courses_titleForm_save: "Salva",
  courses_descriptionForm_title: "Descrizione del Corso",
  courses_descriptionForm_cancel: "Annulla",
  courses_descriptionForm_edit: "Modifica Descrizione",
  courses_descriptionForm_empty: "Nessuna Descrizione",
  courses_descriptionForm_placeholder: "es. 'Questo corso tratta di...'",
  courses_descriptionForm_save: "Salva",
  course_imageForm_title: "Immagine del Corso",
  courses_imageForm_cancel: "Annulla",
  courses_imageForm_add: "Aggiungi un'Immagine",
  courses_imageForm_edit: "Modifica Immagine",
  courses_imageForm_aspectRatioRecoomendation:
    "Rapporto di aspetto consigliato 16:9",
  courses_categoryForm_title: "Categoria del Corso",
  courses_categoryForm_cancel: "Annulla",
  courses_categoryForm_edit: "Modifica Categoria",
  courses_categoryForm_noCategory: "Nessuna Categoria",
  courses_categoryForm_save: "Salva",
  courses_chaptersForm_title: "Capitoli del Corso",
  courses_chaptersForm_cancel: "Annulla",
  courses_chaptersForm_addChapter: "Aggiungi un Capitolo",
  courses_chaptersForm_placeholder: "es. 'Introduzione al corso'",
  courses_chaptersForm_save: "Crea",
  courses_chaptersForm_noChapters: "Nessun Capitolo",
  courses_chaptersForm_reorderInstructions:
    "Trascina e rilascia per riordinare i capitoli",
  course_priceForm_title: "Prezzo del Corso",
  courses_priceForm_cancel: "Annulla",
  courses_priceForm_edit: "Modifica Prezzo",
  courses_priceForm_noPrice: "Nessun Prezzo",
  courses_priceForm_placeholder: "Imposta un prezzo per il tuo corso",
  courses_priceForm_save: "Salva",
  course_attachmentForm_title: "Allegati del Capitolo",
  course_attachmentForm_cancel: "Annulla",
  course_attachmentForm_add: "Aggiungi un File",
  course_attachmentForm_noAttachments: "Nessun Allegato ancora",
  course_attachmentForm_Recoomendation:
    "Aggiungi qualsiasi cosa i tuoi studenti possano aver bisogno per completare il corso.",
  confirmModal_DialogHeader: "Sei sicuro?",
  confirmModal_DialogDescription: "Questa azione non può essere annullata.",
  confirmModal_DialogConfirm: "Conferma",
  confirmModal_DialogCancel: "Annulla",
  chapter_TitleForm_title: "Titolo del Capitolo",
  chapter_TitleForm_cancel: "Annulla",
  chapter_TitleForm_edit: "Modifica Titolo",
  chapter_TitleForm_save: "Salva",
  chapter_TitleForm_placeholder: "es. 'Introduzione al corso'",
  chapter_chapterDescriptionForm_title: "Descrizione del Capitolo",
  chapter_chapterDescriptionForm_cancel: "Annulla",
  chapter_chapterDescriptionForm_edit: "Modifica Descrizione",
  chapter_chapterDescriptionForm_noDescription: "Nessuna Descrizione",
  chapter_chapterDescriptionForm_save: "Salva",
  chapter_accessForm_title: "Accesso al Capitolo",
  chapter_accessForm_cancel: "Annulla",
  chapter_accessForm_edit: "Modifica Accesso",
  chapter_accessForm_isFree: "Questo capitolo è gratuito.",
  chapter_accessForm_isNotFree: "Questo capitolo non è gratuito.",
  chapter_accessForm_description:
    "Seleziona questa casella se vuoi rendere questo capitolo gratuito.",
  chapter_accessForm_save: "Salva",
  chapter_actions_unpublish: "Rimuovi pubblicazione",
  chapter_actions_publish: "Pubblica",
  chapter_VideoForm_title: "Video del Capitolo",
  chapter_VideoForm_cancel: "Annulla",
  chapter_VideoForm_edit: "Modifica Video",
  chapter_VideoForm_addVideo: "Aggiungi un Video",
  chapter_VideoForm_placeholder: "Link di condivisione Vimeo",
  chapter_VideoForm_urlWarning: "Aggiorna la pagina se il video non appare.",
  post_createPost_button_text: "Crea Post",
  post_noPosts_text: "Nessun post trovato.",
  post_search_placeholder_text: "Filtra Post...",
  posts_actions_unpublish: "Rimuovi pubblicazione",
  posts_actions_publish: "Pubblica",
  post_TitleForm_title: "Titolo del Post",
  post_TitleForm_cancel: "Annulla",
  post_TitleForm_edit: "Modifica Titolo",
  post_TitleForm_placeholder: "es. 'Sviluppo web avanzato'",
  post_TitleForm_save: "Salva",
  post_DescriptionForm_title: "Descrizione del Post",
  post_DescriptionForm_cancel: "Annulla",
  post_DescriptionForm_edit: "Modifica Descrizione",
  post_DescriptionForm_noDescription: "Nessuna Descrizione",
  post_DescriptionForm_save: "Salva",
  post_CategoryForm_title: "Categoria del Post",
  post_CategoryForm_cancel: "Annulla",
  post_CategoryForm_edit: "Modifica Categoria",
  post_CategoryForm_noCategory: "Nessuna Categoria",
  post_CategoryForm_save: "Salva",
  post_ImageForm_title: "Immagine del Post",
  post_ImageForm_cancel: "Annulla",
  post_ImageForm_add: "Aggiungi Immagine",
  post_ImageForm_edit: "Modifica Immagine",
  post_ImageForm_help: "Rapporto di aspetto consigliato 16:9",
  categories_search_placeholder_text: "Filtra Categorie...",
  categories_createCategory_button_text: "Crea Categoria",
  categories_noCategories_text: "Nessun Risultato.",
  categories_TitleForm_title: "Nome Categoria",
  categories_TitleForm_cancel: "Annulla",
  categories_TitleForm_edit: "Modifica Nome",
  categories_TitleForm_placeholder: "es. 'Sviluppo web avanzato'",
  categories_TitleForm_save: "Salva",
  category_ColorForm_title: "Colore Categoria",
  categories_ColorForm_cancel: "Annulla",
  categories_ColorForm_edit: "Modifica",
  categories_ColorForm_save: "Salva",
  post_CategoryTypeForm_title: "Tipo di Categoria",
  post_CategoryTypeForm_isCourseCategory: "Categoria Corso",
  post_CategoryTypeForm_isNewsCategory: "Categoria Notizie",
  post_CategoryTypeForm_isLiveEventCategory: "Categoria Evento dal Vivo",
  post_CategoryTypeForm_save: "Salva",
  customize_ContainerLinkForm_title: "Link Contenitore",
  customize_ContainerLinkForm_cancel: "Annulla",
  customize_ContainerLinkForm_edit: "Modifica Titolo",
  customize_ContainerLinkForm_placeholder: "es. 'Sviluppo web avanzato'",
  customize_ContainerLinkForm_save: "Salva",
  customize_ImageForm_title: "Immagine Contenitore",
  customize_ImageForm_cancel: "Annulla",
  customize_ImageForm_addImage: "Aggiungi un'Immagine",
  customize_ImageForm_edit: "Modifica Immagine",
  customize_ImageForm_imageHint: "Rapporto di aspetto consigliato 16:9",
  customize_PrimaryColorForm_title: "Colore Primario",
  customize_PrimaryColorForm_cancel: "Annulla",
  customize_PrimaryColorForm_edit: "Modifica",
  customize_PrimaryColorForm_save: "Salva",
  users_search_placeholder_text: "Filtra Profili...",
  users_noUsers_text: "Nessun Utente.",
  user_TitleForm_title: "Nome Utente",
  user_MailForm_title: "E-Mail Utente",
  user_RoleForm_title: "Ruolo Profilo",
  user_RoleForm_cancel: "Annulla",
  user_RoleForm_edit: "Modifica Ruolo",
  user_RoleForm_save: "Salva",
  chat_ChatMessages_loading: "Caricamento messaggi...",
  chat_ChatMessages_error: "Qualcosa è andato storto!",
  chat_ChatMessages_loadPreviousMessages: "Carica messaggi precedenti",
  chat_ChatItem_viewPDF: "File PDF",
  chat_ChatItem_edited: "(modificato)",
  chat_ChatItem_editMessage: "modifica Messaggio",
  chat_ChatItem_saveChanges: "Salva",
  chat_ChatItem_editMessageHint:
    "Premi escape per annullare, invio per salvare",
  chat_ChatInput_placeholder: "Messaggio",
  chat_initialModal_title: "Crea il tuo Server",
  chat_initialModal_description:
    "Dai una personalità al tuo server con un nome e un'immagine. Puoi sempre cambiarlo più tardi.",
  chat_initialModal_serverName: "Nome Server",
  chat_initialModal_serverName_placeholder: "Inserisci il nome del server",
  chat_initialModal_createServer: "Crea",
  chat_serverSection_createChannel: "Crea Canale",
  chat_serverSection_manageMembers: "Gestisci Membri",
  chat_server_search_placeholder: "Cerca",
  chat_server_search_notFound: "Nessun Risultato Trovato",
  chat_server_invite: "Invita Persone",
  chat_server_edit: "Modifica Server",
  chat_server_manage_members: "Gestisci Membri",
  chat_server_create_channel: "Crea Canale",
  chat_server_delete: "Elimina Server",
  chat_server_addServer: "Aggiungi un Server",
  chat_channel_edit: "Modifica",
  chat_channel_delete: "Elimina",
  chat_chatItem_edit: "Modifica",
  chat_chatItem_delete: "Elimina",
  chat_socket_reconnecting: "Riconnessione: polling ogni 1s",
  chat_socket_connected: "In Diretta",
  chat_modal_create_server_title: "Personalizza il tuo Server",
  chat_modal_create_server_description:
    "Dai al tuo server una personalità con un nome e un'immagine. Puoi sempre cambiarlo più tardi.",
  chat_modal_create_server_name: "Nome del server",
  chat_modal_create_server_name_placeholder: "Inserisci il nome del server",
  chat_modal_create_server_create: "Crea",
  chat_modal_create_channel_title: "Crea Canale",
  chat_modal_create_channel_name: "Nome del Canale",
  chat_modal_create_channel_name_placeholder: "Inserisci il nome del canale",
  chat_modal_create_channelType_name: "Tipo di Canale",
  chat_modal_create_channelType_placeholder: "Seleziona un tipo di canale",
  chat_modal_create_channel_create: "Crea",
  chat_modal_invite_title: "Invita Amici",
  chat_modal_invite_link_label: "Link di invito al server",
  chat_modal_invite_new: "Genera un nuovo link",
  chat_modal_manageMembers_title: "Gestisci Membri",
  chat_modal_manageMembers_description: "Membri",
  chat_modal_manageMembers_role_label: "Ruolo",
  chat_modal_manageMembers_role_guest: "Ospite",
  chat_modal_manageMembers_role_moderator: "Moderatore",
  chat_modal_manageMembers_kick: "Espelli",
  chat_modal_delete_server_title: "Elimina Server",
  chat_modal_delete_server_description_1: "Sei sicuro di voler fare questo?",
  chat_modal_delete_server_description_2: "sarà eliminato permanentemente.",
  chat_modal_delete_server_cancel_button: "Annulla",
  chat_modal_delete_server_delete_button: "Conferma",
  chat_modal_edit_channel_title: "Modifica Canale",
  chat_modal_edit_channel_name: "Nome del Canale",
  chat_modal_edit_channel_name_placeholder: "Inserisci il nome del canale",
  chat_modal_edit_channel_type: "Tipo di Canale",
  chat_modal_edit_channel_save: "Salva",
  chat_modal_edit_channel_type_placeholder: "Seleziona un tipo di canale",
  chat_modal_deleteChannel_title: "Elimina Canale",
  chat_modal_deleteChannel_description_1: "Sei sicuro di voler fare questo?",
  chat_modal_deleteChannel_description_2: "sarà eliminato permanentemente.",
  chat_modal_deleteChannel_cancel_button: "Annulla",
  chat_modal_deleteChannel_delete_button: "Conferma",
  chat_modal_leaveServer_title: "Lascia Server",
  chat_modal_leaveServer_description_1: "Sei sicuro di voler lasciare",
  chat_modal_leaveServer_cancel: "Annulla",
  chat_modal_leaveServer_leave: "Conferma",
  chat_modal_messageFile_title: "Aggiungi un allegato",
  chat_modal_messageFile_description: "Invia un file come messaggio",
  chat_modal_messageFile_submit: "Invia",
  createCourse_title: "Nomina il tuo Corso",
  createCourse_description:
    "Come desideri nominare il tuo corso? Non preoccuparti, potrai cambiarlo in seguito.",
  createCourse_form_label: "Titolo del Corso",
  createCourse_form_description: "Cosa insegnerai in questo corso?",
  createCourse_form_placeholder: "es. 'Sviluppo web avanzato'",
  createCourse_cancel: "Annulla",
  createCourse_submit: "Continua",
  createPost_title: "Nomina il tuo Post",
  createPost_description:
    "Come desideri nominare il tuo post? Non preoccuparti, potrai cambiarlo in seguito.",
  createPost_form_label: "Titolo del Post",
  createPost_form_placeholder: "es. 'Sviluppo web avanzato'",
  createPost_form_description: "Cosa vuoi far sapere alla tua Comunità?",
  createPost_cancel: "Annulla",
  createPost_submit: "Continua",
  createLiveEvent_title: "Nomina il tuo Evento Live",
  createLiveEvent_description:
    "Come desideri nominare il tuo evento live? Non preoccuparti, potrai cambiarlo in seguito.",
  createLiveEvent_form_label: "Titolo dell'Evento",
  createLiveEvent_form_placeholder: "es. 'Sviluppo web avanzato'",
  createLiveEvent_form_description: "Cosa mostrerai nel tuo evento?",
  createLiveEvent_cancel: "Annulla",
  createLiveEvent_submit: "Continua",
  createCategory_title: "Nomina la tua Categoria",
  createCategory_description:
    "Come desideri nominare la tua categoria? Non preoccuparti, potrai cambiarlo in seguito.",
  createCategory_form_label: "Nome della Categoria",
  createCategory_form_placeholder: "es. 'Sviluppo web avanzato'",
  createCategory_form_description: "Cosa categorizzerai sulla tua piattaforma?",
  createCategory_cancel: "Annulla",
  createCategory_submit: "Salva",
  liveEvent_createEvent_button_text: "Crea Evento Live",
  liveEvent_noEvent_text: "Nessun evento trovato.",
  liveEvent_filterEvents_placeholder: "Filtra Eventi...",
  infocard_courses: "Corsi",
  infocard_course: "Corso",
  infocard_inprogress: "In corso",
  infocard_completed: "Completato",
  no_courses: "Nessun corso trovato",
  customize_customizeCcontainer_title: "Personalizza il tuo Contenitore",
  customize_customizeCcontainer_requiredFields:
    "Completa tutti i campi obbligatori",
  customize_customizeYourContainer: "Personalizza il tuo Contenitore",
  requiredFields: "*obbligatorio",
  customize_AddImageTitle: "Aggiungi un'Immagine come Logo",
  chat_welcome_title: "Benvenuto su #",
  chat_welcome_description: "Questo è l'inizio del canale #",
  chat_welcome_description2: "canale",
  chat_welcome_title_directMessage:
    "Questo è l'inizio della tua conversazione con",
  serverSidebar_textChannel: "Canali Testuali",
  serverSidebar_videoChannel: "Canali Video",
  serverSidebar_audioChannel: "Canali Audio",
  serverSidebar_member: "Membri",
  chat_serversection_label_text: "Canali Testuali",
  chat_serversection_label_audio: "Canali Audio",
  chat_serversection_label_video: "Canali Video",
  chat_serversection_label_member: "Membri",
  chat_server_search_command_placeholder: "Cerca tra tutti i canali e membri",
  course_setup_title: "Configurazione del Corso",
  course_setup_undertitle: "Completa tutti i campi obbligatori",
  course_setup_course_information_title: "Personalizza il tuo corso",
  course_setup_price_title: "Vendi il tuo Corso",
  course_setup_chapters_title: "Capitoli del Corso",
  course_setup_attachments_title: "Risorse & Allegati",
  courses_chapter_backToCourse_button_text:
    "Torna alla Configurazione del Corso",
  courses_chapter_title: "Creazione Capitolo",
  courses_chapter_undertitle: "Completa tutti i campi",
  course_chapter_customize_title: "Personalizza il tuo Capitolo",
  course_chapter_access: "Impostazioni di Accesso",
  course_chapter_video: "Aggiungi un Video",
  courses_setup_free_badge: "Gratuito",
  courses_setup_published_text: "Pubblicato",
  courses_setup_draft_text: "Bozza",
  post_setup_title: "Configurazione Post",
  post_setup_undertitle: "Completa tutti i campi obbligatori",
  post_setup_customize_title: "Personalizza il tuo Post",
  post_setup_image_title: "Aggiungi un'Immagine al tuo Post",
  liveEvent_PremiumFeature_description:
    "Per utilizzare gli Eventi dal Vivo e configurare i tuoi eventi digitali e ibridi con il nostro software, devi utilizzare il pacchetto comunitario.",
  liveEvent_PremiumFeature_button_text: "Acquista Pacchetto Comunitario",
  liveEvent_setup_title: "Configurazione dell'Evento dal Vivo",
  liveEvent_setup_undertitle: "Completa tutti i campi obbligatori",
  liveEvent_setup_customize_title: "Personalizza il tuo Evento dal Vivo",
  liveEvent_setup_video_title: "Aggiungi le Risorse al tuo Evento",
  category_setup_title: "Configurazione della Categoria",
  category_setup_undertitle: "Completa tutti i campi obbligatori",
  category_setup_customize_title: "Nomina la tua Categoria",
  user_setup_title: "Configurazione Utente",
  user_setup_undertitle: "Completa tutti i campi obbligatori",
  user_setup_customize_title: "Personalizza l'Utente",
  course_unpublish_banner:
    "Questo corso non è pubblicato. Non sarà visibile agli Utenti.",
  post_unpublish_banner:
    "Questo post non è pubblicato. Non sarà visibile agli Utenti.",
  liveEvent_unpublish_banner:
    "Questo evento non è pubblicato. Non sarà visibile agli Utenti.",
  category_unpublish_banner:
    "Questa categoria non è pubblicata. Non sarà visibile agli Utenti.",
  chapter_unpublish_banner:
    "Questo capitolo non è pubblicato. Non sarà visibile agli Utenti.",
  analytics_total_revenue_label: "Ricavi Totali",
  analytics_total_sales_label: "Vendite Totali",
  customize_NavColors_title: "Personalizza i colori della tua navigazione",
  customize_navBackgroundColorForm_title: "Colore di sfondo della navigazione",
  customize_navDarkBackgroundColorForm_title:
    "Colore di sfondo della navigazione in modalità scura",
  customize_navPrimaryColorForm_title: "Colore primario della navigazione",
  customize_navDarkPrimaryColorForm_title:
    "Colore primario della navigazione in modalità scura",
  customize_customizeNavigation_title:
    "Personalizza i colori della tua navigazione",
  customize_NavColorsDark_title:
    "Personalizza i colori della tua navigazione in modalità scura",
  settings_menu_containersettings_title: "Impostazioni del contenitore",
  settings_menu_navigationdesign_title: "Design della navigazione",
  settings_backToMenu_button_text: "Torna al menu",
  nav_item_browse: "Sfoglia",
  nav_item_dashboard: "Cruscotto",
  nav_item_news: "Notizie",
  nav_item_liveEvent: "Evento dal Vivo",
  nav_item_chat: "Chat",
  nav_item_documents: "Documenti",
  nav_admin_item_course: "Corsi",
  nav_admin_item_posts: "Post",
  nav_admin_item_liveEvents: "Eventi dal Vivo",
  nav_admin_item_categories: "Categoria",
  nav_admin_item_users: "Utenti",
  nav_admin_item_analytics: "Analisi",
  nav_admin_item_settings: "Impostazioni",
  customize_ImageFormDark_title: "Immagine del contenitore in modalità scura",
  settings_Container_IconForm_title: "Icona del contenitore",
  privacy_policy_title: "Politica sulla Privacy e Termini e Condizioni",
  privacy_policy_description:
    "Per continuare a utilizzare la nostra piattaforma, si prega di esaminare e accettare la nostra Politica sulla Privacy e i Termini e Condizioni. La tua accettazione garantisce che hai letto e compreso come saranno gestiti i tuoi dati e accetti le regole che governano la nostra piattaforma. Valutiamo la tua privacy e ci sforziamo di fornire un ambiente sicuro per tutti gli utenti.",
  privacy_policy_button: "Ho letto e accetto",
  user_isBannedForm_title: "Stato di Bannato",
  user_isBannedForm_cancel: "Annulla",
  user_isBannedForm_edit: "Modifica",
  user_isBannedForm_save: "Salva",
  user_setup_settings_title: "Zona Pericolosa",
  courses_authorForm_cancel: "Anulla",
  courses_authorForm_edit: "Modifica autore",
  courses_authorForm_save: "Salva",
  courses_authorForm_placeholder: "es. 'Max Mustermann'",
  courses_authorForm_title: "Nome autore",
  courses_authorForm_empty: "vuoto",
  infocard_completedChapters: "Capitoli Completati",
  infocard_currentOnlineUsers: "Utenti Online Attuali",
  profile_manageAccount: "Gestisci account",
  profile_signOut: "Disconnettersi",
  profile_change_customize_username: "Cambia il tuo nome utente",
  profile_TitleForm_title: "Nome utente",
  profile_TitleForm_cancel: "Annulla",
  profile_TitleForm_edit: "Modifica",
  profile_TitleForm_placeholder: "NomeUtente123",
  profile_TitleForm_save: "Salva",
  courses_list_backToDashboard_button_text: "Torna al Dashboard",
  dashboard_courseTable_CourseStatus_Title: "I Miei Corsi",
  dashboard_courseTable_courseName: "Nome del Corso",
  dashboard_courseTable_paid: "Pagato",
  dashboard_courseTable_progress: "Progresso",
  dashboard_courseTable_chapter: "Capitolo",
  dashboard_courseTable_action: "Azione",
  dashboard_courseTable_viewAllCourses_button_text: "Visualizza tutto",
  dashboard_courseTable_viewCourse_button_text: "CERCARE",
  chapter_aboutcourse_title: "Informazioni sul Capitolo",
  chapter_ChapterDocuments_Title: "Documenti",
  courses_setup_backToCourseAdminList_button_text: "Torna alla Vista dei Corsi",
  post_setup_backToPostAdminList_button_text: "Torna alla Vista dei Post",
  liveEvent_setup_backToEventAdminList_button_text:
    "Torna alla Vista degli Eventi in Diretta",
  category_setup_backToCategoryAdminList_button_text:
    "Torna alla Vista delle Categorie",
  user_setup_backToUserAdminList_button_text: "Torna alla Vista degli Utenti",
  settings_backToAdminSettings_button_text:
    "Torna alla Vista delle Impostazioni",
  navigation_language_tooltip: "Lingue",
  navigation_mode_tooltip: "Modalità",
  navigation_administration_tooltip: "Amministrazione",
  navigation_profile_tooltip: "Profilo",
  privacy_policy_link: "Informativa sulla Privacy",
  privacy_termsOfService_link: "Termini di Servizio",
  chapter_attachments_NoDocuments: "Nessun documento",
  nav_item_career: "Carriera",
  nav_item_calendar: "Calendario",
  nav_item_knowledgeHub: "Centro di Conoscenza",
  profile_OnlineStatus_Online: "Online",
  profile_OnlineStatus_Away: "Non disponibile",
  profile_OnlineStatus_DoNotDisturb: "Non disturbare",
  profile_OnlineStatus_Invisible: "Invisibile",
  profile_OnlineStatus_Offline: "Offline",
  profile_status_text: "Stato",
  profile_help: "Aiuto",
  course_chapter_author_text: "Autore -",
  live_event_filter_start_date_text: "Data di inizio",
  live_event_filter_end_date_text: "Data di fine",
  chapter_aboutevent_title: "Informazioni sul Capitolo",
  chat_server_leave: "Lascia Server",
  settings_menu_design_title: "Pulsante Design",
  customize_customizeContainer_title: "Personalizza il tuo Contenitore",
  customize_PrimaryButtonColors_title:
    "Personalizza il tuo Colore del Pulsante Primario",
  customize_PrimaryButtonColorsDark_title:
    "Personalizza il tuo Colore del Pulsante Primario in Modalità Scura",
  customize_PrimaryButtonColorForm_title: "Colore del Pulsante Primario",
  customize_PrimaryButtonColorForm_cancel: "Annulla",
  customize_PrimaryButtonColorForm_edit: "Modifica",
  customize_PrimaryButtonColorForm_save: "Salva",
  customize_DarkPrimaryButtonColorForm_title:
    "Colore del Pulsante Primario in Modalità Scura",
  dashboard_popularChapter_chapterName_text: "Nome del capitolo",
  dashboard_popularChapter_courseName_text: "Nome del corso",
  dashboard_popularChapter_likes_text: "Mi piace",
  dashboard_popularChapter_comments_text: "Commenti",
  dashboard_popularChapter_action_text: "Azione",
  categories_ColorForm_title: "Colore della Categoria",
  profile_MemberIdForm_title: "ID membro",
  profile_MemberIdForm_cancel: "Annulla",
  profile_MemberIdForm_edit: "Modifica",
  profile_MemberIdForm_placeholder: "111",
  profile_MemberIdForm_save: "Salva",
  post_scheduleDateForm_title: "Programma Data e Ora",
  post_scheduleDateForm_cancel: "Annulla",
  post_scheduleDateForm_edit: "Modifica Data",
  post_scheduleDateForm_save: "Salva",
  liveEvent_TitleForm_title: "Titolo dell'Evento",
  liveEvent_TitleForm_cancel: "Annulla",
  liveEvent_TitleForm_edit: "Modifica Titolo",
  liveEvent_TitleForm_save: "Salva",
  liveEvent_DescriptionForm_title: "Descrizione dell'Evento",
  liveEvent_DescriptionForm_cancel: "Annulla",
  liveEvent_DescriptionForm_edit: "Modifica Descrizione",
  liveEvent_DescriptionForm_save: "Salva",
  liveEvent_CategoryForm_title: "Categoria dell'Evento",
  liveEvent_CategoryForm_cancel: "Annulla",
  liveEvent_CategoryForm_edit: "Modifica Categoria",
  liveEvent_CategoryForm_save: "Salva",
  liveEvent_startDateTimeForm_title: "Data e Ora di Inizio",
  liveEvent_startDateTimeForm_cancel: "Annulla",
  liveEvent_startDateTimeForm_edit: "Modifica Data",
  liveEvent_startDateTimeForm_save: "Salva",
  liveEvent_endDateTimeForm_title: "Data e Ora di Fine",
  liveEvent_endDateTimeForm_cancel: "Annulla",
  liveEvent_endDateTimeForm_edit: "Modifica Data",
  liveEvent_endDateTimeForm_save: "Salva",
  liveEvent_ImageForm_title: "Anteprima Evento",
  liveEvent_ImageForm_add: "Aggiungi Immagine",
  liveEvent_ImageForm_edit: "Modifica Immagine",
  liveEvent_ImageForm_description: "Rapporto d'aspetto 16:9 consigliato",
  liveEvent_videoForm_title: "Evento in Diretta",
  liveEvent_videoForm_cancel: "Annulla",
  liveEvent_videoForm_edit: "Modifica Video",
  liveEvent_videoForm_add: "Aggiungi Video",
  liveEvent_videoForm_save: "Salva",
  liveEvent_videoForm_preview: "Aggiorna la pagina se il video non appare.",
  dashboard_popularChapter_title: "Capitoli Più Popolari",
  sidebar_help: "Aiuto",
  sidebar_privacy_policy: "Politica sulla Privacy",
  profile_backToDashboard_button_text: "Torna alla dashboard",
  profile_EmailForm_title: "E-mail",
  profile_EmailForm_cancel: "Annulla",
  profile_EmailForm_edit: "Modifica",
  profile_EmailForm_placeholder: "es. 'max.mustermann@test.com'",
  profile_EmailForm_save: "Salva",
  profile_ImageForm_title: "Immagine del profilo",
  profile_ImageForm_cancel: "Annulla",
  profile_ImageForm_add: "Aggiungi immagine",
  profile_ImageForm_edit: "Modifica immagine",
  profile_ImageForm_help: "Rapporto di aspetto 1:1 consigliato",
  course_durationForm_title: "Durata del Corso",
  courses_durationForm_cancel: "Annulla",
  courses_durationForm_edit: "Modifica",
  course_durationForm_hours: "Ore",
  courses_durationForm_placeholder: "es. '2'",
  courses_durationForm_save: "Salva",
  courses_levelForm_title: "Livello del Corso",
  courses_levelForm_cancel: "Annulla",
  courses_levelForm_edit: "Modifica",
  courses_levelForm_noLevel: "Nessun Livello",
  courses_levelForm_save: "Salva",
  course_SpecialTypeForm_title: "Stato Speciale",
  course_SpecialTypeForm_isNew: "Nuovo",
  course_SpecialTypeForm_isFeatured: "In Evidenza",
  course_SpecialTypeForm_isBestseller: "Bestseller",
  course_SpecialTypeForm_save: "Salva",
  course_card_chapter: "Capitolo",
  course_card_chapters: "Capitoli",
  course_card_hour: "Ora",
  course_card_hours: "Ore",
  course_card_no_level: "Nessun livello",
  course_card_bestseller: "Bestseller",
  course_card_new: "Nuovo",
  course_card_featured: "In primo piano",
  course_card_edit: "Modifica",
  course_card_delete: "Elimina",
  descriptionModal_DialogHeader: "Descrizione",
  descriptionModal_DialogCancel: "Chiudi",
  courses_sidebar_infoDescription: "Descrizione del corso",
  news_myFavorites_title: "I miei Preferiti",
  news_Posts_title: "Post",
  news_LiveEvents_title: "Eventi Live",
  news_Courses_title: "Corsi",
  news_Chapters_title: "Capitoli",
  chapter_purchaseBanner_text:
    "Devi acquistare questo corso per guardare questo capitolo.",
  chat_modal_deleteMessage_title: "Elimina messaggio",
  chat_modal_deleteMessage_description1: "Sei sicuro di volerlo fare?",
  chat_modal_deleteMessage_description2:
    "Il messaggio sarà eliminato definitivamente.",
  chat_modal_deleteMessage_cancel: "Annulla",
  chat_modal_deleteMessage_confirm: "Conferma",
  liveEvent_chat_title: "Chat del live",
  liveEvent_chat_inputField: "Scrivi il tuo commento",
  liveEvent_start: "Inizia",
  liveEvent_end: "Finisce",
  course_enrollButton_free: "Iscriviti gratis",
  course_enrollButton: "Iscriviti per",
  course_progressButton_NotComplete: "Non completato",
  course_progressButton_MarkComplete: "Segna come completato",
  createContainer_title: "Nomina il tuo Contenitore",
  createCotainer_description: "Qual è il nome del Contenitore o Cliente che utilizzerai?",
  createContainer_form_label: "Nome del Contenitore",
  createContainer_form_placeholder: "es. 'Cliente XYZ'",
  createContainer_form_description: "Cosa insegnerai in questo contenitore?",
  createContainer_cancel: "Annulla",
  createContainer_submit: "Crea",
  dashboard_doughnutChart_title: "Statistiche del corso",
  liveEvent_eventMdal_title: "Vuoi terminare questa sessione?",
  liveEvent_eventMdal_no: "No",
  liveEvent_eventMdal_yes: "Sì",
  dashboard_doughnut_completed: "Completato",
  dashboard_doughnut_inprogress: "In corso",
  dashboard_doughnut_notStarted: "Non iniziato",
  dashboard_courseTable_viewFavoriteChapters_button_text: "I Miei Capitoli Preferiti",
  courses_list_backToCourses_button_text:"Torna ai Corsi",
  dashboard_courseTable_viewMyFavourties_button_text: "I Miei Corsi Preferiti",
  dashboard_eventTable_viewFavoriteEvents_button_text: "I Miei Eventi Preferiti",
  live_event_futureAndPast_button_text_all: "Tutti",
  no_events_found: "Nessun evento trovato",
  courses_list_backToLiveEvents_button_text: "Torna agli eventi live",
  goBack_button_text: "Indietro",
  profile_oldPassword_placeholder: "password attuale",
  profile_newPasswordForm_title: "Password",
  profile_newPasswordForm_cancel: "Annulla",
  profile_newPasswordForm_edit: "Modifica",
  profile_newPasswordForm_placeholder: "nuova password",
  profile_confirmPasswordForm_placeholder: "conferma nuova password",
  profile_newPasswordForm_save: "Salva",
  modal_share_link_title: "Condividi",
  modal_share_link_label: "Condividi link",
  profile_manageBilling: "Fatturazione",
  settings_menu_themedesign_title: "Design del tema",
  customize_customizeTheme_title: "Personalizza il colore del tuo tema",
  customize_ThemeColors_title: "Personalizza il colore del tuo tema",
  customize_ThemeColorForm_title: "Colore del tema",
  customize_ThemeColorForm_cancel: "Annulla",
  customize_ThemeColorForm_edit: "Modifica",
  customize_THemeColorForm_save: "Salva",
  customize_ThemeColorsDark_title: "Personalizza il colore del tuo tema per la modalità scura",
  customize_DarkThemeColorForm_title: "Colore del tema per la modalità scura",
  customize_ThemeColorForm_save: "Salva",
  settings_menu_authenticationdesign_title: "Design dell'autenticazione",
  customize_authDesignSettings_title: "Personalizza le tue pagine di autenticazione",
  customize_authDesignSettings_signUp_title: "Aggiungi un'immagine per la tua pagina di registrazione",
  customize_authDesignSettings_signIn_title: "Aggiungi un'immagine per la tua pagina di accesso",
  customize_authDesignSettings_forgetPassword_title: "Aggiungi un'immagine per la tua pagina di recupero password",
  customize_SignUpImageForm_title: "Immagine di registrazione",
  customize_SignUpImageForm_cancel: "Annulla",
  customize_SignUpImageForm_addImage: "Aggiungi immagine",
  customize_SignUpImageForm_edit: "Modifica",
  customize_SignUpImageForm_imageHint: "Rapporto d'aspetto 16:9 consigliato",
  customize_darkSignUpImageForm_title: "Immagine di registrazione per modalità scura",
  customize_darkSignUpImageForm_cancel: "Annulla",
  customize_darkSignUpImageForm_addImage: "Aggiungi immagine",
  customize_darkSignUpImageForm_edit: "Modifica",
  customize_darkSignUpImageForm_imageHint: "Rapporto d'aspetto 16:9 consigliato",
  customize_SignInImageForm_title: "Immagine di accesso",
  customize_SignInImageForm_cancel: "Annulla",
  customize_SignInImageForm_addImage: "Aggiungi immagine",
  customize_SignInImageForm_edit: "Modifica",
  customize_SignInImageForm_imageHint: "Rapporto d'aspetto 16:9 consigliato",
  customize_darkSignInImageForm_title: "Immagine di accesso per modalità scura",
  customize_darkSignInImageForm_cancel: "Annulla",
  customize_darkSignInImageForm_addImage: "Aggiungi immagine",
  customize_darkSignInImageForm_edit: "Modifica",
  customize_darkSignInImageForm_imageHint: "Rapporto d'aspetto 16:9 consigliato",
  customize_ForgePasswordImageForm_title: "Immagine per recupero password",
  customize_ForgePasswordImageForm_cancel: "Annulla",
  customize_ForgePasswordImageForm_addImage: "Aggiungi immagine",
  customize_ForgePasswordImageForm_edit: "Modifica",
  customize_ForgePasswordImageForm_imageHint: "Rapporto d'aspetto 16:9 consigliato",
  customize_darkForgePasswordImageForm_title: "Immagine per recupero password in modalità scura",
  customize_darkForgePasswordImageForm_cancel: "Annulla",
  customize_darkForgePasswordImageForm_addImage: "Aggiungi immagine",
  customize_darkForgePasswordImageForm_edit: "Modifica",
  customize_darkForgePasswordImageForm_imageHint: "Rapporto d'aspetto 16:9 consigliato",
  categories_TextColorForm_title: "Colore del testo della categoria",
  categories_TextColorForm_save: "Salva",
  categories_DarkTextColorForm_title: "Colore del testo della categoria per modalità scura",
  categories_DarkTextColorForm_save: "Salva",
  liveEvent_isStreamChatForm_title: "Chat in diretta",
  liveEvent_isStreamChatForm_isStreamChat: "Attiva chat in diretta",
  liveEvent_isStreamChatForm_save: "Salva",
  usergroups_search_placeholder_text: "Cerca",
  usergroups_createUsergroup_button_text: "Crea Gruppo Utenti",
  usergroups_noUsergroups_text: "Nessun Gruppo Utenti",
  usergroup_unpublish_banner: "Questo gruppo utenti non è pubblicato. Non funzionerà come previsto.",
  usergroup_setup_title: "Configurazione del Gruppo Utenti",
  usergroup_setup_undertitle: "Completa tutti i campi richiesti",
  usergroup_TitleForm_title: "Nome del Gruppo Utenti",
  usergroup_TitleForm_cancel: "Annulla",
  usergroup_TitleForm_edit: "Modifica",
  usergroup_TitleForm_placeholder: "Gruppo Esperti",
  usergroup_TitleForm_save: "Salva",
  nav_admin_item_usergroups: "Gruppi Utenti",
  createUsergroup_title: "Dai un nome al tuo Gruppo Utenti",
  createUsergroup_description: "Come vuoi chiamare il tuo Gruppo Utenti? Non preoccuparti, potrai cambiarlo più tardi.",
  createUsergroup_form_label: "Nome del Gruppo Utenti",
  createUsergroup_form_placeholder: "Gruppo di Test",
  createUsergroup_form_description: "A cosa servirà questo Gruppo Utenti specifico?",
  createUsergroup_cancel: "Annulla",
  createUsergroup_submit: "Salva",
  profile_UsergroupForm_title: "Gruppo Utenti",
  profile_UsergroupForm_cancel: "Annulla",
  profile_UsergroupForm_edit: "Modifica Gruppo Utenti",
  profile_UsergroupForm_allUsers: "Tutti gli Utenti",
  profile_UsergroupForm_save: "Salva",
  post_UsergroupForm_title: "Gruppo Utenti",
  post_UsergroupForm_cancel: "Annulla",
  post_UsergroupForm_edit: "Modifica Gruppo Utenti",
  post_UsergroupForm_allUsers: "Tutti gli Utenti",
  post_UsergroupForm_noUsergroup: "Nessun Gruppo Utenti",
  post_UsergroupForm_save: "Salva",
  liveEvent_UsergroupForm_title: "Gruppo Utenti",
  liveEvent_UsergroupForm_cancel: "Annulla",
  liveEvent_UsergroupForm_edit: "Modifica Gruppo Utenti",
  liveEvent_UsergroupForm_allUsers: "Tutti gli Utenti",
  liveEvent_UsergroupForm_save: "Salva",
  courses_UsergroupForm_title: "Gruppo Utenti",
  courses_UsergroupForm_cancel: "Annulla",
  courses_UsergroupForm_edit: "Modifica Gruppo Utenti",
  courses_UsergroupForm_allUsers: "Tutti gli Utenti",
  courses_UsergroupForm_save: "Salva",
  course_counter_courses: "corsi",
  course_counter_outOf: "di",
  usergroup_setup_customize_title: "Dai un nome al tuo gruppo di utenti",
  usergroup_setup_members_title: "Aggiungi membri",
  userList_table_header_name: "Nome",
  userList_table_header_email: "E-mail",
  userList_table_header_membership: "Abbonamento",
  userlist_table_body_isMember: "Membro",
  userlist_table_body_notMember: "Non membro",
  userList_pagination_showing: "Mostrando",
  userList_pagination_to: "a",
  userList_pagination_of: "di",
  userList_pagination_users: "utenti",
  userList_pagination_previous: "Precedente",
  userList_pagination_next: "Successivo",
  userList_search_placeholder: "Cerca utenti...",
  chapters_durationForm_title: "Durata del Capitolo",
  chapters_durationForm_cancel: "Annulla",
  chapters_durationForm_edit: "Modifica",
  chapters_durationForm_placeholder: "es. '2'",
  chapters_durationForm_save: "Salva",
  chapters_levelForm_title: "Livello del Capitolo",
  chapters_levelForm_cancel: "Annulla",
  chapters_levelForm_edit: "Modifica",
  chapters_levelForm_noLevel: "Nessun Livello",
  chapters_levelForm_save: "Salva",
  user_DeleteProfileForm_title: "Elimina profilo",
  settings_widgetButton_configure: "Configura",
  categories_ColorForm_ColorLabel: "Colore",
  categories_ColorForm_ColorFormDescription: "Seleziona un colore o inserisci un codice esadecimale",
  categories_TextColorForm_ColorLabel: "Colore del testo",
  categories_TextColorForm_ColorFormDescription: "Seleziona un colore o inserisci un codice esadecimale",
  categories_DarkTextColorForm_ColorLabel: "Colore del testo per la modalità scura",
  categories_DarkTextColorForm_ColorFormDescription: "Seleziona un colore o inserisci un codice esadecimale",
  post_CategoryTypeForm_isCourseCategory_Description: "Imposta questa categoria per essere utilizzata per i corsi",
  post_CategoryTypeForm_isNewsCategory_Description: "Imposta questa categoria per essere utilizzata per le notizie",
  post_CategoryTypeForm_isLiveEventCategory_Description: "Imposta questa categoria per essere utilizzata per eventi dal vivo",
  commonButton_cancel: "Annulla",
  commonButton_save: "Salva",
  user_RoleForm_Label: "Ruolo",
  user_UsergroupForm_Label: "Gruppo utenti",
  user_RoleForm_noRole: "Nessun ruolo assegnato",
  user_isBannedForm_Label: "Stato di ban dell'utente",
  customize_PrimaryButtonColorForm_ColorLabel: "Colore del pulsante principale",
  customize_DarkPrimaryButtonColorForm_ColorLabel: "Colore del pulsante principale per la modalità scura",
  customize_navPrimaryColorForm_ColorLabel: "Colore primario della navigazione",
  customize_navBackgroundColorForm_ColorLabel: "Colore di sfondo della navigazione",
  customize_navDarkPrimaryColorForm_ColorLabel: "Colore primario della navigazione per la modalità scura",
  customize_navDarkBackgroundColorForm_ColorLabel: "Colore di sfondo della navigazione per la modalità scura",
  customize_ThemeColorForm_ColorLabel: "Colore del tema",
  customize_DarkThemeColorForm_ColorLabel: "Colore del tema scuro",
  user_DeleteProfileForm_AlerTitle: "Avviso",
  user_DeleteProfileForm_AlerDescription: "Eliminare il tuo profilo è permanente e non può essere annullato. Tutti i tuoi dati saranno persi.",
  user_DeleteProfileForm_ConfirmModalTitle: "Sei sicuro?",
  user_DeleteProfileForm_ConfirmModalDescription: "Questa azione non può essere annullata. Il tuo account verrà eliminato permanentemente e i tuoi dati verranno rimossi dai nostri server.",
  user_DeleteProfileForm_ConfirmModalDeleteProfile: "Elimina profilo",
  chapters_levelForm_noAuthor: "Nessun autore",
  biliing_page_header: "Fatturazione e Abbonamento",
  billing_page_enterPaymentDetails: "Inserisci i dettagli di pagamento",
  billing_page_payment_endswith: "termina con",
  billing_page_payment_expires: "Scade",
  biliing_page_addCard: "Clicca per pagare con questa carta",
  biliing_page_backToPlans: "Torna ai Piani",
  billing_page_Tabs_Overview: "Panoramica",
  billing_page_Tabs_Plans: "Piani",
  billing_page_Tabs_Payment: "Pagamento",
  billing_page_Tabs_BillingHistory: "Cronologia Fatturazione",
  billing_page_overview_currentPlan: "Piano Attuale:",
  billing_page_overview_startTrialText: "Nessun piano selezionato - Clicca per avviare la tua prova di 14 giorni",
  billing_page_overview_changePlan: "Cambia Piano",
  billing_page_overview_cancelSubscription: "Annulla Abbonamento",
  billing_page_plans_monthly: "Mensile",
  billing_page_plans_yearly: "Annuale",
  billing_page_payment_title: "Metodi di Pagamento",
  billing_page_payment_description: "Gestisci i dettagli di pagamento",
  billing_page_payment_endsWith: "termina con",
  billing_page_payment_removeCard: "Rimuovi",
  billing_page_payment_noSavedPayment: "Nessun metodo di pagamento salvato.",
  billing_page_payment_AddPaymentMethod: "Aggiungi Metodo di Pagamento",
  billing_page_payment_connectStripe_title: "Collega Account Stripe",
  billing_page_payment_connectStripe_description: "Collega il tuo account Stripe per ricevere pagamenti",
  billing_page_payment_connectStripe_button: "Collega Account Stripe",
  billing_page_billingHistory_Title: "Cronologia Fatturazione",
  billing_page_billingHistory_Description: "La tua attività di fatturazione recente",
  billing_page_billingHistory_TableHead_InvoiceId: "ID Fattura",
  billing_page_billingHistory_TableHead_PaidAmount: "Importo Pagato",
  billing_page_billingHistory_TableHead_Status: "Stato",
  billing_page_billingHistory_TableHead_Date: "Data",
  cancelSubscription_title: "Annulla abbonamento",
  cancelSubscription_description: "Inviando il modulo, il tuo abbonamento verrà annullato. Per favore, dicci perché vuoi annullare l'abbonamento.",
  cancelSubscription_options_tooExpensive: "Troppo costoso",
  cancelSubscription_options_noLongerNeeded: "Non più necessario",
  cancelSubscription_options_switchingCompetitor: "Passaggio a un concorrente",
  cancelSubscription_options_otherReason: "Altra ragione",
  cancelSubscription_label_pleaseSpecifiy: "Per favore specifica:",
  cancelSubscription_cancel: "Chiudi",
  cancelSubscription_submitting: "Annullamento abbonamento",
  cancelSubscription_submit: "Annulla abbonamento",
  dashboard_notificationBanner_verifyEmail_1: "Per favore verifica il tuo indirizzo email",
  dashboard_notificationBanner_verifyEmail_2: "Un'email è stata inviata a ",
  dashboard_notificationBanner_verifyEmail_3: "Per favore controlla la tua casella di posta in arrivo e la cartella spam.",
  dashboard_notificationBanner_subscriptionInfo_1: "giorni rimanenti in periodo di sottoscrizione, per favore visita",
  dashboard_notificationBanner_subscriptionInfo_2: "pagina di fatturazione",
  dashboard_notificationBanner_subscriptionInfo_3: "per rinnovare la tua sottoscrizione.",
  analytics_chart_title: "Dettagli del reddito dei corsi",
  course_durationForm_minutes: "Minuti",
  chapters_durationForm_hoursLabel: "Ore",
  chapters_durationForm_minutesLabel: "Minuti",
  course_attachmentForm_name: "Nome dell'Allegato",
  course_attachmentForm_file: "File Allegato",
  course_attachmentForm_submit: "Salva",
  course_attachmentForm_namePlaceholder: "Inserisci il nome dell'allegato",
  course_attachmentForm_changeFile: "Cambia File",
  level_beginner: "Iniziante",
  level_intermediate: "Intermedio",
  level_advanced: "Avanzato",
  level_expert: "Esperto",
  level_master: "Maestro",
  banned: "Bannato",
  not_banned: "Non Bannato",
  courses_setup_edit_chapter: "Modifica Capitolo",
  data_table_title: "Titolo",
  data_table_price: "Prezzo",
  data_table_published: "Pubblicato",
  data_table_createdAt: "Creato il",
  data_table_name: "Nome",
  data_table_color: "Colore",
  data_table_Username: "Nombre de Usuario",
  data_table_email: "Correo Electrónico",
  data_table_role: "Rol",
  data_table_userIsBanned: "Usuario Prohibido",
  data_table_edit: "Editar",
  data_table_draft: "Borrador",
  data_table_locale: "es-ES",
  dashboard_popularCHapter_noFavorites: "No hay capitulos favoritos todavia",
  settings_defaultLanguage_title: "Idioma por Defecto",
  post_setup_advertise_title: "Pubblicizza il tuo Post",
  post_LiveEventForm_noLiveEvent: "Nessun evento dal vivo selezionato",
  post_LiveEventForm_title: "Evento dal Vivo",
  post_CourseForm_noCourse: "Nessun corso selezionato",
  post_CourseForm_title: "Corso",
  linkedCourse_button_viewCourse: "Visualizza Corso",
  linkedEvent_button_viewEvent: "Partecipa all'Evento",
  analytics_overviewContainer_title: "Analisi e Statistiche",
  analytics_overviewFinance_title: "Overview Finanziario",
  analytics_overviewCourse_title: "Analisi dei Corsi",
  analytics_overviewLiveEventAnalytics_title: "Analisi degli Eventi in diretta",
  analytics_overviewPostAnalytics_title: "Analisi delle pubblicazioni",
  analytics_widgetButton_view: "Visualizza",
  post_card_linked_items_title: "Elementi Collegati",
  linkedEvent_button_starts: "Comienza a",
  linkedEvent_button_ends: "Termina a",
  analytic_courses_totalCourses_label: "Corsi Totali",
  analytic_courses_totalChapters_label: "Capitoli Totali",
  analytic_courses_totalPurchasedCourses_label: "Acquisti Totali",
  analytic_courses_NotStartedCourses_label: "Corsi Non Iniziati",
  analytic_courses_inProgress_label: "In Corso",
  analytic_courses_completedCourses_label: "Corsi Completati",
  analytic_courses_coursePurchasDistribution_label: "Distribuzione Acquisti Corsi",
  analytic_courses_totalCourseLikes_label: "Totale Mi Piace ai Corsi",
  analytic_events_totalEvents_label: "Eventi Totali",
  analytic_events_upcomingEvents_label: "Eventi in Arrivo",
  analytic_events_pastEvents_label: "Eventi Passati",
  analytic_events_totalEventsLikes_label: "Totale Mi Piace agli Eventi",
  analytic_posts_totalPosts_label: "Post Totali",
  analytic_posts_totalPostsLikes_label: "Post con Commenti",
  analytic_posts_avgCommentsPosts_label: "Media Commenti per Post",
  analytic_posts_postEngagement_label: "Interazione sui Post",
  analytic_posts_postLikeEngagement_label: "Interazione Mi Piace sui Post",
};